__asm__(".section \".text\"");
__asm__(".align 2");
__asm__("b .main");
// now here are the lines from the GLOBAL section, typically #defines... 
// ======================================================================
// Include file below is generated by C-Builder      

// and contains the variables declared as -          

// PARAMETERS, INPUTS, OUTPUTS . . .                 

#define PI        3.1415926535897932384626433832795   // definition of PI                 

#define TWOPI     6.283185307179586476925286766559    // definition of 2.0*PI             

#define E         2.71828182845904523536028747135266  // definition of E                  

#define EINV      0.36787944117144232159552377016147  // definition of E Inverse (1/E)    

#define RT2       1.4142135623730950488016887242097   // definition of square root 2.0    

#define RT3       1.7320508075688772935274463415059   // definition of square root 3.0    

#define INV_ROOT2 0.70710678118654752440084436210485                                      

// finished the GLOBAL section (#defines)
// ======================================


// now here are the static variables the user has defined... 
//===========================================================


// -----------------------------------------------   

// Variables declared here may be used in both the   

// RAM: and CODE: sections below.                    

// -----------------------------------------------   

//    double dt;    



double W[100] = {-0.22583243, -0.3128571, -0.09350032, 0.05151762, -0.30170206, 0.10661154, 0.13397811, -0.11715875, 0.13758639, -0.37080519, 
                -0.31552383, 0.1287377, -0.32054045, -0.09309492, -0.16414183, 0.2120127, 0.27156818, -0.07757796, 0.04239552, 0.07195159, 
                0.35205592, -0.09705391, 0.33738564, -0.24524731, -0.28469208, 0.25013072, 0.34036605, 0.1005536, -0.33918098, -0.21197596, 
                -0.33672842, 0.24054585, 0.00333349, -0.21373718, 0.25202225, 0.1339504, -0.11438971, -0.202335, 0.22192653, -0.07065314, 
                -0.23420886, 0.21691918, -0.01982722, 0.04454983, 0.20905534, -0.12017015, -0.08227637, -0.05661371, 0.17212206, 0.32163402, 
                0.29030537, 0.28001923, 0.10797155, -0.0928586, -0.1715331, -0.22887881, 0.22965024, -0.07995217, -0.23201016, 0.31551534, 
                0.24058717, -0.00662784, 0.09372023, 0.36184834, -0.38582336, 0.20313682, -0.24181783, 0.02126562, -0.35802985, -0.05997331, 
                0.02444957, 0.26402214, -0.33622075, 0.06562539, -0.227391, 0.20884189, -0.02009295, 0.01609324, -0.19011545, -0.04081026, 
                -0.17759126, 0.18344933, 0.27615151, -0.14534336, 0.07648921, -0.269402, -0.17234415, -0.35345067, 0.07862321, -0.25229918, 
                0.34235341, 0.14599412, 0.24607825, 0.2897428, 0.02386395, 0.37469776, 0.25695225, 0.354817, -0.05244994, 0.03744153};



double b[10] = {0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0};



int N;

int n;

int Y;





// - E n d   o f   S T A T I C :   S e c t i o n -   



// end the user defined STATIC declarations ... 
//===========================================================

// declare the Parameters so that the user's code can reference them
// =================================================================
  int numInputs;  //Description

  int numOutputs; //Description

  int activation; //Description

  int batch_size; //Description


// end Parameter declarations 
// ========================== 


// declare the INPUTS so that the user's code can reference them
// ======================================================================
double* Learning_rate;
double* input1;
double* L1;
double* lamm;
double* input2;
double* input3;
double* input4;
double* input5;
double* input6;
double* input7;
double* input8;
double* input9;
double* input10;
double* L2;
double* L3;
double* L4;
double* L5;
double* L6;
double* L7;
double* L8;
double* L9;
double* L10;

// end INPUTS declarations 
// ================================ 


// declare the OUTPUTS so that the user's code can reference them
// ======================================================================
double* foutput;
double* foutput2;
double* foutput3;
double* foutput4;
double* foutput5;
double* foutput6;
double* foutput7;
double* foutput8;
double* foutput9;
double* foutput10;

// end OUTPUTS declarations 
// ================================ 


// declare the NODES so that the user's code can reference them
// ======================================================================

// end NODES declarations 
// ================================ 


// declare the GVALUES so that the user's code can reference them
// ======================================================================

// end GVALUES declarations 
// ================================ 


// declare the SWITCHED_GVALUES_INDEX so that the user's code can reference them
// ======================================================================

// end SWITCHED_GVALUES_INDEX declarations 
// ================================ 


// declare the INJECTIONS so that the user's code can reference them
// ======================================================================

// end INJECTIONS declarations 
// ================================ 

// methods from the CODE_FUNCTIONS section:
// ========================================
#include <builtin_gcc.h>

double X[10] = {0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0};

double X1[10] = {0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0};

double X11[10] = {0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0};



double a1[10]; //output array

double daa[10]={0.0};

double daa1[10]={0.0};

double loss[10] = {0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0};

int i;

int k;

int indx;



double L;



static void LoadX(int N){

X[0] = (*input1);
if (N>1){
	X[1] = (*input2);
	if (N>2){
		X[2] = (*input3);
		if (N>3){
			X[3] = (*input4);
			if (N>4){
				X[4] = (*input5);
				if (N>5){
					X[5] = (*input6);
					if (N>6){
						X[6] = (*input7);
						if (N>7){
							X[7] = (*input8);
							if (N>8){
								X[8] = (*input9);
								if (N>9){
									X[9] = (*input10);

								}
							}

						}
					}
				}
			}
		}
	}
	
}


}







static void FeedForward(int Y){

for (k = 0; k<Y; k++){
	indx = N*k;
	a1[k] = tanh(W[0+indx] * X[0]+ W[1+indx]*X[1] + W[2				+indx]*X[2] +W[3+indx]*X[3] + W[4+indx] * X[4]+ W[5	+indx]*X[5] + W[6+indx]*X[6] +W[7+indx]*X[7] +W[8	+indx]*X[8] +W[9+indx]*X[9] + b[k]); 
	daa[k] = 1 - a1[k]*a1[k];

}
}





static void Backprop(double Loss[6], int N, int Y, double alpha, double lamb){

for (k = 0; k<Y; k++){
	L = loss[k] * daa1[k];
	b[k] = b[k] - L*alpha;
	
	for (i = 0; i<N; i++){ 
		W[N*k+i] = W[N*k+i] - L* alpha* X1[i]- lamb * ((W[N*k+i] > 0) - (W[N*k+i] < 0));
}
}
}



static void saveX(int N){
for (i = 0; i<N; i++){ 

X11[i] = X1[i];
daa1[i] = daa[i];
X1[i] = X[i];
}
}



static void LoadL(int Y){
loss[0] = (*L1);
if (Y>1){
	loss[1] = (*L2);
	if (Y>2){
		loss[2] = (*L3);
		if (Y>3){
			loss[3] = (*L4);
			if (Y>4){
				loss[4] = (*L5);
				if (Y>5){
					loss[5] = (*L6);
					if (Y>6){
						loss[6] = (*L7);
						if (Y>7){
							loss[7] = (*L8);
							if (Y>8){
								loss[8] = (*L9);
								if (Y>9){
								 loss[9] =(*L10); 

								}
							}
						}
					}
				}
			}
		}
	}
	
}
}

// end of CODE_FUNCTIONS section:
// ==============================
void main(void)
{
	{
		int ___heap_addr_array_idx__ =0;
	}


if ((*Learning_rate)>0.0){

	LoadL(Y);
	Backprop(loss, N, Y, (*Learning_rate),(*lamm));

}



saveX(N);

LoadX(N);



FeedForward(Y);



(*foutput) = a1[0];

(*foutput2) = a1[1];

(*foutput3) = a1[2];

(*foutput4) = a1[3];

(*foutput5) = a1[4];

(*foutput6) = a1[5];

(*foutput7) = a1[6];

(*foutput8) = a1[7];

(*foutput9) = a1[8];

(*foutput10) = a1[9];











// -----------------------------------------------   

// Place C code here which runs on the RTDS. The     

// code below is entered once each simulation        

// step.                                             

// -----------------------------------------------   





// ------------ End of CODE: Section -------------   

}
