#include <stdio.h>
#include <string.h>

#include <cbuilder_ctrl_commonRW.h>

#include <math.h>

static char* checkSumC_lstmV2_4d5f1c821b4737cab2dcbaed0faea054;
extern void* rpcControlStructurePointer;
extern FILE* mapFile;


// now here are the lines from the GLOBAL section, typically #defines... 
// ======================================================================
// Include file below is generated by C-Builder      

// and contains the variables declared as -          

// PARAMETERS, INPUTS, OUTPUTS . . .                 

#define PI        3.1415926535897932384626433832795   // definition of PI                 

#define TWOPI     6.283185307179586476925286766559    // definition of 2.0*PI             

#define E         2.71828182845904523536028747135266  // definition of E                  

#define EINV      0.36787944117144232159552377016147  // definition of E Inverse (1/E)    

#define RT2       1.4142135623730950488016887242097   // definition of square root 2.0    

#define RT3       1.7320508075688772935274463415059   // definition of square root 3.0    

#define INV_ROOT2 0.70710678118654752440084436210485                                      

// finished the GLOBAL section (#defines)
// ======================================


// now here are the static variables the user has defined... 
//===========================================================


// -----------------------------------------------   

// Variables declared here may be used in both the   

// RAM: and CODE: sections below.                    

// -----------------------------------------------   

//    double dt;    



static int N;

static int Y;

static int T;

static int nodes;



static int i;

static int k;

static int t;

static int j;

static int y;





static double hloss[11] = {0.0};

static double dhloss[11] = {0.0};

static double Wloss[60] = {0.0};

static double h[11] = {0.0};

static double h_next[11] = {0.0};

static double h_all[110] = {0.0};



static double C[11] = {0.0};

static double Cprev[11] = {0.0};



static double dC[100] = {0.0};

static double dfg[100] = {0.0};

static double dig[100] = {0.0};

static double dcg[100] = {0.0};

static double dOg[100] = {0.0};



static double Fg = 0.0;

static double Ig = 0.0;

static double Cg = 0.0;

static double Og = 0.0;





static double dUf[100] = {0.0};

static double dUi[100] = {0.0};

static double dUc[100] = {0.0};

static double dUo[100] = {0.0};





//double Uf[100] = {0.0};

//double Ui[100] = {0.0};

//double Uc[100] = {0.0};

//double Uo[100] = {0.0};





//double Wf[60] = {0.0};

//double Wi[60] = {0.0};

//double Wc[60] = {0.0};

//double Wo[60] = {0.0};







//double W[60] = {0.0};



static double Wfx = 0.0;

static double Wcx = 0.0;

static double Wix = 0.0;

static double Wox = 0.0;

static double hf = 0.0;

static double hc = 0.0;

static double hi = 0.0;

static double ho = 0.0;



static double loss[6] = {0.0};

static double ddc = 0.0;



static double X[6] = {0.0};



static double X1[10] = {0.0};

static double X2[10] = {0.0};

static double X3[10] = {0.0};

static double X4[10] = {0.0};

static double X5[10] = {0.0};

static double X6[10] = {0.0};

static double out[6] = {0.0};

static int iter = 0;

static int f = 0.0;

static int f2 = 0.0;





static double tf = 0.0;

static double ti = 0.0;

static double tc = 0.0;

static double tO = 0.0;







static double Wi[2] = { 0.20922089, -0.42483646 };

static double Wf[2] = { 0.7553301, 0.48214918 };

static double Wc[2] = { 0.6274113, 0.6871158 };

static double Wo[2] = { 0.35571808, -0.56450665 };

static double Ui[1] = { 0.5652317 };

static double Uf[1] = { -0.8502836 };

static double Uc[1] = { -0.888813 };

static double Uo[1] = { 0.526938 };

static double bi[1] = { 0.8576933 };

static double bf[1] = { 1.39106 };

static double bc[1] = { -0.0018265678 };

static double bo[1] = { 2.4720716 };

static double W[1] = { 1.7440112 };

static double b[1] = { 0.0031973927 };













// - E n d   o f   S T A T I C :   S e c t i o n -   



// end the user defined STATIC declarations ... 
//===========================================================

// declare the Parameters so that the user's code can reference them
// =================================================================
static   double numInputs;  //Description

static   double numOutputs; //Description

static   double Timesteps;  //Description

static   double nod;        //Description


// end Parameter declarations 
// ========================== 


static void initializeParameterDataRW(void *this_)
{
    // initialize the Parameter values so that the user's code can reference them*/
    // ===========================================================================
    numInputs = getRealParameter(this_,"numInputs");
    numOutputs = getRealParameter(this_,"numOutputs");
    Timesteps = getRealParameter(this_,"Timesteps");
    nod = getRealParameter(this_,"nod");

    // end initializing Parameters 
    // =========================== 

}


static void saveInstance (void *this_, int R_proc1);

static void loadInstance (void *this_, int R_proc1);

/* copy the lines of code from the RAM_FUNCTIONS section */


// -----------------------------------------------   

// This section should contain any 'c' functions     

// to be called from the RAM section (either         

// RAM_PASS1 or RAM_PASS2). Example:                 

//                                                   

// static double myFunction(double v1, double v2)    

// {                                                 

//     return(v1*v2);                                

// }                                                 

// -----------------------------------------------   




static void initializeLocalDataRW(void *this_, int R_proc1)
{
    // initialize the local data based on a special section in the user's c code
    // ===========================================================================
    rpcControlStructurePointer = this_;

    // end initializing local data 
    // =========================== 

}


static void userSuppliedRamPass0Code(void* this_)
{
    rpcControlStructurePointer = this_;

    // copy the lines of code from the RAM_PASS0 section 
}

static void userSuppliedRamPass1Code(void* this_, int R_proc1)
{
    rpcControlStructurePointer = this_;
    void* comp = this_; //for psys component calls that used 'comp'

    // declare the variables the user has supplied in the RAM_DECLARATIONS section 

    // copy the lines of code from the RAM_PASS1 section 
}
static void* mallocInstancePointer (void *this_, int R_proc1)
{
  //  FILE *debugFile;
  //  debugFile = fopen("C:\\RTDS_USER\\testdebug.txt","a");
  //  fprintf(debugFile,"dbgcmb - entering mallocInstancePointer function for component lstmV2 R_proc1 = %i \n",R_proc1);
  //  fclose(debugFile);

    rpcControlStructurePointer = this_;
    void* staticInstancePointer = NULL; 
    int sizeOfStaticSection = 10048;
    int sizeOfLocalStaticSection = 0;
    staticInstancePointer = (void*)malloc(sizeOfStaticSection+sizeOfLocalStaticSection);
    return(staticInstancePointer);
}


static void saveInstance (void *this_, int R_proc1)
{
    rpcControlStructurePointer = this_;
    unsigned char* staticVariablesInstancePtr = getLocalStaticInstancePointer_RW(this_);
   // unsigned char* staticVariablesInstancePtr = NULL;
    if (staticVariablesInstancePtr == NULL)
    {
        staticVariablesInstancePtr = mallocInstancePointer (this_,R_proc1);
        setLocalStaticInstancePointer_RW(this_,staticVariablesInstancePtr);
    }

    unsigned char* tempPtr = staticVariablesInstancePtr;
    int index = 0;
    memcpy(tempPtr, (unsigned char*)&N,sizeof(N));
    tempPtr += sizeof(N);
    memcpy(tempPtr, (unsigned char*)&Y,sizeof(Y));
    tempPtr += sizeof(Y);
    memcpy(tempPtr, (unsigned char*)&T,sizeof(T));
    tempPtr += sizeof(T);
    memcpy(tempPtr, (unsigned char*)&nodes,sizeof(nodes));
    tempPtr += sizeof(nodes);
    memcpy(tempPtr, (unsigned char*)&i,sizeof(i));
    tempPtr += sizeof(i);
    memcpy(tempPtr, (unsigned char*)&k,sizeof(k));
    tempPtr += sizeof(k);
    memcpy(tempPtr, (unsigned char*)&t,sizeof(t));
    tempPtr += sizeof(t);
    memcpy(tempPtr, (unsigned char*)&j,sizeof(j));
    tempPtr += sizeof(j);
    memcpy(tempPtr, (unsigned char*)&y,sizeof(y));
    tempPtr += sizeof(y);
    memcpy(tempPtr, (unsigned char*)&hloss,sizeof(hloss));
    tempPtr += sizeof(hloss);
    memcpy(tempPtr, (unsigned char*)&dhloss,sizeof(dhloss));
    tempPtr += sizeof(dhloss);
    memcpy(tempPtr, (unsigned char*)&Wloss,sizeof(Wloss));
    tempPtr += sizeof(Wloss);
    memcpy(tempPtr, (unsigned char*)&h,sizeof(h));
    tempPtr += sizeof(h);
    memcpy(tempPtr, (unsigned char*)&h_next,sizeof(h_next));
    tempPtr += sizeof(h_next);
    memcpy(tempPtr, (unsigned char*)&h_all,sizeof(h_all));
    tempPtr += sizeof(h_all);
    memcpy(tempPtr, (unsigned char*)&C,sizeof(C));
    tempPtr += sizeof(C);
    memcpy(tempPtr, (unsigned char*)&Cprev,sizeof(Cprev));
    tempPtr += sizeof(Cprev);
    memcpy(tempPtr, (unsigned char*)&dC,sizeof(dC));
    tempPtr += sizeof(dC);
    memcpy(tempPtr, (unsigned char*)&dfg,sizeof(dfg));
    tempPtr += sizeof(dfg);
    memcpy(tempPtr, (unsigned char*)&dig,sizeof(dig));
    tempPtr += sizeof(dig);
    memcpy(tempPtr, (unsigned char*)&dcg,sizeof(dcg));
    tempPtr += sizeof(dcg);
    memcpy(tempPtr, (unsigned char*)&dOg,sizeof(dOg));
    tempPtr += sizeof(dOg);
    memcpy(tempPtr, (unsigned char*)&Fg,sizeof(Fg));
    tempPtr += sizeof(Fg);
    memcpy(tempPtr, (unsigned char*)&Ig,sizeof(Ig));
    tempPtr += sizeof(Ig);
    memcpy(tempPtr, (unsigned char*)&Cg,sizeof(Cg));
    tempPtr += sizeof(Cg);
    memcpy(tempPtr, (unsigned char*)&Og,sizeof(Og));
    tempPtr += sizeof(Og);
    memcpy(tempPtr, (unsigned char*)&dUf,sizeof(dUf));
    tempPtr += sizeof(dUf);
    memcpy(tempPtr, (unsigned char*)&dUi,sizeof(dUi));
    tempPtr += sizeof(dUi);
    memcpy(tempPtr, (unsigned char*)&dUc,sizeof(dUc));
    tempPtr += sizeof(dUc);
    memcpy(tempPtr, (unsigned char*)&dUo,sizeof(dUo));
    tempPtr += sizeof(dUo);
    memcpy(tempPtr, (unsigned char*)&Wfx,sizeof(Wfx));
    tempPtr += sizeof(Wfx);
    memcpy(tempPtr, (unsigned char*)&Wcx,sizeof(Wcx));
    tempPtr += sizeof(Wcx);
    memcpy(tempPtr, (unsigned char*)&Wix,sizeof(Wix));
    tempPtr += sizeof(Wix);
    memcpy(tempPtr, (unsigned char*)&Wox,sizeof(Wox));
    tempPtr += sizeof(Wox);
    memcpy(tempPtr, (unsigned char*)&hf,sizeof(hf));
    tempPtr += sizeof(hf);
    memcpy(tempPtr, (unsigned char*)&hc,sizeof(hc));
    tempPtr += sizeof(hc);
    memcpy(tempPtr, (unsigned char*)&hi,sizeof(hi));
    tempPtr += sizeof(hi);
    memcpy(tempPtr, (unsigned char*)&ho,sizeof(ho));
    tempPtr += sizeof(ho);
    memcpy(tempPtr, (unsigned char*)&loss,sizeof(loss));
    tempPtr += sizeof(loss);
    memcpy(tempPtr, (unsigned char*)&ddc,sizeof(ddc));
    tempPtr += sizeof(ddc);
    memcpy(tempPtr, (unsigned char*)&X,sizeof(X));
    tempPtr += sizeof(X);
    memcpy(tempPtr, (unsigned char*)&X1,sizeof(X1));
    tempPtr += sizeof(X1);
    memcpy(tempPtr, (unsigned char*)&X2,sizeof(X2));
    tempPtr += sizeof(X2);
    memcpy(tempPtr, (unsigned char*)&X3,sizeof(X3));
    tempPtr += sizeof(X3);
    memcpy(tempPtr, (unsigned char*)&X4,sizeof(X4));
    tempPtr += sizeof(X4);
    memcpy(tempPtr, (unsigned char*)&X5,sizeof(X5));
    tempPtr += sizeof(X5);
    memcpy(tempPtr, (unsigned char*)&X6,sizeof(X6));
    tempPtr += sizeof(X6);
    memcpy(tempPtr, (unsigned char*)&out,sizeof(out));
    tempPtr += sizeof(out);
    memcpy(tempPtr, (unsigned char*)&iter,sizeof(iter));
    tempPtr += sizeof(iter);
    memcpy(tempPtr, (unsigned char*)&f,sizeof(f));
    tempPtr += sizeof(f);
    memcpy(tempPtr, (unsigned char*)&f2,sizeof(f2));
    tempPtr += sizeof(f2);
    memcpy(tempPtr, (unsigned char*)&tf,sizeof(tf));
    tempPtr += sizeof(tf);
    memcpy(tempPtr, (unsigned char*)&ti,sizeof(ti));
    tempPtr += sizeof(ti);
    memcpy(tempPtr, (unsigned char*)&tc,sizeof(tc));
    tempPtr += sizeof(tc);
    memcpy(tempPtr, (unsigned char*)&tO,sizeof(tO));
    tempPtr += sizeof(tO);
    memcpy(tempPtr, (unsigned char*)&Wi,sizeof(Wi));
    tempPtr += sizeof(Wi);
    memcpy(tempPtr, (unsigned char*)&Wf,sizeof(Wf));
    tempPtr += sizeof(Wf);
    memcpy(tempPtr, (unsigned char*)&Wc,sizeof(Wc));
    tempPtr += sizeof(Wc);
    memcpy(tempPtr, (unsigned char*)&Wo,sizeof(Wo));
    tempPtr += sizeof(Wo);
    memcpy(tempPtr, (unsigned char*)&Ui,sizeof(Ui));
    tempPtr += sizeof(Ui);
    memcpy(tempPtr, (unsigned char*)&Uf,sizeof(Uf));
    tempPtr += sizeof(Uf);
    memcpy(tempPtr, (unsigned char*)&Uc,sizeof(Uc));
    tempPtr += sizeof(Uc);
    memcpy(tempPtr, (unsigned char*)&Uo,sizeof(Uo));
    tempPtr += sizeof(Uo);
    memcpy(tempPtr, (unsigned char*)&bi,sizeof(bi));
    tempPtr += sizeof(bi);
    memcpy(tempPtr, (unsigned char*)&bf,sizeof(bf));
    tempPtr += sizeof(bf);
    memcpy(tempPtr, (unsigned char*)&bc,sizeof(bc));
    tempPtr += sizeof(bc);
    memcpy(tempPtr, (unsigned char*)&bo,sizeof(bo));
    tempPtr += sizeof(bo);
    memcpy(tempPtr, (unsigned char*)&W,sizeof(W));
    tempPtr += sizeof(W);
    memcpy(tempPtr, (unsigned char*)&b,sizeof(b));
    tempPtr += sizeof(b);
}

static void loadInstance (void *this_, int R_proc1)
{
    rpcControlStructurePointer = this_;
    unsigned char* staticVariablesInstancePtr = getLocalStaticInstancePointer_RW(this_);
    unsigned char* tempPtr = staticVariablesInstancePtr;
    int index = 0;
    if (staticVariablesInstancePtr == NULL)
        return;
    memcpy((unsigned char*)&N, tempPtr, sizeof(N));
    tempPtr += sizeof(N);
    memcpy((unsigned char*)&Y, tempPtr, sizeof(Y));
    tempPtr += sizeof(Y);
    memcpy((unsigned char*)&T, tempPtr, sizeof(T));
    tempPtr += sizeof(T);
    memcpy((unsigned char*)&nodes, tempPtr, sizeof(nodes));
    tempPtr += sizeof(nodes);
    memcpy((unsigned char*)&i, tempPtr, sizeof(i));
    tempPtr += sizeof(i);
    memcpy((unsigned char*)&k, tempPtr, sizeof(k));
    tempPtr += sizeof(k);
    memcpy((unsigned char*)&t, tempPtr, sizeof(t));
    tempPtr += sizeof(t);
    memcpy((unsigned char*)&j, tempPtr, sizeof(j));
    tempPtr += sizeof(j);
    memcpy((unsigned char*)&y, tempPtr, sizeof(y));
    tempPtr += sizeof(y);
    memcpy((unsigned char*)&hloss, tempPtr, sizeof(hloss));
    tempPtr += sizeof(hloss);
    memcpy((unsigned char*)&dhloss, tempPtr, sizeof(dhloss));
    tempPtr += sizeof(dhloss);
    memcpy((unsigned char*)&Wloss, tempPtr, sizeof(Wloss));
    tempPtr += sizeof(Wloss);
    memcpy((unsigned char*)&h, tempPtr, sizeof(h));
    tempPtr += sizeof(h);
    memcpy((unsigned char*)&h_next, tempPtr, sizeof(h_next));
    tempPtr += sizeof(h_next);
    memcpy((unsigned char*)&h_all, tempPtr, sizeof(h_all));
    tempPtr += sizeof(h_all);
    memcpy((unsigned char*)&C, tempPtr, sizeof(C));
    tempPtr += sizeof(C);
    memcpy((unsigned char*)&Cprev, tempPtr, sizeof(Cprev));
    tempPtr += sizeof(Cprev);
    memcpy((unsigned char*)&dC, tempPtr, sizeof(dC));
    tempPtr += sizeof(dC);
    memcpy((unsigned char*)&dfg, tempPtr, sizeof(dfg));
    tempPtr += sizeof(dfg);
    memcpy((unsigned char*)&dig, tempPtr, sizeof(dig));
    tempPtr += sizeof(dig);
    memcpy((unsigned char*)&dcg, tempPtr, sizeof(dcg));
    tempPtr += sizeof(dcg);
    memcpy((unsigned char*)&dOg, tempPtr, sizeof(dOg));
    tempPtr += sizeof(dOg);
    memcpy((unsigned char*)&Fg, tempPtr, sizeof(Fg));
    tempPtr += sizeof(Fg);
    memcpy((unsigned char*)&Ig, tempPtr, sizeof(Ig));
    tempPtr += sizeof(Ig);
    memcpy((unsigned char*)&Cg, tempPtr, sizeof(Cg));
    tempPtr += sizeof(Cg);
    memcpy((unsigned char*)&Og, tempPtr, sizeof(Og));
    tempPtr += sizeof(Og);
    memcpy((unsigned char*)&dUf, tempPtr, sizeof(dUf));
    tempPtr += sizeof(dUf);
    memcpy((unsigned char*)&dUi, tempPtr, sizeof(dUi));
    tempPtr += sizeof(dUi);
    memcpy((unsigned char*)&dUc, tempPtr, sizeof(dUc));
    tempPtr += sizeof(dUc);
    memcpy((unsigned char*)&dUo, tempPtr, sizeof(dUo));
    tempPtr += sizeof(dUo);
    memcpy((unsigned char*)&Wfx, tempPtr, sizeof(Wfx));
    tempPtr += sizeof(Wfx);
    memcpy((unsigned char*)&Wcx, tempPtr, sizeof(Wcx));
    tempPtr += sizeof(Wcx);
    memcpy((unsigned char*)&Wix, tempPtr, sizeof(Wix));
    tempPtr += sizeof(Wix);
    memcpy((unsigned char*)&Wox, tempPtr, sizeof(Wox));
    tempPtr += sizeof(Wox);
    memcpy((unsigned char*)&hf, tempPtr, sizeof(hf));
    tempPtr += sizeof(hf);
    memcpy((unsigned char*)&hc, tempPtr, sizeof(hc));
    tempPtr += sizeof(hc);
    memcpy((unsigned char*)&hi, tempPtr, sizeof(hi));
    tempPtr += sizeof(hi);
    memcpy((unsigned char*)&ho, tempPtr, sizeof(ho));
    tempPtr += sizeof(ho);
    memcpy((unsigned char*)&loss, tempPtr, sizeof(loss));
    tempPtr += sizeof(loss);
    memcpy((unsigned char*)&ddc, tempPtr, sizeof(ddc));
    tempPtr += sizeof(ddc);
    memcpy((unsigned char*)&X, tempPtr, sizeof(X));
    tempPtr += sizeof(X);
    memcpy((unsigned char*)&X1, tempPtr, sizeof(X1));
    tempPtr += sizeof(X1);
    memcpy((unsigned char*)&X2, tempPtr, sizeof(X2));
    tempPtr += sizeof(X2);
    memcpy((unsigned char*)&X3, tempPtr, sizeof(X3));
    tempPtr += sizeof(X3);
    memcpy((unsigned char*)&X4, tempPtr, sizeof(X4));
    tempPtr += sizeof(X4);
    memcpy((unsigned char*)&X5, tempPtr, sizeof(X5));
    tempPtr += sizeof(X5);
    memcpy((unsigned char*)&X6, tempPtr, sizeof(X6));
    tempPtr += sizeof(X6);
    memcpy((unsigned char*)&out, tempPtr, sizeof(out));
    tempPtr += sizeof(out);
    memcpy((unsigned char*)&iter, tempPtr, sizeof(iter));
    tempPtr += sizeof(iter);
    memcpy((unsigned char*)&f, tempPtr, sizeof(f));
    tempPtr += sizeof(f);
    memcpy((unsigned char*)&f2, tempPtr, sizeof(f2));
    tempPtr += sizeof(f2);
    memcpy((unsigned char*)&tf, tempPtr, sizeof(tf));
    tempPtr += sizeof(tf);
    memcpy((unsigned char*)&ti, tempPtr, sizeof(ti));
    tempPtr += sizeof(ti);
    memcpy((unsigned char*)&tc, tempPtr, sizeof(tc));
    tempPtr += sizeof(tc);
    memcpy((unsigned char*)&tO, tempPtr, sizeof(tO));
    tempPtr += sizeof(tO);
    memcpy((unsigned char*)&Wi, tempPtr, sizeof(Wi));
    tempPtr += sizeof(Wi);
    memcpy((unsigned char*)&Wf, tempPtr, sizeof(Wf));
    tempPtr += sizeof(Wf);
    memcpy((unsigned char*)&Wc, tempPtr, sizeof(Wc));
    tempPtr += sizeof(Wc);
    memcpy((unsigned char*)&Wo, tempPtr, sizeof(Wo));
    tempPtr += sizeof(Wo);
    memcpy((unsigned char*)&Ui, tempPtr, sizeof(Ui));
    tempPtr += sizeof(Ui);
    memcpy((unsigned char*)&Uf, tempPtr, sizeof(Uf));
    tempPtr += sizeof(Uf);
    memcpy((unsigned char*)&Uc, tempPtr, sizeof(Uc));
    tempPtr += sizeof(Uc);
    memcpy((unsigned char*)&Uo, tempPtr, sizeof(Uo));
    tempPtr += sizeof(Uo);
    memcpy((unsigned char*)&bi, tempPtr, sizeof(bi));
    tempPtr += sizeof(bi);
    memcpy((unsigned char*)&bf, tempPtr, sizeof(bf));
    tempPtr += sizeof(bf);
    memcpy((unsigned char*)&bc, tempPtr, sizeof(bc));
    tempPtr += sizeof(bc);
    memcpy((unsigned char*)&bo, tempPtr, sizeof(bo));
    tempPtr += sizeof(bo);
    memcpy((unsigned char*)&W, tempPtr, sizeof(W));
    tempPtr += sizeof(W);
    memcpy((unsigned char*)&b, tempPtr, sizeof(b));
    tempPtr += sizeof(b);
}

DllExport int lstmV2_GET_NUM_NAMED_INPUTS(void *this_)
{
    //This comes from CmodelCompiler.createCtlExtraIOCode
    //int cntl_idx;
    int numNamedInputs = 0;
    //rpcControlStructurePointer = this_;
    //cntl_idx = 0;
    numNamedInputs = 0;
    return(numNamedInputs);
}
DllExport int lstmV2_GET_NUM_NAMED_OUTPUTS(void *this_)
{
    //This comes from CmodelCompiler.createCtlExtraIOCode
    //int cntl_idx;
    //rpcControlStructurePointer = this_;
    int numNamedOutputs = 0;
    //cntl_idx = 0;
    numNamedOutputs = 0;
    //this code from CmodelCompiler.createCtlExtraIOCode
    return(numNamedOutputs);
}
DllExport int lstmV2_ADD_EXTRA_IO(void *this_, int R_proc1)
{
    //This comes from CmodelCompiler.createCtlExtraIOCode
    int cntl_idx;
    rpcControlStructurePointer = this_;
    initializeParameterDataRW(this_);

    initializeLocalDataRW(this_, R_proc1);

    saveInstance(this_,R_proc1);  //new!
}
DllExport int lstmV2_GET_FLAG_PARTICIPATION(void *this_)
{
    //This comes from CmodelCompiler.createFlagParticipationCode
    int flags;
    flags = 0;
    flags = flags | 0x04;
    return(flags);
}

static void userSuppliedRamCode(int R_proc1)
{
   ramPassNumber = 2;


    /***** declare the variables the user has supplied in the RAM_DECLARATIONS section */

    /* copy the lines of code from the RAM section */
N = numInputs;

nodes = nod;

Y = numOutputs;

T = Timesteps;

// -----------------------------------------------   

// Place C code here which computes constants        

// required for the CODE: section below.  The C      

// code here is executed once, prior to the start    

// of the simulation case.                           

// -----------------------------------------------   

//    dt= getTimeStep();                             

// ------------- End of RAM: Section -------------   

}
DllExport void lstmV2_DM_RW (void *this_, int R_proc1,  int *wdadr_ptr1)
{
    rpcControlStructurePointer = this_;
    loadInstance(this_, R_proc1);  //new!
    initializeParameterDataRW(this_);
 //   initializeLocalDataRW(this_, R_proc1);    //<<<<<<<<<<<<<< TO-DO, change to this!
    int __inDMCode = 1;
    ramPassNumber = 1;
    FILE* signatureFile;
    //re-execute the Ram Pass1 code. This is necessary because
    //if more than one instance of a particular model is used in 
    //a case, all instances will share the same static variables.
    //This means the variables will have to be re-calculated before 
    //they are written out to data memory.

    //userSuppliedRamPass1Code(this_,R_proc1);  //<<<<<<<<<<<<<< TO-DO, change to this!
    //now call the Ram Pass2 code 

    ramPassNumber = 2;
    userSuppliedRamCode(R_proc1);
    double         __fdata=0;
    int            __idata=0;
    unsigned char *__bdata;
    char          *__pattern;
    int            __loopindex=0;
    char           __cdata[12]; //this is sized to match the Cdta entry in rt_ctl_data_t structure in rtdspc
    unsigned char* __blob;
    char*          __blob2;
    char          *__hexstring;
    char          *__pos;


    //1) storing variable x1
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"x1",1,1);

    //1) storing variable x2
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"x2",1,1);

    //1) storing variable x3
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"x3",1,1);

    //1) storing variable x4
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"x4",1,1);

    //1) storing variable x5
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"x5",1,1);

    //1) storing variable x6
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"x6",1,1);

    //1) storing variable L1
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"L1",1,1);

    //1) storing variable Lr
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"Lr",1,1);

    //1) storing variable lam
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"lam",1,1);

    //1) storing variable L2
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"L2",1,1);

    //1) storing variable L3
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"L3",1,1);

    //1) storing variable L4
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"L4",1,1);

    //1) storing variable L5
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"L5",1,1);

    //1) storing variable L6
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"L6",1,1);

    //2) storing variable foutput
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"foutput",0,1);

    //2) storing variable foutput2
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"foutput2",0,1);

    //2) storing variable foutput3
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"foutput3",0,1);

    //2) storing variable foutput4
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"foutput4",0,1);

    //2) storing variable foutput5
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"foutput5",0,1);

    //2) storing variable foutput6
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"foutput6",0,1);

    //2) storing variable testy
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"testy",0,1);
    //increasing wdadr_ptr1 in order to align variable numInputs with alignment requirement of 8
    *wdadr_ptr1 += 1;

    //3) storing variable numInputs
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"numInputs",1,1);

    //3) storing variable numOutputs
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"numOutputs",1,1);

    //3) storing variable Timesteps
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"Timesteps",1,1);

    //3) storing variable nod
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"nod",1,1);

    //3) storing variable N
    //----------------
     __bdata = (unsigned char*) malloc(4);
     endianSwapRW((unsigned char *)(&N),1,"i",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,1,"N");
    free(__bdata); //2
    //----------------


    //3) storing variable Y
    //----------------
     __bdata = (unsigned char*) malloc(4);
     endianSwapRW((unsigned char *)(&Y),1,"i",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,1,"Y");
    free(__bdata); //2
    //----------------


    //3) storing variable T
    //----------------
     __bdata = (unsigned char*) malloc(4);
     endianSwapRW((unsigned char *)(&T),1,"i",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,1,"T");
    free(__bdata); //2
    //----------------


    //3) storing variable nodes
    //----------------
     __bdata = (unsigned char*) malloc(4);
     endianSwapRW((unsigned char *)(&nodes),1,"i",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,1,"nodes");
    free(__bdata); //2
    //----------------


    //3) storing variable i
    //----------------
     __bdata = (unsigned char*) malloc(4);
     endianSwapRW((unsigned char *)(&i),1,"i",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,1,"i");
    free(__bdata); //2
    //----------------


    //3) storing variable k
    //----------------
     __bdata = (unsigned char*) malloc(4);
     endianSwapRW((unsigned char *)(&k),1,"i",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,1,"k");
    free(__bdata); //2
    //----------------


    //3) storing variable t
    //----------------
     __bdata = (unsigned char*) malloc(4);
     endianSwapRW((unsigned char *)(&t),1,"i",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,1,"t");
    free(__bdata); //2
    //----------------


    //3) storing variable j
    //----------------
     __bdata = (unsigned char*) malloc(4);
     endianSwapRW((unsigned char *)(&j),1,"i",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,1,"j");
    free(__bdata); //2
    //----------------


    //3) storing variable y
    //----------------
     __bdata = (unsigned char*) malloc(4);
     endianSwapRW((unsigned char *)(&y),1,"i",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,1,"y");
    free(__bdata); //2
    //----------------

    //increasing wdadr_ptr1 in order to align variable hloss with alignment requirement of 8
    *wdadr_ptr1 += 1;

    //3) storing variable hloss
    //----------------
     __bdata = (unsigned char*) malloc(88);
     endianSwapRW((unsigned char *)(&hloss),22,"DdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,22,"hloss");
    free(__bdata); //2
    //----------------


    //3) storing variable dhloss
    //----------------
     __bdata = (unsigned char*) malloc(88);
     endianSwapRW((unsigned char *)(&dhloss),22,"DdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,22,"dhloss");
    free(__bdata); //2
    //----------------


    //3) storing variable Wloss
    //----------------
     __bdata = (unsigned char*) malloc(480);
     endianSwapRW((unsigned char *)(&Wloss),120,"DdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,120,"Wloss");
    free(__bdata); //2
    //----------------


    //3) storing variable h
    //----------------
     __bdata = (unsigned char*) malloc(88);
     endianSwapRW((unsigned char *)(&h),22,"DdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,22,"h");
    free(__bdata); //2
    //----------------


    //3) storing variable h_next
    //----------------
     __bdata = (unsigned char*) malloc(88);
     endianSwapRW((unsigned char *)(&h_next),22,"DdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,22,"h_next");
    free(__bdata); //2
    //----------------


    //3) storing variable h_all
    //----------------
     __bdata = (unsigned char*) malloc(880);
     endianSwapRW((unsigned char *)(&h_all),220,"DdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,220,"h_all");
    free(__bdata); //2
    //----------------


    //3) storing variable C
    //----------------
     __bdata = (unsigned char*) malloc(88);
     endianSwapRW((unsigned char *)(&C),22,"DdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,22,"C");
    free(__bdata); //2
    //----------------


    //3) storing variable Cprev
    //----------------
     __bdata = (unsigned char*) malloc(88);
     endianSwapRW((unsigned char *)(&Cprev),22,"DdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,22,"Cprev");
    free(__bdata); //2
    //----------------


    //3) storing variable dC
    //----------------
     __bdata = (unsigned char*) malloc(800);
     endianSwapRW((unsigned char *)(&dC),200,"DdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,200,"dC");
    free(__bdata); //2
    //----------------


    //3) storing variable dfg
    //----------------
     __bdata = (unsigned char*) malloc(800);
     endianSwapRW((unsigned char *)(&dfg),200,"DdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,200,"dfg");
    free(__bdata); //2
    //----------------


    //3) storing variable dig
    //----------------
     __bdata = (unsigned char*) malloc(800);
     endianSwapRW((unsigned char *)(&dig),200,"DdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,200,"dig");
    free(__bdata); //2
    //----------------


    //3) storing variable dcg
    //----------------
     __bdata = (unsigned char*) malloc(800);
     endianSwapRW((unsigned char *)(&dcg),200,"DdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,200,"dcg");
    free(__bdata); //2
    //----------------


    //3) storing variable dOg
    //----------------
     __bdata = (unsigned char*) malloc(800);
     endianSwapRW((unsigned char *)(&dOg),200,"DdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,200,"dOg");
    free(__bdata); //2
    //----------------


    //3) storing variable Fg
    //----------------
     __bdata = (unsigned char*) malloc(8);
     endianSwapRW((unsigned char *)(&Fg),2,"Dd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,2,"Fg");
    free(__bdata); //2
    //----------------


    //3) storing variable Ig
    //----------------
     __bdata = (unsigned char*) malloc(8);
     endianSwapRW((unsigned char *)(&Ig),2,"Dd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,2,"Ig");
    free(__bdata); //2
    //----------------


    //3) storing variable Cg
    //----------------
     __bdata = (unsigned char*) malloc(8);
     endianSwapRW((unsigned char *)(&Cg),2,"Dd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,2,"Cg");
    free(__bdata); //2
    //----------------


    //3) storing variable Og
    //----------------
     __bdata = (unsigned char*) malloc(8);
     endianSwapRW((unsigned char *)(&Og),2,"Dd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,2,"Og");
    free(__bdata); //2
    //----------------


    //3) storing variable dUf
    //----------------
     __bdata = (unsigned char*) malloc(800);
     endianSwapRW((unsigned char *)(&dUf),200,"DdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,200,"dUf");
    free(__bdata); //2
    //----------------


    //3) storing variable dUi
    //----------------
     __bdata = (unsigned char*) malloc(800);
     endianSwapRW((unsigned char *)(&dUi),200,"DdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,200,"dUi");
    free(__bdata); //2
    //----------------


    //3) storing variable dUc
    //----------------
     __bdata = (unsigned char*) malloc(800);
     endianSwapRW((unsigned char *)(&dUc),200,"DdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,200,"dUc");
    free(__bdata); //2
    //----------------


    //3) storing variable dUo
    //----------------
     __bdata = (unsigned char*) malloc(800);
     endianSwapRW((unsigned char *)(&dUo),200,"DdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,200,"dUo");
    free(__bdata); //2
    //----------------


    //3) storing variable Wfx
    //----------------
     __bdata = (unsigned char*) malloc(8);
     endianSwapRW((unsigned char *)(&Wfx),2,"Dd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,2,"Wfx");
    free(__bdata); //2
    //----------------


    //3) storing variable Wcx
    //----------------
     __bdata = (unsigned char*) malloc(8);
     endianSwapRW((unsigned char *)(&Wcx),2,"Dd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,2,"Wcx");
    free(__bdata); //2
    //----------------


    //3) storing variable Wix
    //----------------
     __bdata = (unsigned char*) malloc(8);
     endianSwapRW((unsigned char *)(&Wix),2,"Dd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,2,"Wix");
    free(__bdata); //2
    //----------------


    //3) storing variable Wox
    //----------------
     __bdata = (unsigned char*) malloc(8);
     endianSwapRW((unsigned char *)(&Wox),2,"Dd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,2,"Wox");
    free(__bdata); //2
    //----------------


    //3) storing variable hf
    //----------------
     __bdata = (unsigned char*) malloc(8);
     endianSwapRW((unsigned char *)(&hf),2,"Dd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,2,"hf");
    free(__bdata); //2
    //----------------


    //3) storing variable hc
    //----------------
     __bdata = (unsigned char*) malloc(8);
     endianSwapRW((unsigned char *)(&hc),2,"Dd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,2,"hc");
    free(__bdata); //2
    //----------------


    //3) storing variable hi
    //----------------
     __bdata = (unsigned char*) malloc(8);
     endianSwapRW((unsigned char *)(&hi),2,"Dd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,2,"hi");
    free(__bdata); //2
    //----------------


    //3) storing variable ho
    //----------------
     __bdata = (unsigned char*) malloc(8);
     endianSwapRW((unsigned char *)(&ho),2,"Dd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,2,"ho");
    free(__bdata); //2
    //----------------


    //3) storing variable loss
    //----------------
     __bdata = (unsigned char*) malloc(48);
     endianSwapRW((unsigned char *)(&loss),12,"DdDdDdDdDdDdDdDdDdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,12,"loss");
    free(__bdata); //2
    //----------------


    //3) storing variable ddc
    //----------------
     __bdata = (unsigned char*) malloc(8);
     endianSwapRW((unsigned char *)(&ddc),2,"Dd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,2,"ddc");
    free(__bdata); //2
    //----------------


    //3) storing variable X
    //----------------
     __bdata = (unsigned char*) malloc(48);
     endianSwapRW((unsigned char *)(&X),12,"DdDdDdDdDdDdDdDdDdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,12,"X");
    free(__bdata); //2
    //----------------


    //3) storing variable X1
    //----------------
     __bdata = (unsigned char*) malloc(80);
     endianSwapRW((unsigned char *)(&X1),20,"DdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,20,"X1");
    free(__bdata); //2
    //----------------


    //3) storing variable X2
    //----------------
     __bdata = (unsigned char*) malloc(80);
     endianSwapRW((unsigned char *)(&X2),20,"DdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,20,"X2");
    free(__bdata); //2
    //----------------


    //3) storing variable X3
    //----------------
     __bdata = (unsigned char*) malloc(80);
     endianSwapRW((unsigned char *)(&X3),20,"DdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,20,"X3");
    free(__bdata); //2
    //----------------


    //3) storing variable X4
    //----------------
     __bdata = (unsigned char*) malloc(80);
     endianSwapRW((unsigned char *)(&X4),20,"DdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,20,"X4");
    free(__bdata); //2
    //----------------


    //3) storing variable X5
    //----------------
     __bdata = (unsigned char*) malloc(80);
     endianSwapRW((unsigned char *)(&X5),20,"DdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,20,"X5");
    free(__bdata); //2
    //----------------


    //3) storing variable X6
    //----------------
     __bdata = (unsigned char*) malloc(80);
     endianSwapRW((unsigned char *)(&X6),20,"DdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,20,"X6");
    free(__bdata); //2
    //----------------


    //3) storing variable out
    //----------------
     __bdata = (unsigned char*) malloc(48);
     endianSwapRW((unsigned char *)(&out),12,"DdDdDdDdDdDdDdDdDdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,12,"out");
    free(__bdata); //2
    //----------------


    //3) storing variable iter
    //----------------
     __bdata = (unsigned char*) malloc(4);
     endianSwapRW((unsigned char *)(&iter),1,"i",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,1,"iter");
    free(__bdata); //2
    //----------------


    //3) storing variable f
    //----------------
     __bdata = (unsigned char*) malloc(4);
     endianSwapRW((unsigned char *)(&f),1,"i",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,1,"f");
    free(__bdata); //2
    //----------------


    //3) storing variable f2
    //----------------
     __bdata = (unsigned char*) malloc(4);
     endianSwapRW((unsigned char *)(&f2),1,"i",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,1,"f2");
    free(__bdata); //2
    //----------------

    //increasing wdadr_ptr1 in order to align variable tf with alignment requirement of 8
    *wdadr_ptr1 += 1;

    //3) storing variable tf
    //----------------
     __bdata = (unsigned char*) malloc(8);
     endianSwapRW((unsigned char *)(&tf),2,"Dd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,2,"tf");
    free(__bdata); //2
    //----------------


    //3) storing variable ti
    //----------------
     __bdata = (unsigned char*) malloc(8);
     endianSwapRW((unsigned char *)(&ti),2,"Dd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,2,"ti");
    free(__bdata); //2
    //----------------


    //3) storing variable tc
    //----------------
     __bdata = (unsigned char*) malloc(8);
     endianSwapRW((unsigned char *)(&tc),2,"Dd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,2,"tc");
    free(__bdata); //2
    //----------------


    //3) storing variable tO
    //----------------
     __bdata = (unsigned char*) malloc(8);
     endianSwapRW((unsigned char *)(&tO),2,"Dd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,2,"tO");
    free(__bdata); //2
    //----------------


    //3) storing variable Wi
    //----------------
     __bdata = (unsigned char*) malloc(16);
     endianSwapRW((unsigned char *)(&Wi),4,"DdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,4,"Wi");
    free(__bdata); //2
    //----------------


    //3) storing variable Wf
    //----------------
     __bdata = (unsigned char*) malloc(16);
     endianSwapRW((unsigned char *)(&Wf),4,"DdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,4,"Wf");
    free(__bdata); //2
    //----------------


    //3) storing variable Wc
    //----------------
     __bdata = (unsigned char*) malloc(16);
     endianSwapRW((unsigned char *)(&Wc),4,"DdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,4,"Wc");
    free(__bdata); //2
    //----------------


    //3) storing variable Wo
    //----------------
     __bdata = (unsigned char*) malloc(16);
     endianSwapRW((unsigned char *)(&Wo),4,"DdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,4,"Wo");
    free(__bdata); //2
    //----------------


    //3) storing variable Ui
    //----------------
     __bdata = (unsigned char*) malloc(8);
     endianSwapRW((unsigned char *)(&Ui),2,"Dd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,2,"Ui");
    free(__bdata); //2
    //----------------


    //3) storing variable Uf
    //----------------
     __bdata = (unsigned char*) malloc(8);
     endianSwapRW((unsigned char *)(&Uf),2,"Dd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,2,"Uf");
    free(__bdata); //2
    //----------------


    //3) storing variable Uc
    //----------------
     __bdata = (unsigned char*) malloc(8);
     endianSwapRW((unsigned char *)(&Uc),2,"Dd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,2,"Uc");
    free(__bdata); //2
    //----------------


    //3) storing variable Uo
    //----------------
     __bdata = (unsigned char*) malloc(8);
     endianSwapRW((unsigned char *)(&Uo),2,"Dd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,2,"Uo");
    free(__bdata); //2
    //----------------


    //3) storing variable bi
    //----------------
     __bdata = (unsigned char*) malloc(8);
     endianSwapRW((unsigned char *)(&bi),2,"Dd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,2,"bi");
    free(__bdata); //2
    //----------------


    //3) storing variable bf
    //----------------
     __bdata = (unsigned char*) malloc(8);
     endianSwapRW((unsigned char *)(&bf),2,"Dd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,2,"bf");
    free(__bdata); //2
    //----------------


    //3) storing variable bc
    //----------------
     __bdata = (unsigned char*) malloc(8);
     endianSwapRW((unsigned char *)(&bc),2,"Dd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,2,"bc");
    free(__bdata); //2
    //----------------


    //3) storing variable bo
    //----------------
     __bdata = (unsigned char*) malloc(8);
     endianSwapRW((unsigned char *)(&bo),2,"Dd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,2,"bo");
    free(__bdata); //2
    //----------------


    //3) storing variable W
    //----------------
     __bdata = (unsigned char*) malloc(8);
     endianSwapRW((unsigned char *)(&W),2,"Dd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,2,"W");
    free(__bdata); //2
    //----------------


    //3) storing variable b
    //----------------
     __bdata = (unsigned char*) malloc(8);
     endianSwapRW((unsigned char *)(&b),2,"Dd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,2,"b");
    free(__bdata); //2
    //----------------


    //3) storing variable test
    //----------------

    //4) storing variable test: allocating blob of size 8 plus 3 because we need an extra 3 bytes to fill out the");
    //last 'unsigned char' to be a full 'int' in size, so that it sscanf properly with %2x. (otherwise it's nasty!!!)");
    __bdata = (unsigned char*)malloc(8+3);
    for (__loopindex=0; __loopindex<8; __loopindex++)
    {
        __bdata[__loopindex] = 0;
    }
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,2,"test");
    free(__bdata);  //1

    //3) storing variable .LC0
    //----------------

    //4) storing variable .LC0: allocating blob of size 8 plus 3 because we need an extra 3 bytes to fill out the");
    //last 'unsigned char' to be a full 'int' in size, so that it sscanf properly with %2x. (otherwise it's nasty!!!)");
    __bdata = (unsigned char*)malloc(8+3);
    __hexstring = "0000000000000000";
    __pos = __hexstring;
    for (__loopindex=0; __loopindex<8; __loopindex++)
    {
        sscanf(__pos,"%2x",&__bdata[__loopindex]);
        __pos += 2;
    }
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,2,".LC0");
    free(__bdata);  //1

    //3) storing variable .LC2
    //----------------

    //4) storing variable .LC2: allocating blob of size 4 plus 3 because we need an extra 3 bytes to fill out the");
    //last 'unsigned char' to be a full 'int' in size, so that it sscanf properly with %2x. (otherwise it's nasty!!!)");
    __bdata = (unsigned char*)malloc(4+3);
    __hexstring = "3f800000";
    __pos = __hexstring;
    for (__loopindex=0; __loopindex<4; __loopindex++)
    {
        sscanf(__pos,"%2x",&__bdata[__loopindex]);
        __pos += 2;
    }
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,1,".LC2");
    free(__bdata);  //1
    //increasing wdadr_ptr1 in order to keep functions aligned properly
    //-----------------------------------------------------------------
    *wdadr_ptr1 += 1;

    reserveMemoryForFunction_RW(getSubsystemIndex(),"exp.fsig",R_proc1,wdadr_ptr1,3);
    reserveMemoryForFunction_RW(getSubsystemIndex(),"tanh.fsig",R_proc1,wdadr_ptr1,3);
//setting the total size of the memory map to 11024
   freeScratchMemoryPointers();
}
DllExport void lstmV2_RR(void *this_, int R_proc1)
{
    rpcControlStructurePointer = this_;
    int __idata = 0;
    int __inDMCode = 0;
    int __extraData;
    ramPassNumber = 1;
    initializeParameterDataRW(this_);

    loadInstance(this_,R_proc1); //new!

    userSuppliedRamPass1Code(this_,R_proc1);
    saveInstance(this_,R_proc1);   //new!
    freeScratchMemoryPointers();
}
DllExport int lstmV2_getDMSize(void *this_, int R_proc1)
{
    return((11024)/4);
}
DllExport void lstmV2_INIT(void *this_)
{
    rpcControlStructurePointer = this_;
    ramPassNumber = 0;
    initializeParameterDataRW(this_);

    userSuppliedRamPass0Code(this_);
}
DllExport unsigned int lstmV2_getVariableDMOffset(char* variableName)
{
    int returnValue;
    if(strcmp("x1", variableName) == 0)
        returnValue = 0;
    else if(strcmp("x2", variableName) == 0)
        returnValue = 4;
    else if(strcmp("x3", variableName) == 0)
        returnValue = 8;
    else if(strcmp("x4", variableName) == 0)
        returnValue = 12;
    else if(strcmp("x5", variableName) == 0)
        returnValue = 16;
    else if(strcmp("x6", variableName) == 0)
        returnValue = 20;
    else if(strcmp("L1", variableName) == 0)
        returnValue = 24;
    else if(strcmp("Lr", variableName) == 0)
        returnValue = 28;
    else if(strcmp("lam", variableName) == 0)
        returnValue = 32;
    else if(strcmp("L2", variableName) == 0)
        returnValue = 36;
    else if(strcmp("L3", variableName) == 0)
        returnValue = 40;
    else if(strcmp("L4", variableName) == 0)
        returnValue = 44;
    else if(strcmp("L5", variableName) == 0)
        returnValue = 48;
    else if(strcmp("L6", variableName) == 0)
        returnValue = 52;
    else if(strcmp("foutput", variableName) == 0)
        returnValue = 56;
    else if(strcmp("foutput2", variableName) == 0)
        returnValue = 60;
    else if(strcmp("foutput3", variableName) == 0)
        returnValue = 64;
    else if(strcmp("foutput4", variableName) == 0)
        returnValue = 68;
    else if(strcmp("foutput5", variableName) == 0)
        returnValue = 72;
    else if(strcmp("foutput6", variableName) == 0)
        returnValue = 76;
    else if(strcmp("testy", variableName) == 0)
        returnValue = 80;
    else if(strcmp("numInputs", variableName) == 0)
        returnValue = 88;
    else if(strcmp("numOutputs", variableName) == 0)
        returnValue = 96;
    else if(strcmp("Timesteps", variableName) == 0)
        returnValue = 104;
    else if(strcmp("nod", variableName) == 0)
        returnValue = 112;
    else if(strcmp("N", variableName) == 0)
        returnValue = 120;
    else if(strcmp("Y", variableName) == 0)
        returnValue = 124;
    else if(strcmp("T", variableName) == 0)
        returnValue = 128;
    else if(strcmp("nodes", variableName) == 0)
        returnValue = 132;
    else if(strcmp("i", variableName) == 0)
        returnValue = 136;
    else if(strcmp("k", variableName) == 0)
        returnValue = 140;
    else if(strcmp("t", variableName) == 0)
        returnValue = 144;
    else if(strcmp("j", variableName) == 0)
        returnValue = 148;
    else if(strcmp("y", variableName) == 0)
        returnValue = 152;
    else if(strcmp("hloss", variableName) == 0)
        returnValue = 160;
    else if(strcmp("dhloss", variableName) == 0)
        returnValue = 248;
    else if(strcmp("Wloss", variableName) == 0)
        returnValue = 336;
    else if(strcmp("h", variableName) == 0)
        returnValue = 816;
    else if(strcmp("h_next", variableName) == 0)
        returnValue = 904;
    else if(strcmp("h_all", variableName) == 0)
        returnValue = 992;
    else if(strcmp("C", variableName) == 0)
        returnValue = 1872;
    else if(strcmp("Cprev", variableName) == 0)
        returnValue = 1960;
    else if(strcmp("dC", variableName) == 0)
        returnValue = 2048;
    else if(strcmp("dfg", variableName) == 0)
        returnValue = 2848;
    else if(strcmp("dig", variableName) == 0)
        returnValue = 3648;
    else if(strcmp("dcg", variableName) == 0)
        returnValue = 4448;
    else if(strcmp("dOg", variableName) == 0)
        returnValue = 5248;
    else if(strcmp("Fg", variableName) == 0)
        returnValue = 6048;
    else if(strcmp("Ig", variableName) == 0)
        returnValue = 6056;
    else if(strcmp("Cg", variableName) == 0)
        returnValue = 6064;
    else if(strcmp("Og", variableName) == 0)
        returnValue = 6072;
    else if(strcmp("dUf", variableName) == 0)
        returnValue = 6080;
    else if(strcmp("dUi", variableName) == 0)
        returnValue = 6880;
    else if(strcmp("dUc", variableName) == 0)
        returnValue = 7680;
    else if(strcmp("dUo", variableName) == 0)
        returnValue = 8480;
    else if(strcmp("Wfx", variableName) == 0)
        returnValue = 9280;
    else if(strcmp("Wcx", variableName) == 0)
        returnValue = 9288;
    else if(strcmp("Wix", variableName) == 0)
        returnValue = 9296;
    else if(strcmp("Wox", variableName) == 0)
        returnValue = 9304;
    else if(strcmp("hf", variableName) == 0)
        returnValue = 9312;
    else if(strcmp("hc", variableName) == 0)
        returnValue = 9320;
    else if(strcmp("hi", variableName) == 0)
        returnValue = 9328;
    else if(strcmp("ho", variableName) == 0)
        returnValue = 9336;
    else if(strcmp("loss", variableName) == 0)
        returnValue = 9344;
    else if(strcmp("ddc", variableName) == 0)
        returnValue = 9392;
    else if(strcmp("X", variableName) == 0)
        returnValue = 9400;
    else if(strcmp("X1", variableName) == 0)
        returnValue = 9448;
    else if(strcmp("X2", variableName) == 0)
        returnValue = 9528;
    else if(strcmp("X3", variableName) == 0)
        returnValue = 9608;
    else if(strcmp("X4", variableName) == 0)
        returnValue = 9688;
    else if(strcmp("X5", variableName) == 0)
        returnValue = 9768;
    else if(strcmp("X6", variableName) == 0)
        returnValue = 9848;
    else if(strcmp("out", variableName) == 0)
        returnValue = 9928;
    else if(strcmp("iter", variableName) == 0)
        returnValue = 9976;
    else if(strcmp("f", variableName) == 0)
        returnValue = 9980;
    else if(strcmp("f2", variableName) == 0)
        returnValue = 9984;
    else if(strcmp("tf", variableName) == 0)
        returnValue = 9992;
    else if(strcmp("ti", variableName) == 0)
        returnValue = 10000;
    else if(strcmp("tc", variableName) == 0)
        returnValue = 10008;
    else if(strcmp("tO", variableName) == 0)
        returnValue = 10016;
    else if(strcmp("Wi", variableName) == 0)
        returnValue = 10024;
    else if(strcmp("Wf", variableName) == 0)
        returnValue = 10040;
    else if(strcmp("Wc", variableName) == 0)
        returnValue = 10056;
    else if(strcmp("Wo", variableName) == 0)
        returnValue = 10072;
    else if(strcmp("Ui", variableName) == 0)
        returnValue = 10088;
    else if(strcmp("Uf", variableName) == 0)
        returnValue = 10096;
    else if(strcmp("Uc", variableName) == 0)
        returnValue = 10104;
    else if(strcmp("Uo", variableName) == 0)
        returnValue = 10112;
    else if(strcmp("bi", variableName) == 0)
        returnValue = 10120;
    else if(strcmp("bf", variableName) == 0)
        returnValue = 10128;
    else if(strcmp("bc", variableName) == 0)
        returnValue = 10136;
    else if(strcmp("bo", variableName) == 0)
        returnValue = 10144;
    else if(strcmp("W", variableName) == 0)
        returnValue = 10152;
    else if(strcmp("b", variableName) == 0)
        returnValue = 10160;
    else if(strcmp("test", variableName) == 0)
        returnValue = 10168;
    else if(strcmp(".LC0", variableName) == 0)
        returnValue = 10176;
    else if(strcmp(".LC2", variableName) == 0)
        returnValue = 10184;
    else 
        returnValue = 0xFFFFFFFF;  // Signal that the variable was not found.
    return returnValue;
}
