#include <stdio.h>
#include <string.h>

#include <cbuilder_ctrl_commonRW.h>

#include <math.h>

static char* checkSumC_OutputLv2TanhDense_cecc91072d0fd54f364cc9f24737ef43;
extern void* rpcControlStructurePointer;
extern FILE* mapFile;


// now here are the lines from the GLOBAL section, typically #defines... 
// ======================================================================
// Include file below is generated by C-Builder      

// and contains the variables declared as -          

// PARAMETERS, INPUTS, OUTPUTS . . .                 

#define PI        3.1415926535897932384626433832795   // definition of PI                 

#define TWOPI     6.283185307179586476925286766559    // definition of 2.0*PI             

#define E         2.71828182845904523536028747135266  // definition of E                  

#define EINV      0.36787944117144232159552377016147  // definition of E Inverse (1/E)    

#define RT2       1.4142135623730950488016887242097   // definition of square root 2.0    

#define RT3       1.7320508075688772935274463415059   // definition of square root 3.0    

#define INV_ROOT2 0.70710678118654752440084436210485                                      

// finished the GLOBAL section (#defines)
// ======================================


// now here are the static variables the user has defined... 
//===========================================================


// -----------------------------------------------   

// Variables declared here may be used in both the   

// RAM: and CODE: sections below.                    

// -----------------------------------------------   

//    double dt;    

static double W[60] = {-0.01194542, 0.02700008, -0.20097231, -0.19964591, 0.04697875, -0.2621471, 
               0.33185596, 0.14779643, 0.36256337, 0.02799838, 0.17271972, 0.13564832, 
               -0.20974577, 0.33184618, -0.05653329, 0.3977786, 0.06664755, 0.30365487, 
               0.37559894, 0.04899491, -0.18130616, -0.24870329, -0.34907727, 0.36320711, 
               0.11352973, 0.26516055, -0.1991046, 0.30390542, 0.14991587, -0.30060835, 
               -0.22997509, -0.15156108, -0.30925243, 0.06241518, -0.10372219, 0.32686743, 
               0.14239957, -0.01676829, 0.13334125, -0.25653699, -0.40567608, 0.38335856, 
               0.12191811, -0.14301099, 0.06033108, -0.42277535, 0.03786547, -0.14868022, 
               0.15301943, 0.3113031, 0.21232252, 0.20718283, 0.03385868, -0.39083904, 
               -0.09629824, 0.41479473, 0.10734768, 0.42113613, -0.18060257, 0.00439339};



static double b[6] = {0.0,0.0,0.0,0.0,0.0,0.0};



static double Wd[6] = {1.68943792, 0.90880629, 1.63581244, 0.50655374, -1.21481088, 0.55139419};



static double bd[6] = {0.0};



static int N;

static int n;

static int Y;





// - E n d   o f   S T A T I C :   S e c t i o n -   



// end the user defined STATIC declarations ... 
//===========================================================

// declare the Parameters so that the user's code can reference them
// =================================================================
static   int numInputs;   //Description

static   int numOutputs;  //Description

static   int AddDense;    //Description

static   int CrossCouple; //Description

static   int activation;  //Description


// end Parameter declarations 
// ========================== 


static void initializeParameterDataRW(void *this_)
{
    // initialize the Parameter values so that the user's code can reference them*/
    // ===========================================================================
    numInputs = getIntParameter(this_,"numInputs");
    numOutputs = getIntParameter(this_,"numOutputs");
    AddDense = getIntParameter(this_,"AddDense");
    CrossCouple = getIntParameter(this_,"CrossCouple");
    activation = getIntParameter(this_,"activation");

    // end initializing Parameters 
    // =========================== 

}


static void saveInstance (void *this_, int R_proc1);

static void loadInstance (void *this_, int R_proc1);

/* copy the lines of code from the RAM_FUNCTIONS section */


// -----------------------------------------------   

// This section should contain any 'c' functions     

// to be called from the RAM section (either         

// RAM_PASS1 or RAM_PASS2). Example:                 

//                                                   

// static double myFunction(double v1, double v2)    

// {                                                 

//     return(v1*v2);                                

// }                                                 

// -----------------------------------------------   




static void initializeLocalDataRW(void *this_, int R_proc1)
{
    // initialize the local data based on a special section in the user's c code
    // ===========================================================================
    rpcControlStructurePointer = this_;

    // end initializing local data 
    // =========================== 

}


static void userSuppliedRamPass0Code(void* this_)
{
    rpcControlStructurePointer = this_;

    // copy the lines of code from the RAM_PASS0 section 
}

static void userSuppliedRamPass1Code(void* this_, int R_proc1)
{
    rpcControlStructurePointer = this_;
    void* comp = this_; //for psys component calls that used 'comp'

    // declare the variables the user has supplied in the RAM_DECLARATIONS section 

    // copy the lines of code from the RAM_PASS1 section 
}
static void* mallocInstancePointer (void *this_, int R_proc1)
{
  //  FILE *debugFile;
  //  debugFile = fopen("C:\\RTDS_USER\\testdebug.txt","a");
  //  fprintf(debugFile,"dbgcmb - entering mallocInstancePointer function for component OutputLv2TanhDense R_proc1 = %i \n",R_proc1);
  //  fclose(debugFile);

    rpcControlStructurePointer = this_;
    void* staticInstancePointer = NULL; 
    int sizeOfStaticSection = 636;
    int sizeOfLocalStaticSection = 0;
    staticInstancePointer = (void*)malloc(sizeOfStaticSection+sizeOfLocalStaticSection);
    return(staticInstancePointer);
}


static void saveInstance (void *this_, int R_proc1)
{
    rpcControlStructurePointer = this_;
    unsigned char* staticVariablesInstancePtr = getLocalStaticInstancePointer_RW(this_);
   // unsigned char* staticVariablesInstancePtr = NULL;
    if (staticVariablesInstancePtr == NULL)
    {
        staticVariablesInstancePtr = mallocInstancePointer (this_,R_proc1);
        setLocalStaticInstancePointer_RW(this_,staticVariablesInstancePtr);
    }

    unsigned char* tempPtr = staticVariablesInstancePtr;
    int index = 0;
    memcpy(tempPtr, (unsigned char*)&W,sizeof(W));
    tempPtr += sizeof(W);
    memcpy(tempPtr, (unsigned char*)&b,sizeof(b));
    tempPtr += sizeof(b);
    memcpy(tempPtr, (unsigned char*)&Wd,sizeof(Wd));
    tempPtr += sizeof(Wd);
    memcpy(tempPtr, (unsigned char*)&bd,sizeof(bd));
    tempPtr += sizeof(bd);
    memcpy(tempPtr, (unsigned char*)&N,sizeof(N));
    tempPtr += sizeof(N);
    memcpy(tempPtr, (unsigned char*)&n,sizeof(n));
    tempPtr += sizeof(n);
    memcpy(tempPtr, (unsigned char*)&Y,sizeof(Y));
    tempPtr += sizeof(Y);
}

static void loadInstance (void *this_, int R_proc1)
{
    rpcControlStructurePointer = this_;
    unsigned char* staticVariablesInstancePtr = getLocalStaticInstancePointer_RW(this_);
    unsigned char* tempPtr = staticVariablesInstancePtr;
    int index = 0;
    if (staticVariablesInstancePtr == NULL)
        return;
    memcpy((unsigned char*)&W, tempPtr, sizeof(W));
    tempPtr += sizeof(W);
    memcpy((unsigned char*)&b, tempPtr, sizeof(b));
    tempPtr += sizeof(b);
    memcpy((unsigned char*)&Wd, tempPtr, sizeof(Wd));
    tempPtr += sizeof(Wd);
    memcpy((unsigned char*)&bd, tempPtr, sizeof(bd));
    tempPtr += sizeof(bd);
    memcpy((unsigned char*)&N, tempPtr, sizeof(N));
    tempPtr += sizeof(N);
    memcpy((unsigned char*)&n, tempPtr, sizeof(n));
    tempPtr += sizeof(n);
    memcpy((unsigned char*)&Y, tempPtr, sizeof(Y));
    tempPtr += sizeof(Y);
}

DllExport int OutputLv2TanhDense_GET_NUM_NAMED_INPUTS(void *this_)
{
    //This comes from CmodelCompiler.createCtlExtraIOCode
    //int cntl_idx;
    int numNamedInputs = 0;
    //rpcControlStructurePointer = this_;
    //cntl_idx = 0;
    numNamedInputs = 0;
    return(numNamedInputs);
}
DllExport int OutputLv2TanhDense_GET_NUM_NAMED_OUTPUTS(void *this_)
{
    //This comes from CmodelCompiler.createCtlExtraIOCode
    //int cntl_idx;
    //rpcControlStructurePointer = this_;
    int numNamedOutputs = 0;
    //cntl_idx = 0;
    numNamedOutputs = 0;
    //this code from CmodelCompiler.createCtlExtraIOCode
    return(numNamedOutputs);
}
DllExport int OutputLv2TanhDense_ADD_EXTRA_IO(void *this_, int R_proc1)
{
    //This comes from CmodelCompiler.createCtlExtraIOCode
    int cntl_idx;
    rpcControlStructurePointer = this_;
    initializeParameterDataRW(this_);

    initializeLocalDataRW(this_, R_proc1);

    saveInstance(this_,R_proc1);  //new!
}
DllExport int OutputLv2TanhDense_GET_FLAG_PARTICIPATION(void *this_)
{
    //This comes from CmodelCompiler.createFlagParticipationCode
    int flags;
    flags = 0;
    flags = flags | 0x04;
    return(flags);
}

static void userSuppliedRamCode(int R_proc1)
{
   ramPassNumber = 2;


    /***** declare the variables the user has supplied in the RAM_DECLARATIONS section */

    /* copy the lines of code from the RAM section */
n = numInputs + numOutputs;

N = numInputs;

Y = numOutputs;

// -----------------------------------------------   

// Place C code here which computes constants        

// required for the CODE: section below.  The C      

// code here is executed once, prior to the start    

// of the simulation case.                           

// -----------------------------------------------   

//    dt= getTimeStep();                             

// ------------- End of RAM: Section -------------   

}
DllExport void OutputLv2TanhDense_DM_RW (void *this_, int R_proc1,  int *wdadr_ptr1)
{
    rpcControlStructurePointer = this_;
    loadInstance(this_, R_proc1);  //new!
    initializeParameterDataRW(this_);
 //   initializeLocalDataRW(this_, R_proc1);    //<<<<<<<<<<<<<< TO-DO, change to this!
    int __inDMCode = 1;
    ramPassNumber = 1;
    FILE* signatureFile;
    //re-execute the Ram Pass1 code. This is necessary because
    //if more than one instance of a particular model is used in 
    //a case, all instances will share the same static variables.
    //This means the variables will have to be re-calculated before 
    //they are written out to data memory.

    //userSuppliedRamPass1Code(this_,R_proc1);  //<<<<<<<<<<<<<< TO-DO, change to this!
    //now call the Ram Pass2 code 

    ramPassNumber = 2;
    userSuppliedRamCode(R_proc1);
    double         __fdata=0;
    int            __idata=0;
    unsigned char *__bdata;
    char          *__pattern;
    int            __loopindex=0;
    char           __cdata[12]; //this is sized to match the Cdta entry in rt_ctl_data_t structure in rtdspc
    unsigned char* __blob;
    char*          __blob2;
    char          *__hexstring;
    char          *__pos;


    //1) storing variable Learning_rate
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"Learning_rate",1,1);

    //1) storing variable input1
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"input1",1,1);

    //1) storing variable L1
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"L1",1,1);

    //1) storing variable lam
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"lam",1,1);

    //1) storing variable input2
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"input2",1,1);

    //1) storing variable input3
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"input3",1,1);

    //1) storing variable input4
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"input4",1,1);

    //1) storing variable input5
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"input5",1,1);

    //1) storing variable input6
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"input6",1,1);

    //1) storing variable input7
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"input7",1,1);

    //1) storing variable input8
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"input8",1,1);

    //1) storing variable input9
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"input9",1,1);

    //1) storing variable input10
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"input10",1,1);

    //1) storing variable L2
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"L2",1,1);

    //1) storing variable L3
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"L3",1,1);

    //1) storing variable L4
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"L4",1,1);

    //1) storing variable L5
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"L5",1,1);

    //1) storing variable L6
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"L6",1,1);

    //2) storing variable foutput
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"foutput",0,1);

    //2) storing variable Li1
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"Li1",0,1);

    //2) storing variable Li2
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"Li2",0,1);

    //2) storing variable Li3
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"Li3",0,1);

    //2) storing variable Li4
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"Li4",0,1);

    //2) storing variable Li5
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"Li5",0,1);

    //2) storing variable Li6
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"Li6",0,1);

    //2) storing variable Li7
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"Li7",0,1);

    //2) storing variable Li8
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"Li8",0,1);

    //2) storing variable Li9
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"Li9",0,1);

    //2) storing variable Li10
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"Li10",0,1);

    //2) storing variable foutput2
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"foutput2",0,1);

    //2) storing variable foutput3
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"foutput3",0,1);

    //2) storing variable foutput4
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"foutput4",0,1);

    //2) storing variable foutput5
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"foutput5",0,1);

    //2) storing variable foutput6
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"foutput6",0,1);

    //3) storing variable numInputs
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"numInputs",1,1);

    //3) storing variable numOutputs
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"numOutputs",1,1);

    //3) storing variable AddDense
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"AddDense",1,1);

    //3) storing variable CrossCouple
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"CrossCouple",1,1);

    //3) storing variable activation
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"activation",1,1);
    //increasing wdadr_ptr1 in order to align variable W with alignment requirement of 8
    *wdadr_ptr1 += 1;

    //3) storing variable W
    //----------------
     __bdata = (unsigned char*) malloc(480);
     endianSwapRW((unsigned char *)(&W),120,"DdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,120,"W");
    free(__bdata); //2
    //----------------


    //3) storing variable b
    //----------------
     __bdata = (unsigned char*) malloc(48);
     endianSwapRW((unsigned char *)(&b),12,"DdDdDdDdDdDdDdDdDdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,12,"b");
    free(__bdata); //2
    //----------------


    //3) storing variable Wd
    //----------------
     __bdata = (unsigned char*) malloc(48);
     endianSwapRW((unsigned char *)(&Wd),12,"DdDdDdDdDdDdDdDdDdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,12,"Wd");
    free(__bdata); //2
    //----------------


    //3) storing variable bd
    //----------------
     __bdata = (unsigned char*) malloc(48);
     endianSwapRW((unsigned char *)(&bd),12,"DdDdDdDdDdDdDdDdDdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,12,"bd");
    free(__bdata); //2
    //----------------


    //3) storing variable N
    //----------------
     __bdata = (unsigned char*) malloc(4);
     endianSwapRW((unsigned char *)(&N),1,"i",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,1,"N");
    free(__bdata); //2
    //----------------


    //3) storing variable n
    //----------------
     __bdata = (unsigned char*) malloc(4);
     endianSwapRW((unsigned char *)(&n),1,"i",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,1,"n");
    free(__bdata); //2
    //----------------


    //3) storing variable Y
    //----------------
     __bdata = (unsigned char*) malloc(4);
     endianSwapRW((unsigned char *)(&Y),1,"i",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,1,"Y");
    free(__bdata); //2
    //----------------

    //increasing wdadr_ptr1 in order to align variable dW with alignment requirement of 8
    *wdadr_ptr1 += 1;

    //3) storing variable dW
    //----------------

    //4) storing variable dW: allocating blob of size 8 plus 3 because we need an extra 3 bytes to fill out the");
    //last 'unsigned char' to be a full 'int' in size, so that it sscanf properly with %2x. (otherwise it's nasty!!!)");
    __bdata = (unsigned char*)malloc(8+3);
    for (__loopindex=0; __loopindex<8; __loopindex++)
    {
        __bdata[__loopindex] = 0;
    }
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,2,"dW");
    free(__bdata);  //1

    //3) storing variable lossy2
    //----------------

    //4) storing variable lossy2: allocating blob of size 8 plus 3 because we need an extra 3 bytes to fill out the");
    //last 'unsigned char' to be a full 'int' in size, so that it sscanf properly with %2x. (otherwise it's nasty!!!)");
    __bdata = (unsigned char*)malloc(8+3);
    for (__loopindex=0; __loopindex<8; __loopindex++)
    {
        __bdata[__loopindex] = 0;
    }
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,2,"lossy2");
    free(__bdata);  //1

    //3) storing variable lossy1
    //----------------

    //4) storing variable lossy1: allocating blob of size 8 plus 3 because we need an extra 3 bytes to fill out the");
    //last 'unsigned char' to be a full 'int' in size, so that it sscanf properly with %2x. (otherwise it's nasty!!!)");
    __bdata = (unsigned char*)malloc(8+3);
    for (__loopindex=0; __loopindex<8; __loopindex++)
    {
        __bdata[__loopindex] = 0;
    }
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,2,"lossy1");
    free(__bdata);  //1

    //3) storing variable dLoss_da2
    //----------------

    //4) storing variable dLoss_da2: allocating blob of size 48 plus 3 because we need an extra 3 bytes to fill out the");
    //last 'unsigned char' to be a full 'int' in size, so that it sscanf properly with %2x. (otherwise it's nasty!!!)");
    __bdata = (unsigned char*)malloc(48+3);
    for (__loopindex=0; __loopindex<48; __loopindex++)
    {
        __bdata[__loopindex] = 0;
    }
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,12,"dLoss_da2");
    free(__bdata);  //1

    //3) storing variable k
    //----------------

    //4) storing variable k: allocating blob of size 4 plus 3 because we need an extra 3 bytes to fill out the");
    //last 'unsigned char' to be a full 'int' in size, so that it sscanf properly with %2x. (otherwise it's nasty!!!)");
    __bdata = (unsigned char*)malloc(4+3);
    for (__loopindex=0; __loopindex<4; __loopindex++)
    {
        __bdata[__loopindex] = 0;
    }
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,1,"k");
    free(__bdata);  //1

    //3) storing variable i
    //----------------

    //4) storing variable i: allocating blob of size 4 plus 3 because we need an extra 3 bytes to fill out the");
    //last 'unsigned char' to be a full 'int' in size, so that it sscanf properly with %2x. (otherwise it's nasty!!!)");
    __bdata = (unsigned char*)malloc(4+3);
    for (__loopindex=0; __loopindex<4; __loopindex++)
    {
        __bdata[__loopindex] = 0;
    }
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,1,"i");
    free(__bdata);  //1

    //3) storing variable out2
    //----------------

    //4) storing variable out2: allocating blob of size 8 plus 3 because we need an extra 3 bytes to fill out the");
    //last 'unsigned char' to be a full 'int' in size, so that it sscanf properly with %2x. (otherwise it's nasty!!!)");
    __bdata = (unsigned char*)malloc(8+3);
    for (__loopindex=0; __loopindex<8; __loopindex++)
    {
        __bdata[__loopindex] = 0;
    }
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,2,"out2");
    free(__bdata);  //1

    //3) storing variable out1
    //----------------

    //4) storing variable out1: allocating blob of size 8 plus 3 because we need an extra 3 bytes to fill out the");
    //last 'unsigned char' to be a full 'int' in size, so that it sscanf properly with %2x. (otherwise it's nasty!!!)");
    __bdata = (unsigned char*)malloc(8+3);
    for (__loopindex=0; __loopindex<8; __loopindex++)
    {
        __bdata[__loopindex] = 0;
    }
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,2,"out1");
    free(__bdata);  //1

    //3) storing variable dasig
    //----------------

    //4) storing variable dasig: allocating blob of size 80 plus 3 because we need an extra 3 bytes to fill out the");
    //last 'unsigned char' to be a full 'int' in size, so that it sscanf properly with %2x. (otherwise it's nasty!!!)");
    __bdata = (unsigned char*)malloc(80+3);
    __hexstring = "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    __pos = __hexstring;
    for (__loopindex=0; __loopindex<80; __loopindex++)
    {
        sscanf(__pos,"%2x",&__bdata[__loopindex]);
        __pos += 2;
    }
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,20,"dasig");
    free(__bdata);  //1

    //3) storing variable da
    //----------------

    //4) storing variable da: allocating blob of size 80 plus 3 because we need an extra 3 bytes to fill out the");
    //last 'unsigned char' to be a full 'int' in size, so that it sscanf properly with %2x. (otherwise it's nasty!!!)");
    __bdata = (unsigned char*)malloc(80+3);
    __hexstring = "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    __pos = __hexstring;
    for (__loopindex=0; __loopindex<80; __loopindex++)
    {
        sscanf(__pos,"%2x",&__bdata[__loopindex]);
        __pos += 2;
    }
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,20,"da");
    free(__bdata);  //1

    //3) storing variable loss
    //----------------

    //4) storing variable loss: allocating blob of size 48 plus 3 because we need an extra 3 bytes to fill out the");
    //last 'unsigned char' to be a full 'int' in size, so that it sscanf properly with %2x. (otherwise it's nasty!!!)");
    __bdata = (unsigned char*)malloc(48+3);
    __hexstring = "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    __pos = __hexstring;
    for (__loopindex=0; __loopindex<48; __loopindex++)
    {
        sscanf(__pos,"%2x",&__bdata[__loopindex]);
        __pos += 2;
    }
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,12,"loss");
    free(__bdata);  //1

    //3) storing variable X1
    //----------------

    //4) storing variable X1: allocating blob of size 80 plus 3 because we need an extra 3 bytes to fill out the");
    //last 'unsigned char' to be a full 'int' in size, so that it sscanf properly with %2x. (otherwise it's nasty!!!)");
    __bdata = (unsigned char*)malloc(80+3);
    __hexstring = "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    __pos = __hexstring;
    for (__loopindex=0; __loopindex<80; __loopindex++)
    {
        sscanf(__pos,"%2x",&__bdata[__loopindex]);
        __pos += 2;
    }
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,20,"X1");
    free(__bdata);  //1

    //3) storing variable X
    //----------------

    //4) storing variable X: allocating blob of size 80 plus 3 because we need an extra 3 bytes to fill out the");
    //last 'unsigned char' to be a full 'int' in size, so that it sscanf properly with %2x. (otherwise it's nasty!!!)");
    __bdata = (unsigned char*)malloc(80+3);
    __hexstring = "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    __pos = __hexstring;
    for (__loopindex=0; __loopindex<80; __loopindex++)
    {
        sscanf(__pos,"%2x",&__bdata[__loopindex]);
        __pos += 2;
    }
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,20,"X");
    free(__bdata);  //1

    //3) storing variable Xout
    //----------------

    //4) storing variable Xout: allocating blob of size 48 plus 3 because we need an extra 3 bytes to fill out the");
    //last 'unsigned char' to be a full 'int' in size, so that it sscanf properly with %2x. (otherwise it's nasty!!!)");
    __bdata = (unsigned char*)malloc(48+3);
    __hexstring = "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    __pos = __hexstring;
    for (__loopindex=0; __loopindex<48; __loopindex++)
    {
        sscanf(__pos,"%2x",&__bdata[__loopindex]);
        __pos += 2;
    }
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,12,"Xout");
    free(__bdata);  //1

    //3) storing variable out
    //----------------

    //4) storing variable out: allocating blob of size 48 plus 3 because we need an extra 3 bytes to fill out the");
    //last 'unsigned char' to be a full 'int' in size, so that it sscanf properly with %2x. (otherwise it's nasty!!!)");
    __bdata = (unsigned char*)malloc(48+3);
    __hexstring = "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    __pos = __hexstring;
    for (__loopindex=0; __loopindex<48; __loopindex++)
    {
        sscanf(__pos,"%2x",&__bdata[__loopindex]);
        __pos += 2;
    }
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,12,"out");
    free(__bdata);  //1

    //3) storing variable preOutputa
    //----------------

    //4) storing variable preOutputa: allocating blob of size 48 plus 3 because we need an extra 3 bytes to fill out the");
    //last 'unsigned char' to be a full 'int' in size, so that it sscanf properly with %2x. (otherwise it's nasty!!!)");
    __bdata = (unsigned char*)malloc(48+3);
    __hexstring = "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    __pos = __hexstring;
    for (__loopindex=0; __loopindex<48; __loopindex++)
    {
        sscanf(__pos,"%2x",&__bdata[__loopindex]);
        __pos += 2;
    }
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,12,"preOutputa");
    free(__bdata);  //1

    //3) storing variable preOutput2
    //----------------

    //4) storing variable preOutput2: allocating blob of size 8 plus 3 because we need an extra 3 bytes to fill out the");
    //last 'unsigned char' to be a full 'int' in size, so that it sscanf properly with %2x. (otherwise it's nasty!!!)");
    __bdata = (unsigned char*)malloc(8+3);
    __hexstring = "0000000000000000";
    __pos = __hexstring;
    for (__loopindex=0; __loopindex<8; __loopindex++)
    {
        sscanf(__pos,"%2x",&__bdata[__loopindex]);
        __pos += 2;
    }
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,2,"preOutput2");
    free(__bdata);  //1

    //3) storing variable preOutput
    //----------------

    //4) storing variable preOutput: allocating blob of size 8 plus 3 because we need an extra 3 bytes to fill out the");
    //last 'unsigned char' to be a full 'int' in size, so that it sscanf properly with %2x. (otherwise it's nasty!!!)");
    __bdata = (unsigned char*)malloc(8+3);
    __hexstring = "0000000000000000";
    __pos = __hexstring;
    for (__loopindex=0; __loopindex<8; __loopindex++)
    {
        sscanf(__pos,"%2x",&__bdata[__loopindex]);
        __pos += 2;
    }
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,2,"preOutput");
    free(__bdata);  //1

    //3) storing variable .LC0
    //----------------

    //4) storing variable .LC0: allocating blob of size 8 plus 3 because we need an extra 3 bytes to fill out the");
    //last 'unsigned char' to be a full 'int' in size, so that it sscanf properly with %2x. (otherwise it's nasty!!!)");
    __bdata = (unsigned char*)malloc(8+3);
    __hexstring = "0000000000000000";
    __pos = __hexstring;
    for (__loopindex=0; __loopindex<8; __loopindex++)
    {
        sscanf(__pos,"%2x",&__bdata[__loopindex]);
        __pos += 2;
    }
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,2,".LC0");
    free(__bdata);  //1

    //3) storing variable .LC2
    //----------------

    //4) storing variable .LC2: allocating blob of size 4 plus 3 because we need an extra 3 bytes to fill out the");
    //last 'unsigned char' to be a full 'int' in size, so that it sscanf properly with %2x. (otherwise it's nasty!!!)");
    __bdata = (unsigned char*)malloc(4+3);
    __hexstring = "59800004";
    __pos = __hexstring;
    for (__loopindex=0; __loopindex<4; __loopindex++)
    {
        sscanf(__pos,"%2x",&__bdata[__loopindex]);
        __pos += 2;
    }
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,1,".LC2");
    free(__bdata);  //1

    //3) storing variable .LC4
    //----------------

    //4) storing variable .LC4: allocating blob of size 4 plus 3 because we need an extra 3 bytes to fill out the");
    //last 'unsigned char' to be a full 'int' in size, so that it sscanf properly with %2x. (otherwise it's nasty!!!)");
    __bdata = (unsigned char*)malloc(4+3);
    __hexstring = "3f800000";
    __pos = __hexstring;
    for (__loopindex=0; __loopindex<4; __loopindex++)
    {
        sscanf(__pos,"%2x",&__bdata[__loopindex]);
        __pos += 2;
    }
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,1,".LC4");
    free(__bdata);  //1
    reserveMemoryForFunction_RW(getSubsystemIndex(),"memset.fsig",R_proc1,wdadr_ptr1,3);
    reserveMemoryForFunction_RW(getSubsystemIndex(),"tanh.fsig",R_proc1,wdadr_ptr1,3);
//setting the total size of the memory map to 1904
   freeScratchMemoryPointers();
}
DllExport void OutputLv2TanhDense_RR(void *this_, int R_proc1)
{
    rpcControlStructurePointer = this_;
    int __idata = 0;
    int __inDMCode = 0;
    int __extraData;
    ramPassNumber = 1;
    initializeParameterDataRW(this_);

    loadInstance(this_,R_proc1); //new!

    userSuppliedRamPass1Code(this_,R_proc1);
    saveInstance(this_,R_proc1);   //new!
    freeScratchMemoryPointers();
}
DllExport int OutputLv2TanhDense_getDMSize(void *this_, int R_proc1)
{
    return((1904)/4);
}
DllExport void OutputLv2TanhDense_INIT(void *this_)
{
    rpcControlStructurePointer = this_;
    ramPassNumber = 0;
    initializeParameterDataRW(this_);

    userSuppliedRamPass0Code(this_);
}
DllExport unsigned int OutputLv2TanhDense_getVariableDMOffset(char* variableName)
{
    int returnValue;
    if(strcmp("Learning_rate", variableName) == 0)
        returnValue = 0;
    else if(strcmp("input1", variableName) == 0)
        returnValue = 4;
    else if(strcmp("L1", variableName) == 0)
        returnValue = 8;
    else if(strcmp("lam", variableName) == 0)
        returnValue = 12;
    else if(strcmp("input2", variableName) == 0)
        returnValue = 16;
    else if(strcmp("input3", variableName) == 0)
        returnValue = 20;
    else if(strcmp("input4", variableName) == 0)
        returnValue = 24;
    else if(strcmp("input5", variableName) == 0)
        returnValue = 28;
    else if(strcmp("input6", variableName) == 0)
        returnValue = 32;
    else if(strcmp("input7", variableName) == 0)
        returnValue = 36;
    else if(strcmp("input8", variableName) == 0)
        returnValue = 40;
    else if(strcmp("input9", variableName) == 0)
        returnValue = 44;
    else if(strcmp("input10", variableName) == 0)
        returnValue = 48;
    else if(strcmp("L2", variableName) == 0)
        returnValue = 52;
    else if(strcmp("L3", variableName) == 0)
        returnValue = 56;
    else if(strcmp("L4", variableName) == 0)
        returnValue = 60;
    else if(strcmp("L5", variableName) == 0)
        returnValue = 64;
    else if(strcmp("L6", variableName) == 0)
        returnValue = 68;
    else if(strcmp("foutput", variableName) == 0)
        returnValue = 72;
    else if(strcmp("Li1", variableName) == 0)
        returnValue = 76;
    else if(strcmp("Li2", variableName) == 0)
        returnValue = 80;
    else if(strcmp("Li3", variableName) == 0)
        returnValue = 84;
    else if(strcmp("Li4", variableName) == 0)
        returnValue = 88;
    else if(strcmp("Li5", variableName) == 0)
        returnValue = 92;
    else if(strcmp("Li6", variableName) == 0)
        returnValue = 96;
    else if(strcmp("Li7", variableName) == 0)
        returnValue = 100;
    else if(strcmp("Li8", variableName) == 0)
        returnValue = 104;
    else if(strcmp("Li9", variableName) == 0)
        returnValue = 108;
    else if(strcmp("Li10", variableName) == 0)
        returnValue = 112;
    else if(strcmp("foutput2", variableName) == 0)
        returnValue = 116;
    else if(strcmp("foutput3", variableName) == 0)
        returnValue = 120;
    else if(strcmp("foutput4", variableName) == 0)
        returnValue = 124;
    else if(strcmp("foutput5", variableName) == 0)
        returnValue = 128;
    else if(strcmp("foutput6", variableName) == 0)
        returnValue = 132;
    else if(strcmp("numInputs", variableName) == 0)
        returnValue = 136;
    else if(strcmp("numOutputs", variableName) == 0)
        returnValue = 140;
    else if(strcmp("AddDense", variableName) == 0)
        returnValue = 144;
    else if(strcmp("CrossCouple", variableName) == 0)
        returnValue = 148;
    else if(strcmp("activation", variableName) == 0)
        returnValue = 152;
    else if(strcmp("W", variableName) == 0)
        returnValue = 160;
    else if(strcmp("b", variableName) == 0)
        returnValue = 640;
    else if(strcmp("Wd", variableName) == 0)
        returnValue = 688;
    else if(strcmp("bd", variableName) == 0)
        returnValue = 736;
    else if(strcmp("N", variableName) == 0)
        returnValue = 784;
    else if(strcmp("n", variableName) == 0)
        returnValue = 788;
    else if(strcmp("Y", variableName) == 0)
        returnValue = 792;
    else if(strcmp("dW", variableName) == 0)
        returnValue = 800;
    else if(strcmp("lossy2", variableName) == 0)
        returnValue = 808;
    else if(strcmp("lossy1", variableName) == 0)
        returnValue = 816;
    else if(strcmp("dLoss_da2", variableName) == 0)
        returnValue = 824;
    else if(strcmp("k", variableName) == 0)
        returnValue = 872;
    else if(strcmp("i", variableName) == 0)
        returnValue = 876;
    else if(strcmp("out2", variableName) == 0)
        returnValue = 880;
    else if(strcmp("out1", variableName) == 0)
        returnValue = 888;
    else if(strcmp("dasig", variableName) == 0)
        returnValue = 896;
    else if(strcmp("da", variableName) == 0)
        returnValue = 976;
    else if(strcmp("loss", variableName) == 0)
        returnValue = 1056;
    else if(strcmp("X1", variableName) == 0)
        returnValue = 1104;
    else if(strcmp("X", variableName) == 0)
        returnValue = 1184;
    else if(strcmp("Xout", variableName) == 0)
        returnValue = 1264;
    else if(strcmp("out", variableName) == 0)
        returnValue = 1312;
    else if(strcmp("preOutputa", variableName) == 0)
        returnValue = 1360;
    else if(strcmp("preOutput2", variableName) == 0)
        returnValue = 1408;
    else if(strcmp("preOutput", variableName) == 0)
        returnValue = 1416;
    else if(strcmp(".LC0", variableName) == 0)
        returnValue = 1424;
    else if(strcmp(".LC2", variableName) == 0)
        returnValue = 1432;
    else if(strcmp(".LC4", variableName) == 0)
        returnValue = 1436;
    else 
        returnValue = 0xFFFFFFFF;  // Signal that the variable was not found.
    return returnValue;
}
