/* DO NOT EDIT THIS FILE */

MODEL_TYPE: CTL

#define PI        3.1415926535897932384626433832795   // definition of PI                 
#define TWOPI     6.283185307179586476925286766559    // definition of 2.0*PI             
#define E         2.71828182845904523536028747135266  // definition of E                  
#define EINV      0.36787944117144232159552377016147  // definition of E Inverse (1/E)    
#define RT2       1.4142135623730950488016887242097   // definition of square root 2.0    
#define RT3       1.7320508075688772935274463415059   // definition of square root 3.0    
#define INV_ROOT2 0.70710678118654752440084436210485                                      

INPUTS:
  double Learning_rate;
  double lamm;
  double x1;
  double x2;
  double x3;
  double x4;
  double x5;
  double x6;
  double x7;
  double x8;
  double x9;
  double x10;
  double L1;
  double L2;
  double L3;
  double L4;
  double L5;
  double L6;
  double L7;
  double L8;
  double L9;
  double L10;

OUTPUTS:
  double foutput;
  double foutput2;
  double foutput3;
  double foutput4;
  double foutput5;
  double foutput6;
  double foutput7;
  double foutput8;
  double foutput9;
  double foutput10;
  double tests;

PARAMETERS:
  int numInputs;   //Description
  int numOutputs;  //Description
  int Layers;      //Description
  int batch_size;  //Description
  int activation1; //Description
  int Nodes1;      //Description
  int activation2; //Description
  int Nodes2;      //Description
  int activation3; //Description
  int Nodes3;      //Description

