#include <stdio.h>
#include <string.h>

#include <cbuilder_ctrl_commonRW.h>

#include <math.h>

static char* checkSumC_ANN_Final_2af4727f2437fdd4b357c875800dbd87;
extern void* rpcControlStructurePointer;
extern FILE* mapFile;


// now here are the lines from the GLOBAL section, typically #defines... 
// ======================================================================
// Include file below is generated by C-Builder      

// and contains the variables declared as -          

// PARAMETERS, INPUTS, OUTPUTS . . .                 

#define PI        3.1415926535897932384626433832795   // definition of PI                 

#define TWOPI     6.283185307179586476925286766559    // definition of 2.0*PI             

#define E         2.71828182845904523536028747135266  // definition of E                  

#define EINV      0.36787944117144232159552377016147  // definition of E Inverse (1/E)    

#define RT2       1.4142135623730950488016887242097   // definition of square root 2.0    

#define RT3       1.7320508075688772935274463415059   // definition of square root 3.0    

#define INV_ROOT2 0.70710678118654752440084436210485                                      

// finished the GLOBAL section (#defines)
// ======================================


// now here are the static variables the user has defined... 
//===========================================================
static double testout;

// -----------------------------------------------   

// Variables declared here may be used in both the   

// RAM: and CODE: sections below.                    

// -----------------------------------------------   

//    double dt;    

static double W1[18] =  { 0.107636325, 0.067938805, 0.14532101, -0.22826472, 0.039204452, 1.2104177, -0.2996164, 0.8820697, -0.63229483, -0.030488968, 0.5512029, 0.07976646, 0.22130048, -0.4609804, 0.2206365, 0.9901441, -0.30606145, -0.6965658 };

static double b1[3] = { 0.023580035, 0.0058132247, 0.021381315 };





static double W2[9] =  { -0.21735963, -0.95582664, -1.2001845, 0.64842796, 0.43467012, -0.79226154, 0.35005328, -0.6938111, -0.9446461 };



static double b2[3] = { 0.0060735303, 0.02123643, -0.0040892987 };





static double W3[9] =  { -0.5647482, 0.513669, 1.2727365, -1.1156123, -0.9551774, -0.8200697, 0.4101158, -0.32294378, 0.9075196 };



static double b3[3] = { -0.008884262, -0.022166247, 0.040670604 };







//double W2[100] = {0.0};

//double b2[10] = {0.0};



//double W3[100] = {0.0};

//double b3[10] = {0.0};





static double Wdense[9] = {1.0, 0.0, 0.0,
0.0, 1.0, 0.0,
0.0, 0.0, 1.0};

static double bdense[3] = {0.0, 0.0, 0.0};





static int N;

//int n;

static int Y;



static int N1;

static int N2;

static int N3;



static double X[10] = {0.0}; //Array to host inputs

static double y[10] = {0.0}; 



static double a1[10]; // layer 1 output array

static double a2[10]; // layer 2 output array

static double a3[10]; // layer 3 output array





static double dummyloss[10] = {0.0};

static double a1Loss[10] = {0.0};

static double a2Loss[10] = {0.0};

static double a3Loss[10] = {0.0};





static double loss[10] = {0.0}; // Array to host the loss function of //each output



static int i;

static int k;

static int indx;

static int j;



static double L;



static double Lr;

static int Ndense;

// - E n d   o f   S T A T I C :   S e c t i o n -   



// end the user defined STATIC declarations ... 
//===========================================================

// declare the Parameters so that the user's code can reference them
// =================================================================
static   int numInputs;   //Description

static   int numOutputs;  //Description

static   int Layers;      //Description

static   int batch_size;  //Description

static   int activation1; //Description

static   int Nodes1;      //Description

static   int activation2; //Description

static   int Nodes2;      //Description

static   int activation3; //Description

static   int Nodes3;      //Description


// end Parameter declarations 
// ========================== 


static void initializeParameterDataRW(void *this_)
{
    // initialize the Parameter values so that the user's code can reference them*/
    // ===========================================================================
    numInputs = getIntParameter(this_,"numInputs");
    numOutputs = getIntParameter(this_,"numOutputs");
    Layers = getIntParameter(this_,"Layers");
    batch_size = getIntParameter(this_,"batch_size");
    activation1 = getIntParameter(this_,"activation1");
    Nodes1 = getIntParameter(this_,"Nodes1");
    activation2 = getIntParameter(this_,"activation2");
    Nodes2 = getIntParameter(this_,"Nodes2");
    activation3 = getIntParameter(this_,"activation3");
    Nodes3 = getIntParameter(this_,"Nodes3");

    // end initializing Parameters 
    // =========================== 

}


static void saveInstance (void *this_, int R_proc1);

static void loadInstance (void *this_, int R_proc1);

/* copy the lines of code from the RAM_FUNCTIONS section */


// -----------------------------------------------   

// This section should contain any 'c' functions     

// to be called from the RAM section (either         

// RAM_PASS1 or RAM_PASS2). Example:                 

//                                                   

// static double myFunction(double v1, double v2)    

// {                                                 

//     return(v1*v2);                                

// }                                                 

// -----------------------------------------------   




static void initializeLocalDataRW(void *this_, int R_proc1)
{
    // initialize the local data based on a special section in the user's c code
    // ===========================================================================
    rpcControlStructurePointer = this_;

    // end initializing local data 
    // =========================== 

}


static void userSuppliedRamPass0Code(void* this_)
{
    rpcControlStructurePointer = this_;

    // copy the lines of code from the RAM_PASS0 section 
}

static void userSuppliedRamPass1Code(void* this_, int R_proc1)
{
    rpcControlStructurePointer = this_;
    void* comp = this_; //for psys component calls that used 'comp'

    // declare the variables the user has supplied in the RAM_DECLARATIONS section 

    // copy the lines of code from the RAM_PASS1 section 
}
static void* mallocInstancePointer (void *this_, int R_proc1)
{
  //  FILE *debugFile;
  //  debugFile = fopen("C:\\RTDS_USER\\testdebug.txt","a");
  //  fprintf(debugFile,"dbgcmb - entering mallocInstancePointer function for component ANN_Final R_proc1 = %i \n",R_proc1);
  //  fclose(debugFile);

    rpcControlStructurePointer = this_;
    void* staticInstancePointer = NULL; 
    int sizeOfStaticSection = 1324;
    int sizeOfLocalStaticSection = 0;
    staticInstancePointer = (void*)malloc(sizeOfStaticSection+sizeOfLocalStaticSection);
    return(staticInstancePointer);
}


static void saveInstance (void *this_, int R_proc1)
{
    rpcControlStructurePointer = this_;
    unsigned char* staticVariablesInstancePtr = getLocalStaticInstancePointer_RW(this_);
   // unsigned char* staticVariablesInstancePtr = NULL;
    if (staticVariablesInstancePtr == NULL)
    {
        staticVariablesInstancePtr = mallocInstancePointer (this_,R_proc1);
        setLocalStaticInstancePointer_RW(this_,staticVariablesInstancePtr);
    }

    unsigned char* tempPtr = staticVariablesInstancePtr;
    int index = 0;
    memcpy(tempPtr, (unsigned char*)&testout,sizeof(testout));
    tempPtr += sizeof(testout);
    memcpy(tempPtr, (unsigned char*)&W1,sizeof(W1));
    tempPtr += sizeof(W1);
    memcpy(tempPtr, (unsigned char*)&b1,sizeof(b1));
    tempPtr += sizeof(b1);
    memcpy(tempPtr, (unsigned char*)&W2,sizeof(W2));
    tempPtr += sizeof(W2);
    memcpy(tempPtr, (unsigned char*)&b2,sizeof(b2));
    tempPtr += sizeof(b2);
    memcpy(tempPtr, (unsigned char*)&W3,sizeof(W3));
    tempPtr += sizeof(W3);
    memcpy(tempPtr, (unsigned char*)&b3,sizeof(b3));
    tempPtr += sizeof(b3);
    memcpy(tempPtr, (unsigned char*)&Wdense,sizeof(Wdense));
    tempPtr += sizeof(Wdense);
    memcpy(tempPtr, (unsigned char*)&bdense,sizeof(bdense));
    tempPtr += sizeof(bdense);
    memcpy(tempPtr, (unsigned char*)&N,sizeof(N));
    tempPtr += sizeof(N);
    memcpy(tempPtr, (unsigned char*)&Y,sizeof(Y));
    tempPtr += sizeof(Y);
    memcpy(tempPtr, (unsigned char*)&N1,sizeof(N1));
    tempPtr += sizeof(N1);
    memcpy(tempPtr, (unsigned char*)&N2,sizeof(N2));
    tempPtr += sizeof(N2);
    memcpy(tempPtr, (unsigned char*)&N3,sizeof(N3));
    tempPtr += sizeof(N3);
    memcpy(tempPtr, (unsigned char*)&X,sizeof(X));
    tempPtr += sizeof(X);
    memcpy(tempPtr, (unsigned char*)&y,sizeof(y));
    tempPtr += sizeof(y);
    memcpy(tempPtr, (unsigned char*)&a1,sizeof(a1));
    tempPtr += sizeof(a1);
    memcpy(tempPtr, (unsigned char*)&a2,sizeof(a2));
    tempPtr += sizeof(a2);
    memcpy(tempPtr, (unsigned char*)&a3,sizeof(a3));
    tempPtr += sizeof(a3);
    memcpy(tempPtr, (unsigned char*)&dummyloss,sizeof(dummyloss));
    tempPtr += sizeof(dummyloss);
    memcpy(tempPtr, (unsigned char*)&a1Loss,sizeof(a1Loss));
    tempPtr += sizeof(a1Loss);
    memcpy(tempPtr, (unsigned char*)&a2Loss,sizeof(a2Loss));
    tempPtr += sizeof(a2Loss);
    memcpy(tempPtr, (unsigned char*)&a3Loss,sizeof(a3Loss));
    tempPtr += sizeof(a3Loss);
    memcpy(tempPtr, (unsigned char*)&loss,sizeof(loss));
    tempPtr += sizeof(loss);
    memcpy(tempPtr, (unsigned char*)&i,sizeof(i));
    tempPtr += sizeof(i);
    memcpy(tempPtr, (unsigned char*)&k,sizeof(k));
    tempPtr += sizeof(k);
    memcpy(tempPtr, (unsigned char*)&indx,sizeof(indx));
    tempPtr += sizeof(indx);
    memcpy(tempPtr, (unsigned char*)&j,sizeof(j));
    tempPtr += sizeof(j);
    memcpy(tempPtr, (unsigned char*)&L,sizeof(L));
    tempPtr += sizeof(L);
    memcpy(tempPtr, (unsigned char*)&Lr,sizeof(Lr));
    tempPtr += sizeof(Lr);
    memcpy(tempPtr, (unsigned char*)&Ndense,sizeof(Ndense));
    tempPtr += sizeof(Ndense);
}

static void loadInstance (void *this_, int R_proc1)
{
    rpcControlStructurePointer = this_;
    unsigned char* staticVariablesInstancePtr = getLocalStaticInstancePointer_RW(this_);
    unsigned char* tempPtr = staticVariablesInstancePtr;
    int index = 0;
    if (staticVariablesInstancePtr == NULL)
        return;
    memcpy((unsigned char*)&testout, tempPtr, sizeof(testout));
    tempPtr += sizeof(testout);
    memcpy((unsigned char*)&W1, tempPtr, sizeof(W1));
    tempPtr += sizeof(W1);
    memcpy((unsigned char*)&b1, tempPtr, sizeof(b1));
    tempPtr += sizeof(b1);
    memcpy((unsigned char*)&W2, tempPtr, sizeof(W2));
    tempPtr += sizeof(W2);
    memcpy((unsigned char*)&b2, tempPtr, sizeof(b2));
    tempPtr += sizeof(b2);
    memcpy((unsigned char*)&W3, tempPtr, sizeof(W3));
    tempPtr += sizeof(W3);
    memcpy((unsigned char*)&b3, tempPtr, sizeof(b3));
    tempPtr += sizeof(b3);
    memcpy((unsigned char*)&Wdense, tempPtr, sizeof(Wdense));
    tempPtr += sizeof(Wdense);
    memcpy((unsigned char*)&bdense, tempPtr, sizeof(bdense));
    tempPtr += sizeof(bdense);
    memcpy((unsigned char*)&N, tempPtr, sizeof(N));
    tempPtr += sizeof(N);
    memcpy((unsigned char*)&Y, tempPtr, sizeof(Y));
    tempPtr += sizeof(Y);
    memcpy((unsigned char*)&N1, tempPtr, sizeof(N1));
    tempPtr += sizeof(N1);
    memcpy((unsigned char*)&N2, tempPtr, sizeof(N2));
    tempPtr += sizeof(N2);
    memcpy((unsigned char*)&N3, tempPtr, sizeof(N3));
    tempPtr += sizeof(N3);
    memcpy((unsigned char*)&X, tempPtr, sizeof(X));
    tempPtr += sizeof(X);
    memcpy((unsigned char*)&y, tempPtr, sizeof(y));
    tempPtr += sizeof(y);
    memcpy((unsigned char*)&a1, tempPtr, sizeof(a1));
    tempPtr += sizeof(a1);
    memcpy((unsigned char*)&a2, tempPtr, sizeof(a2));
    tempPtr += sizeof(a2);
    memcpy((unsigned char*)&a3, tempPtr, sizeof(a3));
    tempPtr += sizeof(a3);
    memcpy((unsigned char*)&dummyloss, tempPtr, sizeof(dummyloss));
    tempPtr += sizeof(dummyloss);
    memcpy((unsigned char*)&a1Loss, tempPtr, sizeof(a1Loss));
    tempPtr += sizeof(a1Loss);
    memcpy((unsigned char*)&a2Loss, tempPtr, sizeof(a2Loss));
    tempPtr += sizeof(a2Loss);
    memcpy((unsigned char*)&a3Loss, tempPtr, sizeof(a3Loss));
    tempPtr += sizeof(a3Loss);
    memcpy((unsigned char*)&loss, tempPtr, sizeof(loss));
    tempPtr += sizeof(loss);
    memcpy((unsigned char*)&i, tempPtr, sizeof(i));
    tempPtr += sizeof(i);
    memcpy((unsigned char*)&k, tempPtr, sizeof(k));
    tempPtr += sizeof(k);
    memcpy((unsigned char*)&indx, tempPtr, sizeof(indx));
    tempPtr += sizeof(indx);
    memcpy((unsigned char*)&j, tempPtr, sizeof(j));
    tempPtr += sizeof(j);
    memcpy((unsigned char*)&L, tempPtr, sizeof(L));
    tempPtr += sizeof(L);
    memcpy((unsigned char*)&Lr, tempPtr, sizeof(Lr));
    tempPtr += sizeof(Lr);
    memcpy((unsigned char*)&Ndense, tempPtr, sizeof(Ndense));
    tempPtr += sizeof(Ndense);
}

DllExport int ANN_Final_GET_NUM_NAMED_INPUTS(void *this_)
{
    //This comes from CmodelCompiler.createCtlExtraIOCode
    //int cntl_idx;
    int numNamedInputs = 0;
    //rpcControlStructurePointer = this_;
    //cntl_idx = 0;
    numNamedInputs = 0;
    return(numNamedInputs);
}
DllExport int ANN_Final_GET_NUM_NAMED_OUTPUTS(void *this_)
{
    //This comes from CmodelCompiler.createCtlExtraIOCode
    //int cntl_idx;
    //rpcControlStructurePointer = this_;
    int numNamedOutputs = 0;
    //cntl_idx = 0;
    numNamedOutputs = 0;
    //this code from CmodelCompiler.createCtlExtraIOCode
    return(numNamedOutputs);
}
DllExport int ANN_Final_ADD_EXTRA_IO(void *this_, int R_proc1)
{
    //This comes from CmodelCompiler.createCtlExtraIOCode
    int cntl_idx;
    rpcControlStructurePointer = this_;
    initializeParameterDataRW(this_);

    initializeLocalDataRW(this_, R_proc1);

    saveInstance(this_,R_proc1);  //new!
}
DllExport int ANN_Final_GET_FLAG_PARTICIPATION(void *this_)
{
    //This comes from CmodelCompiler.createFlagParticipationCode
    int flags;
    flags = 0;
    flags = flags | 0x04;
    return(flags);
}

static void userSuppliedRamCode(int R_proc1)
{
   ramPassNumber = 2;


    /***** declare the variables the user has supplied in the RAM_DECLARATIONS section */

    /* copy the lines of code from the RAM section */
//n = numInputs + numOutputs;

N = numInputs;

Y = numOutputs;

N1 = Nodes1;

N2 = Nodes2;

N3 = Nodes3;

if (Layers == 1){

Ndense = N1;

}

else if (Layers == 2){

Ndense = N2;
}

else{
Ndense = N3;
}

// -----------------------------------------------   

// Place C code here which computes constants        

// required for the CODE: section below.  The C      

// code here is executed once, prior to the start    

// of the simulation case.                           

// -----------------------------------------------   

//    dt= getTimeStep();                             

// ------------- End of RAM: Section -------------   

}
DllExport void ANN_Final_DM_RW (void *this_, int R_proc1,  int *wdadr_ptr1)
{
    rpcControlStructurePointer = this_;
    loadInstance(this_, R_proc1);  //new!
    initializeParameterDataRW(this_);
 //   initializeLocalDataRW(this_, R_proc1);    //<<<<<<<<<<<<<< TO-DO, change to this!
    int __inDMCode = 1;
    ramPassNumber = 1;
    FILE* signatureFile;
    //re-execute the Ram Pass1 code. This is necessary because
    //if more than one instance of a particular model is used in 
    //a case, all instances will share the same static variables.
    //This means the variables will have to be re-calculated before 
    //they are written out to data memory.

    //userSuppliedRamPass1Code(this_,R_proc1);  //<<<<<<<<<<<<<< TO-DO, change to this!
    //now call the Ram Pass2 code 

    ramPassNumber = 2;
    userSuppliedRamCode(R_proc1);
    double         __fdata=0;
    int            __idata=0;
    unsigned char *__bdata;
    char          *__pattern;
    int            __loopindex=0;
    char           __cdata[12]; //this is sized to match the Cdta entry in rt_ctl_data_t structure in rtdspc
    unsigned char* __blob;
    char*          __blob2;
    char          *__hexstring;
    char          *__pos;


    //1) storing variable Learning_rate
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"Learning_rate",1,1);

    //1) storing variable lamm
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"lamm",1,1);

    //1) storing variable x1
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"x1",1,1);

    //1) storing variable x2
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"x2",1,1);

    //1) storing variable x3
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"x3",1,1);

    //1) storing variable x4
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"x4",1,1);

    //1) storing variable x5
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"x5",1,1);

    //1) storing variable x6
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"x6",1,1);

    //1) storing variable x7
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"x7",1,1);

    //1) storing variable x8
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"x8",1,1);

    //1) storing variable x9
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"x9",1,1);

    //1) storing variable x10
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"x10",1,1);

    //1) storing variable L1
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"L1",1,1);

    //1) storing variable L2
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"L2",1,1);

    //1) storing variable L3
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"L3",1,1);

    //1) storing variable L4
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"L4",1,1);

    //1) storing variable L5
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"L5",1,1);

    //1) storing variable L6
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"L6",1,1);

    //1) storing variable L7
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"L7",1,1);

    //1) storing variable L8
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"L8",1,1);

    //1) storing variable L9
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"L9",1,1);

    //1) storing variable L10
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"L10",1,1);

    //2) storing variable foutput
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"foutput",0,1);

    //2) storing variable foutput2
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"foutput2",0,1);

    //2) storing variable foutput3
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"foutput3",0,1);

    //2) storing variable foutput4
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"foutput4",0,1);

    //2) storing variable foutput5
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"foutput5",0,1);

    //2) storing variable foutput6
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"foutput6",0,1);

    //2) storing variable foutput7
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"foutput7",0,1);

    //2) storing variable foutput8
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"foutput8",0,1);

    //2) storing variable foutput9
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"foutput9",0,1);

    //2) storing variable foutput10
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"foutput10",0,1);

    //2) storing variable tests
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"tests",0,1);

    //3) storing variable numInputs
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"numInputs",1,1);

    //3) storing variable numOutputs
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"numOutputs",1,1);

    //3) storing variable Layers
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"Layers",1,1);

    //3) storing variable batch_size
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"batch_size",1,1);

    //3) storing variable activation1
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"activation1",1,1);

    //3) storing variable Nodes1
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"Nodes1",1,1);

    //3) storing variable activation2
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"activation2",1,1);

    //3) storing variable Nodes2
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"Nodes2",1,1);

    //3) storing variable activation3
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"activation3",1,1);

    //3) storing variable Nodes3
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"Nodes3",1,1);
    //increasing wdadr_ptr1 in order to align variable testout with alignment requirement of 8
    *wdadr_ptr1 += 1;

    //3) storing variable testout
    //----------------
     __bdata = (unsigned char*) malloc(8);
     endianSwapRW((unsigned char *)(&testout),2,"Dd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,2,"testout");
    free(__bdata); //2
    //----------------


    //3) storing variable W1
    //----------------
     __bdata = (unsigned char*) malloc(144);
     endianSwapRW((unsigned char *)(&W1),36,"DdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,36,"W1");
    free(__bdata); //2
    //----------------


    //3) storing variable b1
    //----------------
     __bdata = (unsigned char*) malloc(24);
     endianSwapRW((unsigned char *)(&b1),6,"DdDdDdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,6,"b1");
    free(__bdata); //2
    //----------------


    //3) storing variable W2
    //----------------
     __bdata = (unsigned char*) malloc(72);
     endianSwapRW((unsigned char *)(&W2),18,"DdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,18,"W2");
    free(__bdata); //2
    //----------------


    //3) storing variable b2
    //----------------
     __bdata = (unsigned char*) malloc(24);
     endianSwapRW((unsigned char *)(&b2),6,"DdDdDdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,6,"b2");
    free(__bdata); //2
    //----------------


    //3) storing variable W3
    //----------------
     __bdata = (unsigned char*) malloc(72);
     endianSwapRW((unsigned char *)(&W3),18,"DdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,18,"W3");
    free(__bdata); //2
    //----------------


    //3) storing variable b3
    //----------------
     __bdata = (unsigned char*) malloc(24);
     endianSwapRW((unsigned char *)(&b3),6,"DdDdDdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,6,"b3");
    free(__bdata); //2
    //----------------


    //3) storing variable Wdense
    //----------------
     __bdata = (unsigned char*) malloc(72);
     endianSwapRW((unsigned char *)(&Wdense),18,"DdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,18,"Wdense");
    free(__bdata); //2
    //----------------


    //3) storing variable bdense
    //----------------
     __bdata = (unsigned char*) malloc(24);
     endianSwapRW((unsigned char *)(&bdense),6,"DdDdDdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,6,"bdense");
    free(__bdata); //2
    //----------------


    //3) storing variable N
    //----------------
     __bdata = (unsigned char*) malloc(4);
     endianSwapRW((unsigned char *)(&N),1,"i",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,1,"N");
    free(__bdata); //2
    //----------------


    //3) storing variable Y
    //----------------
     __bdata = (unsigned char*) malloc(4);
     endianSwapRW((unsigned char *)(&Y),1,"i",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,1,"Y");
    free(__bdata); //2
    //----------------


    //3) storing variable N1
    //----------------
     __bdata = (unsigned char*) malloc(4);
     endianSwapRW((unsigned char *)(&N1),1,"i",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,1,"N1");
    free(__bdata); //2
    //----------------


    //3) storing variable N2
    //----------------
     __bdata = (unsigned char*) malloc(4);
     endianSwapRW((unsigned char *)(&N2),1,"i",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,1,"N2");
    free(__bdata); //2
    //----------------


    //3) storing variable N3
    //----------------
     __bdata = (unsigned char*) malloc(4);
     endianSwapRW((unsigned char *)(&N3),1,"i",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,1,"N3");
    free(__bdata); //2
    //----------------

    //increasing wdadr_ptr1 in order to align variable X with alignment requirement of 8
    *wdadr_ptr1 += 1;

    //3) storing variable X
    //----------------
     __bdata = (unsigned char*) malloc(80);
     endianSwapRW((unsigned char *)(&X),20,"DdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,20,"X");
    free(__bdata); //2
    //----------------


    //3) storing variable y
    //----------------
     __bdata = (unsigned char*) malloc(80);
     endianSwapRW((unsigned char *)(&y),20,"DdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,20,"y");
    free(__bdata); //2
    //----------------


    //3) storing variable a1
    //----------------
     __bdata = (unsigned char*) malloc(80);
     endianSwapRW((unsigned char *)(&a1),20,"DdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,20,"a1");
    free(__bdata); //2
    //----------------


    //3) storing variable a2
    //----------------
     __bdata = (unsigned char*) malloc(80);
     endianSwapRW((unsigned char *)(&a2),20,"DdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,20,"a2");
    free(__bdata); //2
    //----------------


    //3) storing variable a3
    //----------------
     __bdata = (unsigned char*) malloc(80);
     endianSwapRW((unsigned char *)(&a3),20,"DdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,20,"a3");
    free(__bdata); //2
    //----------------


    //3) storing variable dummyloss
    //----------------
     __bdata = (unsigned char*) malloc(80);
     endianSwapRW((unsigned char *)(&dummyloss),20,"DdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,20,"dummyloss");
    free(__bdata); //2
    //----------------


    //3) storing variable a1Loss
    //----------------
     __bdata = (unsigned char*) malloc(80);
     endianSwapRW((unsigned char *)(&a1Loss),20,"DdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,20,"a1Loss");
    free(__bdata); //2
    //----------------


    //3) storing variable a2Loss
    //----------------
     __bdata = (unsigned char*) malloc(80);
     endianSwapRW((unsigned char *)(&a2Loss),20,"DdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,20,"a2Loss");
    free(__bdata); //2
    //----------------


    //3) storing variable a3Loss
    //----------------
     __bdata = (unsigned char*) malloc(80);
     endianSwapRW((unsigned char *)(&a3Loss),20,"DdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,20,"a3Loss");
    free(__bdata); //2
    //----------------


    //3) storing variable loss
    //----------------
     __bdata = (unsigned char*) malloc(80);
     endianSwapRW((unsigned char *)(&loss),20,"DdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,20,"loss");
    free(__bdata); //2
    //----------------


    //3) storing variable i
    //----------------
     __bdata = (unsigned char*) malloc(4);
     endianSwapRW((unsigned char *)(&i),1,"i",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,1,"i");
    free(__bdata); //2
    //----------------


    //3) storing variable k
    //----------------
     __bdata = (unsigned char*) malloc(4);
     endianSwapRW((unsigned char *)(&k),1,"i",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,1,"k");
    free(__bdata); //2
    //----------------


    //3) storing variable indx
    //----------------
     __bdata = (unsigned char*) malloc(4);
     endianSwapRW((unsigned char *)(&indx),1,"i",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,1,"indx");
    free(__bdata); //2
    //----------------


    //3) storing variable j
    //----------------
     __bdata = (unsigned char*) malloc(4);
     endianSwapRW((unsigned char *)(&j),1,"i",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,1,"j");
    free(__bdata); //2
    //----------------


    //3) storing variable L
    //----------------
     __bdata = (unsigned char*) malloc(8);
     endianSwapRW((unsigned char *)(&L),2,"Dd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,2,"L");
    free(__bdata); //2
    //----------------


    //3) storing variable Lr
    //----------------
     __bdata = (unsigned char*) malloc(8);
     endianSwapRW((unsigned char *)(&Lr),2,"Dd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,2,"Lr");
    free(__bdata); //2
    //----------------


    //3) storing variable Ndense
    //----------------
     __bdata = (unsigned char*) malloc(4);
     endianSwapRW((unsigned char *)(&Ndense),1,"i",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,1,"Ndense");
    free(__bdata); //2
    //----------------

    //increasing wdadr_ptr1 in order to align variable .LC0 with alignment requirement of 8
    *wdadr_ptr1 += 1;

    //3) storing variable .LC0
    //----------------

    //4) storing variable .LC0: allocating blob of size 8 plus 3 because we need an extra 3 bytes to fill out the");
    //last 'unsigned char' to be a full 'int' in size, so that it sscanf properly with %2x. (otherwise it's nasty!!!)");
    __bdata = (unsigned char*)malloc(8+3);
    __hexstring = "0000000000000000";
    __pos = __hexstring;
    for (__loopindex=0; __loopindex<8; __loopindex++)
    {
        sscanf(__pos,"%2x",&__bdata[__loopindex]);
        __pos += 2;
    }
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,2,".LC0");
    free(__bdata);  //1
//setting the total size of the memory map to 1512
   freeScratchMemoryPointers();
}
DllExport void ANN_Final_RR(void *this_, int R_proc1)
{
    rpcControlStructurePointer = this_;
    int __idata = 0;
    int __inDMCode = 0;
    int __extraData;
    ramPassNumber = 1;
    initializeParameterDataRW(this_);

    loadInstance(this_,R_proc1); //new!

    userSuppliedRamPass1Code(this_,R_proc1);
    saveInstance(this_,R_proc1);   //new!
    freeScratchMemoryPointers();
}
DllExport int ANN_Final_getDMSize(void *this_, int R_proc1)
{
    return((1512)/4);
}
DllExport void ANN_Final_INIT(void *this_)
{
    rpcControlStructurePointer = this_;
    ramPassNumber = 0;
    initializeParameterDataRW(this_);

    userSuppliedRamPass0Code(this_);
}
DllExport unsigned int ANN_Final_getVariableDMOffset(char* variableName)
{
    int returnValue;
    if(strcmp("Learning_rate", variableName) == 0)
        returnValue = 0;
    else if(strcmp("lamm", variableName) == 0)
        returnValue = 4;
    else if(strcmp("x1", variableName) == 0)
        returnValue = 8;
    else if(strcmp("x2", variableName) == 0)
        returnValue = 12;
    else if(strcmp("x3", variableName) == 0)
        returnValue = 16;
    else if(strcmp("x4", variableName) == 0)
        returnValue = 20;
    else if(strcmp("x5", variableName) == 0)
        returnValue = 24;
    else if(strcmp("x6", variableName) == 0)
        returnValue = 28;
    else if(strcmp("x7", variableName) == 0)
        returnValue = 32;
    else if(strcmp("x8", variableName) == 0)
        returnValue = 36;
    else if(strcmp("x9", variableName) == 0)
        returnValue = 40;
    else if(strcmp("x10", variableName) == 0)
        returnValue = 44;
    else if(strcmp("L1", variableName) == 0)
        returnValue = 48;
    else if(strcmp("L2", variableName) == 0)
        returnValue = 52;
    else if(strcmp("L3", variableName) == 0)
        returnValue = 56;
    else if(strcmp("L4", variableName) == 0)
        returnValue = 60;
    else if(strcmp("L5", variableName) == 0)
        returnValue = 64;
    else if(strcmp("L6", variableName) == 0)
        returnValue = 68;
    else if(strcmp("L7", variableName) == 0)
        returnValue = 72;
    else if(strcmp("L8", variableName) == 0)
        returnValue = 76;
    else if(strcmp("L9", variableName) == 0)
        returnValue = 80;
    else if(strcmp("L10", variableName) == 0)
        returnValue = 84;
    else if(strcmp("foutput", variableName) == 0)
        returnValue = 88;
    else if(strcmp("foutput2", variableName) == 0)
        returnValue = 92;
    else if(strcmp("foutput3", variableName) == 0)
        returnValue = 96;
    else if(strcmp("foutput4", variableName) == 0)
        returnValue = 100;
    else if(strcmp("foutput5", variableName) == 0)
        returnValue = 104;
    else if(strcmp("foutput6", variableName) == 0)
        returnValue = 108;
    else if(strcmp("foutput7", variableName) == 0)
        returnValue = 112;
    else if(strcmp("foutput8", variableName) == 0)
        returnValue = 116;
    else if(strcmp("foutput9", variableName) == 0)
        returnValue = 120;
    else if(strcmp("foutput10", variableName) == 0)
        returnValue = 124;
    else if(strcmp("tests", variableName) == 0)
        returnValue = 128;
    else if(strcmp("numInputs", variableName) == 0)
        returnValue = 132;
    else if(strcmp("numOutputs", variableName) == 0)
        returnValue = 136;
    else if(strcmp("Layers", variableName) == 0)
        returnValue = 140;
    else if(strcmp("batch_size", variableName) == 0)
        returnValue = 144;
    else if(strcmp("activation1", variableName) == 0)
        returnValue = 148;
    else if(strcmp("Nodes1", variableName) == 0)
        returnValue = 152;
    else if(strcmp("activation2", variableName) == 0)
        returnValue = 156;
    else if(strcmp("Nodes2", variableName) == 0)
        returnValue = 160;
    else if(strcmp("activation3", variableName) == 0)
        returnValue = 164;
    else if(strcmp("Nodes3", variableName) == 0)
        returnValue = 168;
    else if(strcmp("testout", variableName) == 0)
        returnValue = 176;
    else if(strcmp("W1", variableName) == 0)
        returnValue = 184;
    else if(strcmp("b1", variableName) == 0)
        returnValue = 328;
    else if(strcmp("W2", variableName) == 0)
        returnValue = 352;
    else if(strcmp("b2", variableName) == 0)
        returnValue = 424;
    else if(strcmp("W3", variableName) == 0)
        returnValue = 448;
    else if(strcmp("b3", variableName) == 0)
        returnValue = 520;
    else if(strcmp("Wdense", variableName) == 0)
        returnValue = 544;
    else if(strcmp("bdense", variableName) == 0)
        returnValue = 616;
    else if(strcmp("N", variableName) == 0)
        returnValue = 640;
    else if(strcmp("Y", variableName) == 0)
        returnValue = 644;
    else if(strcmp("N1", variableName) == 0)
        returnValue = 648;
    else if(strcmp("N2", variableName) == 0)
        returnValue = 652;
    else if(strcmp("N3", variableName) == 0)
        returnValue = 656;
    else if(strcmp("X", variableName) == 0)
        returnValue = 664;
    else if(strcmp("y", variableName) == 0)
        returnValue = 744;
    else if(strcmp("a1", variableName) == 0)
        returnValue = 824;
    else if(strcmp("a2", variableName) == 0)
        returnValue = 904;
    else if(strcmp("a3", variableName) == 0)
        returnValue = 984;
    else if(strcmp("dummyloss", variableName) == 0)
        returnValue = 1064;
    else if(strcmp("a1Loss", variableName) == 0)
        returnValue = 1144;
    else if(strcmp("a2Loss", variableName) == 0)
        returnValue = 1224;
    else if(strcmp("a3Loss", variableName) == 0)
        returnValue = 1304;
    else if(strcmp("loss", variableName) == 0)
        returnValue = 1384;
    else if(strcmp("i", variableName) == 0)
        returnValue = 1464;
    else if(strcmp("k", variableName) == 0)
        returnValue = 1468;
    else if(strcmp("indx", variableName) == 0)
        returnValue = 1472;
    else if(strcmp("j", variableName) == 0)
        returnValue = 1476;
    else if(strcmp("L", variableName) == 0)
        returnValue = 1480;
    else if(strcmp("Lr", variableName) == 0)
        returnValue = 1488;
    else if(strcmp("Ndense", variableName) == 0)
        returnValue = 1496;
    else if(strcmp(".LC0", variableName) == 0)
        returnValue = 1504;
    else 
        returnValue = 0xFFFFFFFF;  // Signal that the variable was not found.
    return returnValue;
}
