__asm__(".section \".text\"");
__asm__(".align 2");
__asm__("b .main");
// now here are the lines from the GLOBAL section, typically #defines... 
// ======================================================================
// Include file below is generated by C-Builder      

// and contains the variables declared as -          

// PARAMETERS, INPUTS, OUTPUTS . . .                 

#define PI        3.1415926535897932384626433832795   // definition of PI                 

#define TWOPI     6.283185307179586476925286766559    // definition of 2.0*PI             

#define E         2.71828182845904523536028747135266  // definition of E                  

#define EINV      0.36787944117144232159552377016147  // definition of E Inverse (1/E)    

#define RT2       1.4142135623730950488016887242097   // definition of square root 2.0    

#define RT3       1.7320508075688772935274463415059   // definition of square root 3.0    

#define INV_ROOT2 0.70710678118654752440084436210485                                      

// finished the GLOBAL section (#defines)
// ======================================


// now here are the static variables the user has defined... 
//===========================================================
double testout;

// -----------------------------------------------   

// Variables declared here may be used in both the   

// RAM: and CODE: sections below.                    

// -----------------------------------------------   

//    double dt;    

double W1[18] =  { 0.107636325, 0.067938805, 0.14532101, -0.22826472, 0.039204452, 1.2104177, -0.2996164, 0.8820697, -0.63229483, -0.030488968, 0.5512029, 0.07976646, 0.22130048, -0.4609804, 0.2206365, 0.9901441, -0.30606145, -0.6965658 };

double b1[3] = { 0.023580035, 0.0058132247, 0.021381315 };





double W2[9] =  { -0.21735963, -0.95582664, -1.2001845, 0.64842796, 0.43467012, -0.79226154, 0.35005328, -0.6938111, -0.9446461 };



double b2[3] = { 0.0060735303, 0.02123643, -0.0040892987 };





double W3[9] =  { -0.5647482, 0.513669, 1.2727365, -1.1156123, -0.9551774, -0.8200697, 0.4101158, -0.32294378, 0.9075196 };



double b3[3] = { -0.008884262, -0.022166247, 0.040670604 };







//double W2[100] = {0.0};

//double b2[10] = {0.0};



//double W3[100] = {0.0};

//double b3[10] = {0.0};





double Wdense[9] = {1.0, 0.0, 0.0,
0.0, 1.0, 0.0,
0.0, 0.0, 1.0};

double bdense[3] = {0.0, 0.0, 0.0};





int N;

//int n;

int Y;



int N1;

int N2;

int N3;



double X[10] = {0.0}; //Array to host inputs

double y[10] = {0.0}; 



double a1[10]; // layer 1 output array

double a2[10]; // layer 2 output array

double a3[10]; // layer 3 output array





double dummyloss[10] = {0.0};

double a1Loss[10] = {0.0};

double a2Loss[10] = {0.0};

double a3Loss[10] = {0.0};





double loss[10] = {0.0}; // Array to host the loss function of //each output



int i;

int k;

int indx;

int j;



double L;



double Lr;

int Ndense;

// - E n d   o f   S T A T I C :   S e c t i o n -   



// end the user defined STATIC declarations ... 
//===========================================================

// declare the Parameters so that the user's code can reference them
// =================================================================
  int numInputs;   //Description

  int numOutputs;  //Description

  int Layers;      //Description

  int batch_size;  //Description

  int activation1; //Description

  int Nodes1;      //Description

  int activation2; //Description

  int Nodes2;      //Description

  int activation3; //Description

  int Nodes3;      //Description


// end Parameter declarations 
// ========================== 


// declare the INPUTS so that the user's code can reference them
// ======================================================================
double* Learning_rate;
double* lamm;
double* x1;
double* x2;
double* x3;
double* x4;
double* x5;
double* x6;
double* x7;
double* x8;
double* x9;
double* x10;
double* L1;
double* L2;
double* L3;
double* L4;
double* L5;
double* L6;
double* L7;
double* L8;
double* L9;
double* L10;

// end INPUTS declarations 
// ================================ 


// declare the OUTPUTS so that the user's code can reference them
// ======================================================================
double* foutput;
double* foutput2;
double* foutput3;
double* foutput4;
double* foutput5;
double* foutput6;
double* foutput7;
double* foutput8;
double* foutput9;
double* foutput10;
double* tests;

// end OUTPUTS declarations 
// ================================ 


// declare the NODES so that the user's code can reference them
// ======================================================================

// end NODES declarations 
// ================================ 


// declare the GVALUES so that the user's code can reference them
// ======================================================================

// end GVALUES declarations 
// ================================ 


// declare the SWITCHED_GVALUES_INDEX so that the user's code can reference them
// ======================================================================

// end SWITCHED_GVALUES_INDEX declarations 
// ================================ 


// declare the INJECTIONS so that the user's code can reference them
// ======================================================================

// end INJECTIONS declarations 
// ================================ 

// methods from the CODE_FUNCTIONS section:
// ========================================
#include <builtin_gcc.h>



static void LoadX(int N){ // This function loads the input array

X[0] = (*x1);
if (N>1){
	X[1] = (*x2);
	if (N>2){
		X[2] = (*x3);
		if (N>3){
			X[3] = (*x4);
			if (N>4){
				X[4] = (*x5);
				if (N>5){
					X[5] = (*x6);
					if (N>6){
						X[6] = (*x7);
						if (N>7){
							X[7] = (*x8);
							if (N>8){
								X[8] = (*x9);
								if (N>9){
								X[9] = (*x10);

								}
							}

						}
					}
				}
			}
		}
	}
}
}







//The following function is the feedforward operation (predict)



static void ANNLayer(int N, int Y, double X[10], double a[10], double W[100], double b[10]){

for (k = 0; k<Y; k++){
i = N*k;
//a[k] = 0;

for (j = 0; j<N; j++){

	a[k] +=W[j+i] * X[j];

}

a[k] += b[k];

}
}



static void DenseLayer(int N, int Y, double X[10], double W[100], double b[10]){

for (k = 0; k<Y; k++){
i = N*k;
y[k] = W[0+i] * X[0]+ W[1+i]*X[1] + W[2+i]*X[2] +W[3+i]*X[3] + W[4+i] * X[4]+ W[5+i]*X[5] + W[6+i]*X[6] + W[7+i]*X[7] +W[8+i]*X[8] +W[9+i]*X[9] + b[k]; 
}
}





static void FeedForward(){

ANNLayer(N, N1,X, a1, W1, b1);
//testout = a1[2];
if (Layers > 1){

	ANNLayer(N1, N2, a1, a2, W2, b2);

	if (Layers > 2){
		ANNLayer(N2, N3, a2, a3, W3, b3);
		DenseLayer(Ndense, Y,a3, Wdense, bdense);
	}

	else{
		DenseLayer(Ndense, Y,a2, Wdense, bdense);
	}

}
else{
	DenseLayer(Ndense, Y,a1, Wdense, bdense);
	}
}





static void LoadL(int Y){
loss[0] = (*L1);
if (Y>1){
	loss[1] = (*L2);
	if (Y>2){
		loss[2] = (*L3);
		if (Y>3){
			loss[3] = (*L4);
			if (Y>4){
				loss[4] = (*L5);
				if (Y>5){
					loss[5] = (*L6);
					if (Y>6){
						loss[6] = (*L7);
						if (Y>7){
							loss[7] = (*L8);
							if (Y>8){
								loss[8] = (*L9);
								if (Y>9){
								 loss[9] =(*L10); 

								}
							}
						}
					}
				}
			}
		}
	}
	
}
}





static void ResetNodes(numLayers){
if (numLayers==1){
	for (i = 0; i<N1; i++){
		a1[i] = 0.0;
	}
}

	else if (numLayers==2){
	for (i = 0; i<10; i++){
		a2[i] = 0.0;
		a1[i] = 0.0;

	}
	}

	else{

	for (i = 0; i<10; i++){
		a3[i] = 0.0;
		a2[i] = 0.0;
		a1[i] = 0.0;
	}
	}

}







static void ResetLosses(numLayers){

if (numLayers==1){
	for (i = 0; i<N1; i++){
		a1Loss[i] = 0.0;
		dummyloss[i] = 0.0;
	}
}

	else if (numLayers==2){
	for (i = 0; i<10; i++){
		a2Loss[i] = 0.0;
		a1Loss[i] = 0.0;
		dummyloss[i] = 0.0;
	}
	}

	else{

	for (i = 0; i<10; i++){
		a3Loss[i] = 0.0;
		a2Loss[i] = 0.0;
		a1Loss[i] = 0.0;
		dummyloss[i] = 0.0;
	}
	}

}





static void Backprop(double Loss[10], int N, int Y, double alpha, double A[10], double W[100], double b[10], double lossback[10]){
//alpha = (*Learning_rate);	
for (k = 0; k<Y; k++){
	L = Loss[k];
	//b[k] = b[k] - L*alpha;
	b[k] -= L*alpha;
	testout = alpha;
	for (i = 0; i<N; i++){ 
		W[N*k+i] = W[N*k+i] - L* alpha* A[i];
		lossback[i] += L * W[N*k+i];
	}
}

}











static void Training(numLayers){
	Lr = (*Learning_rate);

if (numLayers==1){
		
		Backprop(loss, N1, Y, Lr, a1, Wdense, bdense, a1Loss);
		
	Backprop(a1Loss, N, N1, Lr, X, W1, b1, dummyloss);
	//testout = a1[2];
}

	else if (numLayers==2){
		Backprop(loss, N2, Y, Lr, a2, Wdense, bdense, a2Loss);
		Backprop(a2Loss, N1, N2, Lr, a1, W2, b2, a1Loss);
		Backprop(a1Loss, N, N1, Lr, a1, W1, b1, dummyloss);
	}

	else{

		Backprop(loss, N3, Y, Lr,a3, Wdense, bdense, a3Loss);
		Backprop(a3Loss, N2, N3, Lr,a2, W3, b3, a2Loss);
		Backprop(a2Loss, N1, N2, Lr,a1, W2, b2, a1Loss);
		Backprop(a1Loss, N, N1, Lr,X, W1, b1, dummyloss);
	}

	//ResetLosses(numLayers);

}









// end of CODE_FUNCTIONS section:
// ==============================
void main(void)
{
	{
		int ___heap_addr_array_idx__ =0;
	}




LoadX(N);



FeedForward();



(*foutput) = y[0];

(*foutput2) = y[1];

(*foutput3) = y[2];

(*foutput4) = y[3];

(*foutput5) = y[4];

(*foutput6) = y[5];

(*foutput7) = y[6];

(*foutput8) = y[7];

(*foutput9) = y[8];

(*foutput10) = y[9];







if ((*Learning_rate)>0.0){

	LoadL(Y);
	
	Training(Layers);

}





//testout = bdense[0];



(*tests) = testout;



ResetLosses(Layers);



ResetNodes(Layers);

// -----------------------------------------------   

// Place C code here which runs on the RTDS. The     

// code below is entered once each simulation        

// step.                                             

// -----------------------------------------------   





// ------------ End of CODE: Section -------------   

}
