VERSION:
3.001

// Include file below is generated by C-Builder      
// and contains the variables declared as -          
// PARAMETERS, INPUTS, OUTPUTS . . .                 
#include "dv.h"
//#include "math.h"


STATIC:

// -----------------------------------------------   
// Variables declared here may be used in both the   
// RAM: and CODE: sections below.                    
// -----------------------------------------------   

double dt, Ts, Lpu, tau;   



// - E n d   o f   S T A T I C :   S e c t i o n -   

RAM_FUNCTIONS:

// -----------------------------------------------   
// This section should contain any 'c' functions     
// to be called from the RAM section (either         
// RAM_PASS1 or RAM_PASS2). Example:                 
//                                                   
// static double myFunction(double v1, double v2)    
// {                                                 
//     return(v1*v2);                                
// }                                                 
// -----------------------------------------------


RAM:

// -----------------------------------------------   
// Place C code here which computes constants        
// required for the CODE: section below.  The C      
// code here is executed once, prior to the start    
// of the simulation case.                           
// -----------------------------------------------   

dt = getTimeStep();  
Ts = 1/f; 



// ------------- End of RAM: Section ------------- 
  
CODE_FUNCTIONS:

double calculate_u(double i_ref, double i_m, double R, double tau, double u_g, double Ts) {
    double exp_term = exp(-Ts / tau);
    double denominator = 1 - exp_term;
    //if (denominator == 0) { // Izbegavanje deljenja nulom
    //    printf("Greska: Deljenje nulom!\n");
    //    return 0;
    //}
    double u = u_g - R * ((i_ref - i_m* exp_term) / denominator);
    return u;
}   


CODE:

// -----------------------------------------------   
// Place C code here which runs on the RTDS. The     
// code below is entered once each simulation        
// step.                                             
// -----------------------------------------------

Lpu = wLpu/wPLL;
tau = Lpu/Rpu;

VAC_A = calculate_u(ia_ref, ia_m, Rpu, tau, vga, Ts);
VAC_B = calculate_u(ib_ref, ib_m, Rpu, tau, vgb, Ts);
VAC_C = calculate_u(ic_ref, ic_m, Rpu, tau, vgc, Ts);
   



// ------------ End of CODE: Section -------------   
