VERSION:
3.001

// Include file below is generated by C-Builder      
// and contains the variables declared as -          
// PARAMETERS, INPUTS, OUTPUTS . . .                 
#include "ANN_Final.h"


STATIC:
double testout;
// -----------------------------------------------   
// Variables declared here may be used in both the   
// RAM: and CODE: sections below.                    
// -----------------------------------------------   
//    double dt;    
double W1[18] =  { 0.107636325, 0.067938805, 0.14532101, -0.22826472, 0.039204452, 1.2104177, -0.2996164, 0.8820697, -0.63229483, -0.030488968, 0.5512029, 0.07976646, 0.22130048, -0.4609804, 0.2206365, 0.9901441, -0.30606145, -0.6965658 };
double b1[3] = { 0.023580035, 0.0058132247, 0.021381315 };


double W2[9] =  { -0.21735963, -0.95582664, -1.2001845, 0.64842796, 0.43467012, -0.79226154, 0.35005328, -0.6938111, -0.9446461 };

double b2[3] = { 0.0060735303, 0.02123643, -0.0040892987 };


double W3[9] =  { -0.5647482, 0.513669, 1.2727365, -1.1156123, -0.9551774, -0.8200697, 0.4101158, -0.32294378, 0.9075196 };

double b3[3] = { -0.008884262, -0.022166247, 0.040670604 };



//double W2[100] = {0.0};
//double b2[10] = {0.0};

//double W3[100] = {0.0};
//double b3[10] = {0.0};


double Wdense[9] = {1.0, 0.0, 0.0,
0.0, 1.0, 0.0,
0.0, 0.0, 1.0};
double bdense[3] = {0.0, 0.0, 0.0};


int N;
//int n;
int Y;

int N1;
int N2;
int N3;

double X[10] = {0.0}; //Array to host inputs
double y[10] = {0.0}; 

double a1[10]; // layer 1 output array
double a2[10]; // layer 2 output array
double a3[10]; // layer 3 output array


double dummyloss[10] = {0.0};
double a1Loss[10] = {0.0};
double a2Loss[10] = {0.0};
double a3Loss[10] = {0.0};


double loss[10] = {0.0}; // Array to host the loss function of //each output

int i;
int k;
int indx;
int j;

double L;

double Lr;
int Ndense;
// - E n d   o f   S T A T I C :   S e c t i o n -   

RAM_FUNCTIONS:

// -----------------------------------------------   
// This section should contain any 'c' functions     
// to be called from the RAM section (either         
// RAM_PASS1 or RAM_PASS2). Example:                 
//                                                   
// static double myFunction(double v1, double v2)    
// {                                                 
//     return(v1*v2);                                
// }                                                 
// -----------------------------------------------   

RAM:
//n = numInputs + numOutputs;
N = numInputs;
Y = numOutputs;

N1 = Nodes1;
N2 = Nodes2;
N3 = Nodes3;



if (Layers == 1){

Ndense = N1;

}

else if (Layers == 2){

Ndense = N2;
}

else{
Ndense = N3;
}

// -----------------------------------------------   
// Place C code here which computes constants        
// required for the CODE: section below.  The C      
// code here is executed once, prior to the start    
// of the simulation case.                           
// -----------------------------------------------   
//    dt= getTimeStep();                             


// ------------- End of RAM: Section -------------   




CODE_FUNCTIONS:

static void LoadX(int N){ // This function loads the input array

X[0] = x1;
if (N>1){
	X[1] = x2;
	if (N>2){
		X[2] = x3;
		if (N>3){
			X[3] = x4;
			if (N>4){
				X[4] = x5;
				if (N>5){
					X[5] = x6;
					if (N>6){
						X[6] = x7;
						if (N>7){
							X[7] = x8;
							if (N>8){
								X[8] = x9;
								if (N>9){
								X[9] = x10;

								}
							}

						}
					}
				}
			}
		}
	}
}
}



//The following function is the feedforward operation (predict)

static void ANNLayer(int N, int Y, double X[10], double a[10], double W[100], double b[10]){

for (k = 0; k<Y; k++){
i = N*k;
//a[k] = 0;

for (j = 0; j<N; j++){

	a[k] +=W[j+i] * X[j];

}

a[k] += b[k];

}
}

static void DenseLayer(int N, int Y, double X[10], double W[100], double b[10]){

for (k = 0; k<Y; k++){
i = N*k;
y[k] = W[0+i] * X[0]+ W[1+i]*X[1] + W[2+i]*X[2] +W[3+i]*X[3] + W[4+i] * X[4]+ W[5+i]*X[5] + W[6+i]*X[6] + W[7+i]*X[7] +W[8+i]*X[8] +W[9+i]*X[9] + b[k]; 
}
}


static void FeedForward(){

ANNLayer(N, N1,X, a1, W1, b1);
//testout = a1[2];
if (Layers > 1){

	ANNLayer(N1, N2, a1, a2, W2, b2);

	if (Layers > 2){
		ANNLayer(N2, N3, a2, a3, W3, b3);
		DenseLayer(Ndense, Y,a3, Wdense, bdense);
	}

	else{
		DenseLayer(Ndense, Y,a2, Wdense, bdense);
	}

}
else{
	DenseLayer(Ndense, Y,a1, Wdense, bdense);
	}
}


static void LoadL(int Y){
loss[0] = L1;
if (Y>1){
	loss[1] = L2;
	if (Y>2){
		loss[2] = L3;
		if (Y>3){
			loss[3] = L4;
			if (Y>4){
				loss[4] = L5;
				if (Y>5){
					loss[5] = L6;
					if (Y>6){
						loss[6] = L7;
						if (Y>7){
							loss[7] = L8;
							if (Y>8){
								loss[8] = L9;
								if (Y>9){
								 loss[9] =L10; 

								}
							}
						}
					}
				}
			}
		}
	}
	
}
}


static void ResetNodes(numLayers){
if (numLayers==1){
	for (i = 0; i<N1; i++){
		a1[i] = 0.0;
	}
}

	else if (numLayers==2){
	for (i = 0; i<10; i++){
		a2[i] = 0.0;
		a1[i] = 0.0;

	}
	}

	else{

	for (i = 0; i<10; i++){
		a3[i] = 0.0;
		a2[i] = 0.0;
		a1[i] = 0.0;
	}
	}

}



static void ResetLosses(numLayers){

if (numLayers==1){
	for (i = 0; i<N1; i++){
		a1Loss[i] = 0.0;
		dummyloss[i] = 0.0;
	}
}

	else if (numLayers==2){
	for (i = 0; i<10; i++){
		a2Loss[i] = 0.0;
		a1Loss[i] = 0.0;
		dummyloss[i] = 0.0;
	}
	}

	else{

	for (i = 0; i<10; i++){
		a3Loss[i] = 0.0;
		a2Loss[i] = 0.0;
		a1Loss[i] = 0.0;
		dummyloss[i] = 0.0;
	}
	}

}


static void Backprop(double Loss[10], int N, int Y, double alpha, double A[10], double W[100], double b[10], double lossback[10]){
//alpha = Learning_rate;	
for (k = 0; k<Y; k++){
	L = Loss[k];
	//b[k] = b[k] - L*alpha;
	b[k] -= L*alpha;
	testout = alpha;
	for (i = 0; i<N; i++){ 
		W[N*k+i] = W[N*k+i] - L* alpha* A[i];
		lossback[i] += L * W[N*k+i];
	}
}

}





static void Training(numLayers){
	Lr = Learning_rate;

if (numLayers==1){
		
		Backprop(loss, N1, Y, Lr, a1, Wdense, bdense, a1Loss);
		
	Backprop(a1Loss, N, N1, Lr, X, W1, b1, dummyloss);
	//testout = a1[2];
}

	else if (numLayers==2){
		Backprop(loss, N2, Y, Lr, a2, Wdense, bdense, a2Loss);
		Backprop(a2Loss, N1, N2, Lr, a1, W2, b2, a1Loss);
		Backprop(a1Loss, N, N1, Lr, a1, W1, b1, dummyloss);
	}

	else{

		Backprop(loss, N3, Y, Lr,a3, Wdense, bdense, a3Loss);
		Backprop(a3Loss, N2, N3, Lr,a2, W3, b3, a2Loss);
		Backprop(a2Loss, N1, N2, Lr,a1, W2, b2, a1Loss);
		Backprop(a1Loss, N, N1, Lr,X, W1, b1, dummyloss);
	}

	//ResetLosses(numLayers);

}




CODE:


LoadX(N);

FeedForward();

foutput = y[0];
foutput2 = y[1];
foutput3 = y[2];
foutput4 = y[3];
foutput5 = y[4];
foutput6 = y[5];
foutput7 = y[6];
foutput8 = y[7];
foutput9 = y[8];
foutput10 = y[9];



if (Learning_rate>0.0){

	LoadL(Y);
	
	Training(Layers);

}


//testout = bdense[0];

tests = testout;

ResetLosses(Layers);

ResetNodes(Layers);
// -----------------------------------------------   
// Place C code here which runs on the RTDS. The     
// code below is entered once each simulation        
// step.                                             
// -----------------------------------------------   


// ------------ End of CODE: Section -------------   
