__asm__(".section \".text\"");
__asm__(".align 2");
__asm__("b .main");
// now here are the lines from the GLOBAL section, typically #defines... 
// ======================================================================
// Include file below is generated by C-Builder      

// and contains the variables declared as -          

// PARAMETERS, INPUTS, OUTPUTS . . .                 

#define PI        3.1415926535897932384626433832795   // definition of PI                 

#define TWOPI     6.283185307179586476925286766559    // definition of 2.0*PI             

#define E         2.71828182845904523536028747135266  // definition of E                  

#define EINV      0.36787944117144232159552377016147  // definition of E Inverse (1/E)    

#define RT2       1.4142135623730950488016887242097   // definition of square root 2.0    

#define RT3       1.7320508075688772935274463415059   // definition of square root 3.0    

#define INV_ROOT2 0.70710678118654752440084436210485                                      

//#include "math.h"

// finished the GLOBAL section (#defines)
// ======================================


// now here are the static variables the user has defined... 
//===========================================================


// -----------------------------------------------   

// Variables declared here may be used in both the   

// RAM: and CODE: sections below.                    

// -----------------------------------------------   



double dt, Ts, Lpu, tau;   







// - E n d   o f   S T A T I C :   S e c t i o n -   



// end the user defined STATIC declarations ... 
//===========================================================

// declare the Parameters so that the user's code can reference them
// =================================================================
  double f;   //Switching freq.

  double Rpu; //Resistance p.u.


// end Parameter declarations 
// ========================== 


// declare the INPUTS so that the user's code can reference them
// ======================================================================
double* wPLL;
double* ia_ref;
double* ia_m;
double* ib_ref;
double* ib_m;
double* ic_ref;
double* ic_m;
double* vga;
double* vgb;
double* vgc;
double* wLpu;

// end INPUTS declarations 
// ================================ 


// declare the OUTPUTS so that the user's code can reference them
// ======================================================================
double* VAC_A;
double* VAC_B;
double* VAC_C;

// end OUTPUTS declarations 
// ================================ 


// declare the NODES so that the user's code can reference them
// ======================================================================

// end NODES declarations 
// ================================ 


// declare the GVALUES so that the user's code can reference them
// ======================================================================

// end GVALUES declarations 
// ================================ 


// declare the SWITCHED_GVALUES_INDEX so that the user's code can reference them
// ======================================================================

// end SWITCHED_GVALUES_INDEX declarations 
// ================================ 


// declare the INJECTIONS so that the user's code can reference them
// ======================================================================

// end INJECTIONS declarations 
// ================================ 

// methods from the CODE_FUNCTIONS section:
// ========================================
#include <builtin_gcc.h>



double calculate_u(double i_ref, double i_m, double R, double L, double u_g, double Ts) {
    double di_dt = (i_ref - i_m) / Ts; // Diskretna derivacija
    double u = u_g - L * di_dt - R * i_m;
    return u;
}   





// end of CODE_FUNCTIONS section:
// ==============================
void main(void)
{
	{
		int ___heap_addr_array_idx__ =0;
	}


// -----------------------------------------------   

// Place C code here which runs on the RTDS. The     

// code below is entered once each simulation        

// step.                                             

// -----------------------------------------------



Lpu = (*wLpu)/(*wPLL);

tau = Lpu/Rpu;



(*VAC_A) = calculate_u((*ia_ref), (*ia_m), Rpu, Lpu, (*vga), Ts);

(*VAC_B) = calculate_u((*ib_ref), (*ib_m), Rpu, Lpu, (*vgb), Ts);

(*VAC_C) = calculate_u((*ic_ref), (*ic_m), Rpu, Lpu, (*vgc), Ts);

   







// ------------ End of CODE: Section -------------   



}
