#include <stdio.h>
#include <string.h>

#include <cbuilder_ctrl_commonRW.h>

#include <math.h>

static char* checkSumC_euler_a19f5b79a709ca5a36026c2dc8b1629d;
extern void* rpcControlStructurePointer;
extern FILE* mapFile;


// now here are the lines from the GLOBAL section, typically #defines... 
// ======================================================================
// Include file below is generated by C-Builder      

// and contains the variables declared as -          

// PARAMETERS, INPUTS, OUTPUTS . . .                 

#define PI        3.1415926535897932384626433832795   // definition of PI                 

#define TWOPI     6.283185307179586476925286766559    // definition of 2.0*PI             

#define E         2.71828182845904523536028747135266  // definition of E                  

#define EINV      0.36787944117144232159552377016147  // definition of E Inverse (1/E)    

#define RT2       1.4142135623730950488016887242097   // definition of square root 2.0    

#define RT3       1.7320508075688772935274463415059   // definition of square root 3.0    

#define INV_ROOT2 0.70710678118654752440084436210485                                      

//#include "math.h"

// finished the GLOBAL section (#defines)
// ======================================


// now here are the static variables the user has defined... 
//===========================================================


// -----------------------------------------------   

// Variables declared here may be used in both the   

// RAM: and CODE: sections below.                    

// -----------------------------------------------   



static double dt, Ts, Lpu, tau;   







// - E n d   o f   S T A T I C :   S e c t i o n -   



// end the user defined STATIC declarations ... 
//===========================================================

// declare the Parameters so that the user's code can reference them
// =================================================================
static   double f;   //Switching freq.

static   double Rpu; //Resistance p.u.


// end Parameter declarations 
// ========================== 


static void initializeParameterDataRW(void *this_)
{
    // initialize the Parameter values so that the user's code can reference them*/
    // ===========================================================================
    f = getRealParameter(this_,"f");
    Rpu = getRealParameter(this_,"Rpu");

    // end initializing Parameters 
    // =========================== 

}


static void saveInstance (void *this_, int R_proc1);

static void loadInstance (void *this_, int R_proc1);

/* copy the lines of code from the RAM_FUNCTIONS section */


// -----------------------------------------------   

// This section should contain any 'c' functions     

// to be called from the RAM section (either         

// RAM_PASS1 or RAM_PASS2). Example:                 

//                                                   

// static double myFunction(double v1, double v2)    

// {                                                 

//     return(v1*v2);                                

// }                                                 

// -----------------------------------------------






static void initializeLocalDataRW(void *this_, int R_proc1)
{
    // initialize the local data based on a special section in the user's c code
    // ===========================================================================
    rpcControlStructurePointer = this_;

    // end initializing local data 
    // =========================== 

}


static void userSuppliedRamPass0Code(void* this_)
{
    rpcControlStructurePointer = this_;

    // copy the lines of code from the RAM_PASS0 section 
}

static void userSuppliedRamPass1Code(void* this_, int R_proc1)
{
    rpcControlStructurePointer = this_;
    void* comp = this_; //for psys component calls that used 'comp'

    // declare the variables the user has supplied in the RAM_DECLARATIONS section 

    // copy the lines of code from the RAM_PASS1 section 
}
static void* mallocInstancePointer (void *this_, int R_proc1)
{
  //  FILE *debugFile;
  //  debugFile = fopen("C:\\RTDS_USER\\testdebug.txt","a");
  //  fprintf(debugFile,"dbgcmb - entering mallocInstancePointer function for component euler R_proc1 = %i \n",R_proc1);
  //  fclose(debugFile);

    rpcControlStructurePointer = this_;
    void* staticInstancePointer = NULL; 
    int sizeOfStaticSection = 32;
    int sizeOfLocalStaticSection = 0;
    staticInstancePointer = (void*)malloc(sizeOfStaticSection+sizeOfLocalStaticSection);
    return(staticInstancePointer);
}


static void saveInstance (void *this_, int R_proc1)
{
    rpcControlStructurePointer = this_;
    unsigned char* staticVariablesInstancePtr = getLocalStaticInstancePointer_RW(this_);
   // unsigned char* staticVariablesInstancePtr = NULL;
    if (staticVariablesInstancePtr == NULL)
    {
        staticVariablesInstancePtr = mallocInstancePointer (this_,R_proc1);
        setLocalStaticInstancePointer_RW(this_,staticVariablesInstancePtr);
    }

    unsigned char* tempPtr = staticVariablesInstancePtr;
    int index = 0;
    memcpy(tempPtr, (unsigned char*)&dt,sizeof(dt));
    tempPtr += sizeof(dt);
    memcpy(tempPtr, (unsigned char*)&Ts,sizeof(Ts));
    tempPtr += sizeof(Ts);
    memcpy(tempPtr, (unsigned char*)&Lpu,sizeof(Lpu));
    tempPtr += sizeof(Lpu);
    memcpy(tempPtr, (unsigned char*)&tau,sizeof(tau));
    tempPtr += sizeof(tau);
}

static void loadInstance (void *this_, int R_proc1)
{
    rpcControlStructurePointer = this_;
    unsigned char* staticVariablesInstancePtr = getLocalStaticInstancePointer_RW(this_);
    unsigned char* tempPtr = staticVariablesInstancePtr;
    int index = 0;
    if (staticVariablesInstancePtr == NULL)
        return;
    memcpy((unsigned char*)&dt, tempPtr, sizeof(dt));
    tempPtr += sizeof(dt);
    memcpy((unsigned char*)&Ts, tempPtr, sizeof(Ts));
    tempPtr += sizeof(Ts);
    memcpy((unsigned char*)&Lpu, tempPtr, sizeof(Lpu));
    tempPtr += sizeof(Lpu);
    memcpy((unsigned char*)&tau, tempPtr, sizeof(tau));
    tempPtr += sizeof(tau);
}

DllExport int euler_GET_NUM_NAMED_INPUTS(void *this_)
{
    //This comes from CmodelCompiler.createCtlExtraIOCode
    //int cntl_idx;
    int numNamedInputs = 0;
    //rpcControlStructurePointer = this_;
    //cntl_idx = 0;
    numNamedInputs = 0;
    return(numNamedInputs);
}
DllExport int euler_GET_NUM_NAMED_OUTPUTS(void *this_)
{
    //This comes from CmodelCompiler.createCtlExtraIOCode
    //int cntl_idx;
    //rpcControlStructurePointer = this_;
    int numNamedOutputs = 0;
    //cntl_idx = 0;
    numNamedOutputs = 0;
    //this code from CmodelCompiler.createCtlExtraIOCode
    return(numNamedOutputs);
}
DllExport int euler_ADD_EXTRA_IO(void *this_, int R_proc1)
{
    //This comes from CmodelCompiler.createCtlExtraIOCode
    int cntl_idx;
    rpcControlStructurePointer = this_;
    initializeParameterDataRW(this_);

    initializeLocalDataRW(this_, R_proc1);

    saveInstance(this_,R_proc1);  //new!
}
DllExport int euler_GET_FLAG_PARTICIPATION(void *this_)
{
    //This comes from CmodelCompiler.createFlagParticipationCode
    int flags;
    flags = 0;
    flags = flags | 0x04;
    return(flags);
}

static void userSuppliedRamCode(int R_proc1)
{
   ramPassNumber = 2;


    /***** declare the variables the user has supplied in the RAM_DECLARATIONS section */

    /* copy the lines of code from the RAM section */
// -----------------------------------------------   

// Place C code here which computes constants        

// required for the CODE: section below.  The C      

// code here is executed once, prior to the start    

// of the simulation case.                           

// -----------------------------------------------   

dt = getTimeStep();  

Ts = 1/f; 

// ------------- End of RAM: Section ------------- 

}
DllExport void euler_DM_RW (void *this_, int R_proc1,  int *wdadr_ptr1)
{
    rpcControlStructurePointer = this_;
    loadInstance(this_, R_proc1);  //new!
    initializeParameterDataRW(this_);
 //   initializeLocalDataRW(this_, R_proc1);    //<<<<<<<<<<<<<< TO-DO, change to this!
    int __inDMCode = 1;
    ramPassNumber = 1;
    FILE* signatureFile;
    //re-execute the Ram Pass1 code. This is necessary because
    //if more than one instance of a particular model is used in 
    //a case, all instances will share the same static variables.
    //This means the variables will have to be re-calculated before 
    //they are written out to data memory.

    //userSuppliedRamPass1Code(this_,R_proc1);  //<<<<<<<<<<<<<< TO-DO, change to this!
    //now call the Ram Pass2 code 

    ramPassNumber = 2;
    userSuppliedRamCode(R_proc1);
    double         __fdata=0;
    int            __idata=0;
    unsigned char *__bdata;
    char          *__pattern;
    int            __loopindex=0;
    char           __cdata[12]; //this is sized to match the Cdta entry in rt_ctl_data_t structure in rtdspc
    unsigned char* __blob;
    char*          __blob2;
    char          *__hexstring;
    char          *__pos;


    //1) storing variable wPLL
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"wPLL",1,1);

    //1) storing variable ia_ref
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"ia_ref",1,1);

    //1) storing variable ia_m
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"ia_m",1,1);

    //1) storing variable ib_ref
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"ib_ref",1,1);

    //1) storing variable ib_m
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"ib_m",1,1);

    //1) storing variable ic_ref
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"ic_ref",1,1);

    //1) storing variable ic_m
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"ic_m",1,1);

    //1) storing variable vga
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"vga",1,1);

    //1) storing variable vgb
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"vgb",1,1);

    //1) storing variable vgc
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"vgc",1,1);

    //1) storing variable wLpu
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"wLpu",1,1);

    //2) storing variable VAC_A
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"VAC_A",0,1);

    //2) storing variable VAC_B
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"VAC_B",0,1);

    //2) storing variable VAC_C
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"VAC_C",0,1);

    //3) storing variable f
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"f",1,1);

    //3) storing variable Rpu
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"Rpu",1,1);

    //3) storing variable dt
    //----------------
     __bdata = (unsigned char*) malloc(8);
     endianSwapRW((unsigned char *)(&dt),2,"Dd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,2,"dt");
    free(__bdata); //2
    //----------------


    //3) storing variable Ts
    //----------------
     __bdata = (unsigned char*) malloc(8);
     endianSwapRW((unsigned char *)(&Ts),2,"Dd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,2,"Ts");
    free(__bdata); //2
    //----------------


    //3) storing variable Lpu
    //----------------
     __bdata = (unsigned char*) malloc(8);
     endianSwapRW((unsigned char *)(&Lpu),2,"Dd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,2,"Lpu");
    free(__bdata); //2
    //----------------


    //3) storing variable tau
    //----------------
     __bdata = (unsigned char*) malloc(8);
     endianSwapRW((unsigned char *)(&tau),2,"Dd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,2,"tau");
    free(__bdata); //2
    //----------------

//setting the total size of the memory map to 104
   freeScratchMemoryPointers();
}
DllExport void euler_RR(void *this_, int R_proc1)
{
    rpcControlStructurePointer = this_;
    int __idata = 0;
    int __inDMCode = 0;
    int __extraData;
    ramPassNumber = 1;
    initializeParameterDataRW(this_);

    loadInstance(this_,R_proc1); //new!

    userSuppliedRamPass1Code(this_,R_proc1);
    saveInstance(this_,R_proc1);   //new!
    freeScratchMemoryPointers();
}
DllExport int euler_getDMSize(void *this_, int R_proc1)
{
    return((104)/4);
}
DllExport void euler_INIT(void *this_)
{
    rpcControlStructurePointer = this_;
    ramPassNumber = 0;
    initializeParameterDataRW(this_);

    userSuppliedRamPass0Code(this_);
}
DllExport unsigned int euler_getVariableDMOffset(char* variableName)
{
    int returnValue;
    if(strcmp("wPLL", variableName) == 0)
        returnValue = 0;
    else if(strcmp("ia_ref", variableName) == 0)
        returnValue = 4;
    else if(strcmp("ia_m", variableName) == 0)
        returnValue = 8;
    else if(strcmp("ib_ref", variableName) == 0)
        returnValue = 12;
    else if(strcmp("ib_m", variableName) == 0)
        returnValue = 16;
    else if(strcmp("ic_ref", variableName) == 0)
        returnValue = 20;
    else if(strcmp("ic_m", variableName) == 0)
        returnValue = 24;
    else if(strcmp("vga", variableName) == 0)
        returnValue = 28;
    else if(strcmp("vgb", variableName) == 0)
        returnValue = 32;
    else if(strcmp("vgc", variableName) == 0)
        returnValue = 36;
    else if(strcmp("wLpu", variableName) == 0)
        returnValue = 40;
    else if(strcmp("VAC_A", variableName) == 0)
        returnValue = 44;
    else if(strcmp("VAC_B", variableName) == 0)
        returnValue = 48;
    else if(strcmp("VAC_C", variableName) == 0)
        returnValue = 52;
    else if(strcmp("f", variableName) == 0)
        returnValue = 56;
    else if(strcmp("Rpu", variableName) == 0)
        returnValue = 64;
    else if(strcmp("dt", variableName) == 0)
        returnValue = 72;
    else if(strcmp("Ts", variableName) == 0)
        returnValue = 80;
    else if(strcmp("Lpu", variableName) == 0)
        returnValue = 88;
    else if(strcmp("tau", variableName) == 0)
        returnValue = 96;
    else 
        returnValue = 0xFFFFFFFF;  // Signal that the variable was not found.
    return returnValue;
}
