#include <stdio.h>
#include <string.h>

#include <cbuilder_ctrl_commonRW.h>

#include <math.h>

static char* checkSumC_InputLv2_6c4a94460738cb14e923a6387762078f;
extern void* rpcControlStructurePointer;
extern FILE* mapFile;


// now here are the lines from the GLOBAL section, typically #defines... 
// ======================================================================
// Include file below is generated by C-Builder      

// and contains the variables declared as -          

// PARAMETERS, INPUTS, OUTPUTS . . .                 

#define PI        3.1415926535897932384626433832795   // definition of PI                 

#define TWOPI     6.283185307179586476925286766559    // definition of 2.0*PI             

#define E         2.71828182845904523536028747135266  // definition of E                  

#define EINV      0.36787944117144232159552377016147  // definition of E Inverse (1/E)    

#define RT2       1.4142135623730950488016887242097   // definition of square root 2.0    

#define RT3       1.7320508075688772935274463415059   // definition of square root 3.0    

#define INV_ROOT2 0.70710678118654752440084436210485                                      

// finished the GLOBAL section (#defines)
// ======================================


// now here are the static variables the user has defined... 
//===========================================================


// -----------------------------------------------   

// Variables declared here may be used in both the   

// RAM: and CODE: sections below.                    

// -----------------------------------------------   

//    double dt;    

static double W[100] = {-0.22583243, -0.3128571, -0.09350032, 0.05151762, -0.30170206, 0.10661154, 0.13397811, -0.11715875, 0.13758639, -0.37080519, 
                -0.31552383, 0.1287377, -0.32054045, -0.09309492, -0.16414183, 0.2120127, 0.27156818, -0.07757796, 0.04239552, 0.07195159, 
                0.35205592, -0.09705391, 0.33738564, -0.24524731, -0.28469208, 0.25013072, 0.34036605, 0.1005536, -0.33918098, -0.21197596, 
                -0.33672842, 0.24054585, 0.00333349, -0.21373718, 0.25202225, 0.1339504, -0.11438971, -0.202335, 0.22192653, -0.07065314, 
                -0.23420886, 0.21691918, -0.01982722, 0.04454983, 0.20905534, -0.12017015, -0.08227637, -0.05661371, 0.17212206, 0.32163402, 
                0.29030537, 0.28001923, 0.10797155, -0.0928586, -0.1715331, -0.22887881, 0.22965024, -0.07995217, -0.23201016, 0.31551534, 
                0.24058717, -0.00662784, 0.09372023, 0.36184834, -0.38582336, 0.20313682, -0.24181783, 0.02126562, -0.35802985, -0.05997331, 
                0.02444957, 0.26402214, -0.33622075, 0.06562539, -0.227391, 0.20884189, -0.02009295, 0.01609324, -0.19011545, -0.04081026, 
                -0.17759126, 0.18344933, 0.27615151, -0.14534336, 0.07648921, -0.269402, -0.17234415, -0.35345067, 0.07862321, -0.25229918, 
                0.34235341, 0.14599412, 0.24607825, 0.2897428, 0.02386395, 0.37469776, 0.25695225, 0.354817, -0.05244994, 0.03744153};



static double b[10] = {0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0};



static int N;

static int n;

static int Y;





// - E n d   o f   S T A T I C :   S e c t i o n -   



// end the user defined STATIC declarations ... 
//===========================================================

// declare the Parameters so that the user's code can reference them
// =================================================================
static   int numInputs;  //Description

static   int numOutputs; //Description

static   int activation; //Description

static   int batch_size; //Description


// end Parameter declarations 
// ========================== 


static void initializeParameterDataRW(void *this_)
{
    // initialize the Parameter values so that the user's code can reference them*/
    // ===========================================================================
    numInputs = getIntParameter(this_,"numInputs");
    numOutputs = getIntParameter(this_,"numOutputs");
    activation = getIntParameter(this_,"activation");
    batch_size = getIntParameter(this_,"batch_size");

    // end initializing Parameters 
    // =========================== 

}


static void saveInstance (void *this_, int R_proc1);

static void loadInstance (void *this_, int R_proc1);

/* copy the lines of code from the RAM_FUNCTIONS section */


// -----------------------------------------------   

// This section should contain any 'c' functions     

// to be called from the RAM section (either         

// RAM_PASS1 or RAM_PASS2). Example:                 

//                                                   

// static double myFunction(double v1, double v2)    

// {                                                 

//     return(v1*v2);                                

// }                                                 

// -----------------------------------------------   




static void initializeLocalDataRW(void *this_, int R_proc1)
{
    // initialize the local data based on a special section in the user's c code
    // ===========================================================================
    rpcControlStructurePointer = this_;

    // end initializing local data 
    // =========================== 

}


static void userSuppliedRamPass0Code(void* this_)
{
    rpcControlStructurePointer = this_;

    // copy the lines of code from the RAM_PASS0 section 
}

static void userSuppliedRamPass1Code(void* this_, int R_proc1)
{
    rpcControlStructurePointer = this_;
    void* comp = this_; //for psys component calls that used 'comp'

    // declare the variables the user has supplied in the RAM_DECLARATIONS section 

    // copy the lines of code from the RAM_PASS1 section 
}
static void* mallocInstancePointer (void *this_, int R_proc1)
{
  //  FILE *debugFile;
  //  debugFile = fopen("C:\\RTDS_USER\\testdebug.txt","a");
  //  fprintf(debugFile,"dbgcmb - entering mallocInstancePointer function for component InputLv2 R_proc1 = %i \n",R_proc1);
  //  fclose(debugFile);

    rpcControlStructurePointer = this_;
    void* staticInstancePointer = NULL; 
    int sizeOfStaticSection = 892;
    int sizeOfLocalStaticSection = 0;
    staticInstancePointer = (void*)malloc(sizeOfStaticSection+sizeOfLocalStaticSection);
    return(staticInstancePointer);
}


static void saveInstance (void *this_, int R_proc1)
{
    rpcControlStructurePointer = this_;
    unsigned char* staticVariablesInstancePtr = getLocalStaticInstancePointer_RW(this_);
   // unsigned char* staticVariablesInstancePtr = NULL;
    if (staticVariablesInstancePtr == NULL)
    {
        staticVariablesInstancePtr = mallocInstancePointer (this_,R_proc1);
        setLocalStaticInstancePointer_RW(this_,staticVariablesInstancePtr);
    }

    unsigned char* tempPtr = staticVariablesInstancePtr;
    int index = 0;
    memcpy(tempPtr, (unsigned char*)&W,sizeof(W));
    tempPtr += sizeof(W);
    memcpy(tempPtr, (unsigned char*)&b,sizeof(b));
    tempPtr += sizeof(b);
    memcpy(tempPtr, (unsigned char*)&N,sizeof(N));
    tempPtr += sizeof(N);
    memcpy(tempPtr, (unsigned char*)&n,sizeof(n));
    tempPtr += sizeof(n);
    memcpy(tempPtr, (unsigned char*)&Y,sizeof(Y));
    tempPtr += sizeof(Y);
}

static void loadInstance (void *this_, int R_proc1)
{
    rpcControlStructurePointer = this_;
    unsigned char* staticVariablesInstancePtr = getLocalStaticInstancePointer_RW(this_);
    unsigned char* tempPtr = staticVariablesInstancePtr;
    int index = 0;
    if (staticVariablesInstancePtr == NULL)
        return;
    memcpy((unsigned char*)&W, tempPtr, sizeof(W));
    tempPtr += sizeof(W);
    memcpy((unsigned char*)&b, tempPtr, sizeof(b));
    tempPtr += sizeof(b);
    memcpy((unsigned char*)&N, tempPtr, sizeof(N));
    tempPtr += sizeof(N);
    memcpy((unsigned char*)&n, tempPtr, sizeof(n));
    tempPtr += sizeof(n);
    memcpy((unsigned char*)&Y, tempPtr, sizeof(Y));
    tempPtr += sizeof(Y);
}

DllExport int InputLv2_GET_NUM_NAMED_INPUTS(void *this_)
{
    //This comes from CmodelCompiler.createCtlExtraIOCode
    //int cntl_idx;
    int numNamedInputs = 0;
    //rpcControlStructurePointer = this_;
    //cntl_idx = 0;
    numNamedInputs = 0;
    return(numNamedInputs);
}
DllExport int InputLv2_GET_NUM_NAMED_OUTPUTS(void *this_)
{
    //This comes from CmodelCompiler.createCtlExtraIOCode
    //int cntl_idx;
    //rpcControlStructurePointer = this_;
    int numNamedOutputs = 0;
    //cntl_idx = 0;
    numNamedOutputs = 0;
    //this code from CmodelCompiler.createCtlExtraIOCode
    return(numNamedOutputs);
}
DllExport int InputLv2_ADD_EXTRA_IO(void *this_, int R_proc1)
{
    //This comes from CmodelCompiler.createCtlExtraIOCode
    int cntl_idx;
    rpcControlStructurePointer = this_;
    initializeParameterDataRW(this_);

    initializeLocalDataRW(this_, R_proc1);

    saveInstance(this_,R_proc1);  //new!
}
DllExport int InputLv2_GET_FLAG_PARTICIPATION(void *this_)
{
    //This comes from CmodelCompiler.createFlagParticipationCode
    int flags;
    flags = 0;
    flags = flags | 0x04;
    return(flags);
}

static void userSuppliedRamCode(int R_proc1)
{
   ramPassNumber = 2;


    /***** declare the variables the user has supplied in the RAM_DECLARATIONS section */

    /* copy the lines of code from the RAM section */
n = numInputs + numOutputs;

N = numInputs;

Y = numOutputs;

// -----------------------------------------------   

// Place C code here which computes constants        

// required for the CODE: section below.  The C      

// code here is executed once, prior to the start    

// of the simulation case.                           

// -----------------------------------------------   

//    dt= getTimeStep();                             

// ------------- End of RAM: Section -------------   

}
DllExport void InputLv2_DM_RW (void *this_, int R_proc1,  int *wdadr_ptr1)
{
    rpcControlStructurePointer = this_;
    loadInstance(this_, R_proc1);  //new!
    initializeParameterDataRW(this_);
 //   initializeLocalDataRW(this_, R_proc1);    //<<<<<<<<<<<<<< TO-DO, change to this!
    int __inDMCode = 1;
    ramPassNumber = 1;
    FILE* signatureFile;
    //re-execute the Ram Pass1 code. This is necessary because
    //if more than one instance of a particular model is used in 
    //a case, all instances will share the same static variables.
    //This means the variables will have to be re-calculated before 
    //they are written out to data memory.

    //userSuppliedRamPass1Code(this_,R_proc1);  //<<<<<<<<<<<<<< TO-DO, change to this!
    //now call the Ram Pass2 code 

    ramPassNumber = 2;
    userSuppliedRamCode(R_proc1);
    double         __fdata=0;
    int            __idata=0;
    unsigned char *__bdata;
    char          *__pattern;
    int            __loopindex=0;
    char           __cdata[12]; //this is sized to match the Cdta entry in rt_ctl_data_t structure in rtdspc
    unsigned char* __blob;
    char*          __blob2;
    char          *__hexstring;
    char          *__pos;


    //1) storing variable Learning_rate
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"Learning_rate",1,1);

    //1) storing variable input1
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"input1",1,1);

    //1) storing variable L1
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"L1",1,1);

    //1) storing variable input2
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"input2",1,1);

    //1) storing variable input3
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"input3",1,1);

    //1) storing variable input4
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"input4",1,1);

    //1) storing variable input5
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"input5",1,1);

    //1) storing variable input6
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"input6",1,1);

    //1) storing variable input7
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"input7",1,1);

    //1) storing variable input8
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"input8",1,1);

    //1) storing variable input9
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"input9",1,1);

    //1) storing variable input10
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"input10",1,1);

    //1) storing variable L2
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"L2",1,1);

    //1) storing variable L3
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"L3",1,1);

    //1) storing variable L4
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"L4",1,1);

    //1) storing variable L5
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"L5",1,1);

    //1) storing variable L6
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"L6",1,1);

    //1) storing variable L7
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"L7",1,1);

    //1) storing variable L8
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"L8",1,1);

    //1) storing variable L9
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"L9",1,1);

    //1) storing variable L10
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"L10",1,1);

    //1) storing variable lamm
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"lamm",1,1);

    //2) storing variable foutput2
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"foutput2",0,1);

    //2) storing variable foutput3
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"foutput3",0,1);

    //2) storing variable foutput4
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"foutput4",0,1);

    //2) storing variable foutput5
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"foutput5",0,1);

    //2) storing variable foutput6
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"foutput6",0,1);

    //2) storing variable foutput7
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"foutput7",0,1);

    //2) storing variable foutput8
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"foutput8",0,1);

    //2) storing variable foutput9
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"foutput9",0,1);

    //2) storing variable foutput10
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"foutput10",0,1);

    //2) storing variable foutput
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"foutput",0,1);

    //3) storing variable numInputs
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"numInputs",1,1);

    //3) storing variable numOutputs
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"numOutputs",1,1);

    //3) storing variable activation
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"activation",1,1);

    //3) storing variable batch_size
    //----------------
    storeCtlVariableInDM_RW(this_,R_proc1,wdadr_ptr1,"batch_size",1,1);

    //3) storing variable W
    //----------------
     __bdata = (unsigned char*) malloc(800);
     endianSwapRW((unsigned char *)(&W),200,"DdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,200,"W");
    free(__bdata); //2
    //----------------


    //3) storing variable b
    //----------------
     __bdata = (unsigned char*) malloc(80);
     endianSwapRW((unsigned char *)(&b),20,"DdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDdDd",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,20,"b");
    free(__bdata); //2
    //----------------


    //3) storing variable N
    //----------------
     __bdata = (unsigned char*) malloc(4);
     endianSwapRW((unsigned char *)(&N),1,"i",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,1,"N");
    free(__bdata); //2
    //----------------


    //3) storing variable n
    //----------------
     __bdata = (unsigned char*) malloc(4);
     endianSwapRW((unsigned char *)(&n),1,"i",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,1,"n");
    free(__bdata); //2
    //----------------


    //3) storing variable Y
    //----------------
     __bdata = (unsigned char*) malloc(4);
     endianSwapRW((unsigned char *)(&Y),1,"i",__bdata);
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,1,"Y");
    free(__bdata); //2
    //----------------

    //increasing wdadr_ptr1 in order to align variable L with alignment requirement of 8
    *wdadr_ptr1 += 1;

    //3) storing variable L
    //----------------

    //4) storing variable L: allocating blob of size 8 plus 3 because we need an extra 3 bytes to fill out the");
    //last 'unsigned char' to be a full 'int' in size, so that it sscanf properly with %2x. (otherwise it's nasty!!!)");
    __bdata = (unsigned char*)malloc(8+3);
    for (__loopindex=0; __loopindex<8; __loopindex++)
    {
        __bdata[__loopindex] = 0;
    }
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,2,"L");
    free(__bdata);  //1

    //3) storing variable indx
    //----------------

    //4) storing variable indx: allocating blob of size 4 plus 3 because we need an extra 3 bytes to fill out the");
    //last 'unsigned char' to be a full 'int' in size, so that it sscanf properly with %2x. (otherwise it's nasty!!!)");
    __bdata = (unsigned char*)malloc(4+3);
    for (__loopindex=0; __loopindex<4; __loopindex++)
    {
        __bdata[__loopindex] = 0;
    }
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,1,"indx");
    free(__bdata);  //1

    //3) storing variable k
    //----------------

    //4) storing variable k: allocating blob of size 4 plus 3 because we need an extra 3 bytes to fill out the");
    //last 'unsigned char' to be a full 'int' in size, so that it sscanf properly with %2x. (otherwise it's nasty!!!)");
    __bdata = (unsigned char*)malloc(4+3);
    for (__loopindex=0; __loopindex<4; __loopindex++)
    {
        __bdata[__loopindex] = 0;
    }
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,1,"k");
    free(__bdata);  //1

    //3) storing variable i
    //----------------

    //4) storing variable i: allocating blob of size 4 plus 3 because we need an extra 3 bytes to fill out the");
    //last 'unsigned char' to be a full 'int' in size, so that it sscanf properly with %2x. (otherwise it's nasty!!!)");
    __bdata = (unsigned char*)malloc(4+3);
    for (__loopindex=0; __loopindex<4; __loopindex++)
    {
        __bdata[__loopindex] = 0;
    }
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,1,"i");
    free(__bdata);  //1
    //increasing wdadr_ptr1 in order to align variable a1 with alignment requirement of 8
    *wdadr_ptr1 += 1;

    //3) storing variable a1
    //----------------

    //4) storing variable a1: allocating blob of size 80 plus 3 because we need an extra 3 bytes to fill out the");
    //last 'unsigned char' to be a full 'int' in size, so that it sscanf properly with %2x. (otherwise it's nasty!!!)");
    __bdata = (unsigned char*)malloc(80+3);
    for (__loopindex=0; __loopindex<80; __loopindex++)
    {
        __bdata[__loopindex] = 0;
    }
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,20,"a1");
    free(__bdata);  //1

    //3) storing variable loss
    //----------------

    //4) storing variable loss: allocating blob of size 80 plus 3 because we need an extra 3 bytes to fill out the");
    //last 'unsigned char' to be a full 'int' in size, so that it sscanf properly with %2x. (otherwise it's nasty!!!)");
    __bdata = (unsigned char*)malloc(80+3);
    __hexstring = "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    __pos = __hexstring;
    for (__loopindex=0; __loopindex<80; __loopindex++)
    {
        sscanf(__pos,"%2x",&__bdata[__loopindex]);
        __pos += 2;
    }
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,20,"loss");
    free(__bdata);  //1

    //3) storing variable X11
    //----------------

    //4) storing variable X11: allocating blob of size 80 plus 3 because we need an extra 3 bytes to fill out the");
    //last 'unsigned char' to be a full 'int' in size, so that it sscanf properly with %2x. (otherwise it's nasty!!!)");
    __bdata = (unsigned char*)malloc(80+3);
    __hexstring = "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    __pos = __hexstring;
    for (__loopindex=0; __loopindex<80; __loopindex++)
    {
        sscanf(__pos,"%2x",&__bdata[__loopindex]);
        __pos += 2;
    }
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,20,"X11");
    free(__bdata);  //1

    //3) storing variable X1
    //----------------

    //4) storing variable X1: allocating blob of size 80 plus 3 because we need an extra 3 bytes to fill out the");
    //last 'unsigned char' to be a full 'int' in size, so that it sscanf properly with %2x. (otherwise it's nasty!!!)");
    __bdata = (unsigned char*)malloc(80+3);
    __hexstring = "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    __pos = __hexstring;
    for (__loopindex=0; __loopindex<80; __loopindex++)
    {
        sscanf(__pos,"%2x",&__bdata[__loopindex]);
        __pos += 2;
    }
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,20,"X1");
    free(__bdata);  //1

    //3) storing variable X
    //----------------

    //4) storing variable X: allocating blob of size 80 plus 3 because we need an extra 3 bytes to fill out the");
    //last 'unsigned char' to be a full 'int' in size, so that it sscanf properly with %2x. (otherwise it's nasty!!!)");
    __bdata = (unsigned char*)malloc(80+3);
    __hexstring = "0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    __pos = __hexstring;
    for (__loopindex=0; __loopindex<80; __loopindex++)
    {
        sscanf(__pos,"%2x",&__bdata[__loopindex]);
        __pos += 2;
    }
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,20,"X");
    free(__bdata);  //1

    //3) storing variable .LC0
    //----------------

    //4) storing variable .LC0: allocating blob of size 8 plus 3 because we need an extra 3 bytes to fill out the");
    //last 'unsigned char' to be a full 'int' in size, so that it sscanf properly with %2x. (otherwise it's nasty!!!)");
    __bdata = (unsigned char*)malloc(8+3);
    __hexstring = "0000000000000000";
    __pos = __hexstring;
    for (__loopindex=0; __loopindex<8; __loopindex++)
    {
        sscanf(__pos,"%2x",&__bdata[__loopindex]);
        __pos += 2;
    }
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,2,".LC0");
    free(__bdata);  //1

    //3) storing variable .LC2
    //----------------

    //4) storing variable .LC2: allocating blob of size 4 plus 3 because we need an extra 3 bytes to fill out the");
    //last 'unsigned char' to be a full 'int' in size, so that it sscanf properly with %2x. (otherwise it's nasty!!!)");
    __bdata = (unsigned char*)malloc(4+3);
    __hexstring = "59800004";
    __pos = __hexstring;
    for (__loopindex=0; __loopindex<4; __loopindex++)
    {
        sscanf(__pos,"%2x",&__bdata[__loopindex]);
        __pos += 2;
    }
    storeBytesInDM_RW(getSubsystemIndex(),R_proc1,wdadr_ptr1,__bdata,1,".LC2");
    free(__bdata);  //1
   //now we need to increase the wdadr_ptr1 because this model's DM didn't end on a double word boundary
   *wdadr_ptr1 += 1;
//setting the total size of the memory map to 1480
   freeScratchMemoryPointers();
}
DllExport void InputLv2_RR(void *this_, int R_proc1)
{
    rpcControlStructurePointer = this_;
    int __idata = 0;
    int __inDMCode = 0;
    int __extraData;
    ramPassNumber = 1;
    initializeParameterDataRW(this_);

    loadInstance(this_,R_proc1); //new!

    userSuppliedRamPass1Code(this_,R_proc1);
    saveInstance(this_,R_proc1);   //new!
    freeScratchMemoryPointers();
}
DllExport int InputLv2_getDMSize(void *this_, int R_proc1)
{
    return((1480)/4);
}
DllExport void InputLv2_INIT(void *this_)
{
    rpcControlStructurePointer = this_;
    ramPassNumber = 0;
    initializeParameterDataRW(this_);

    userSuppliedRamPass0Code(this_);
}
DllExport unsigned int InputLv2_getVariableDMOffset(char* variableName)
{
    int returnValue;
    if(strcmp("Learning_rate", variableName) == 0)
        returnValue = 0;
    else if(strcmp("input1", variableName) == 0)
        returnValue = 4;
    else if(strcmp("L1", variableName) == 0)
        returnValue = 8;
    else if(strcmp("input2", variableName) == 0)
        returnValue = 12;
    else if(strcmp("input3", variableName) == 0)
        returnValue = 16;
    else if(strcmp("input4", variableName) == 0)
        returnValue = 20;
    else if(strcmp("input5", variableName) == 0)
        returnValue = 24;
    else if(strcmp("input6", variableName) == 0)
        returnValue = 28;
    else if(strcmp("input7", variableName) == 0)
        returnValue = 32;
    else if(strcmp("input8", variableName) == 0)
        returnValue = 36;
    else if(strcmp("input9", variableName) == 0)
        returnValue = 40;
    else if(strcmp("input10", variableName) == 0)
        returnValue = 44;
    else if(strcmp("L2", variableName) == 0)
        returnValue = 48;
    else if(strcmp("L3", variableName) == 0)
        returnValue = 52;
    else if(strcmp("L4", variableName) == 0)
        returnValue = 56;
    else if(strcmp("L5", variableName) == 0)
        returnValue = 60;
    else if(strcmp("L6", variableName) == 0)
        returnValue = 64;
    else if(strcmp("L7", variableName) == 0)
        returnValue = 68;
    else if(strcmp("L8", variableName) == 0)
        returnValue = 72;
    else if(strcmp("L9", variableName) == 0)
        returnValue = 76;
    else if(strcmp("L10", variableName) == 0)
        returnValue = 80;
    else if(strcmp("lamm", variableName) == 0)
        returnValue = 84;
    else if(strcmp("foutput2", variableName) == 0)
        returnValue = 88;
    else if(strcmp("foutput3", variableName) == 0)
        returnValue = 92;
    else if(strcmp("foutput4", variableName) == 0)
        returnValue = 96;
    else if(strcmp("foutput5", variableName) == 0)
        returnValue = 100;
    else if(strcmp("foutput6", variableName) == 0)
        returnValue = 104;
    else if(strcmp("foutput7", variableName) == 0)
        returnValue = 108;
    else if(strcmp("foutput8", variableName) == 0)
        returnValue = 112;
    else if(strcmp("foutput9", variableName) == 0)
        returnValue = 116;
    else if(strcmp("foutput10", variableName) == 0)
        returnValue = 120;
    else if(strcmp("foutput", variableName) == 0)
        returnValue = 124;
    else if(strcmp("numInputs", variableName) == 0)
        returnValue = 128;
    else if(strcmp("numOutputs", variableName) == 0)
        returnValue = 132;
    else if(strcmp("activation", variableName) == 0)
        returnValue = 136;
    else if(strcmp("batch_size", variableName) == 0)
        returnValue = 140;
    else if(strcmp("W", variableName) == 0)
        returnValue = 144;
    else if(strcmp("b", variableName) == 0)
        returnValue = 944;
    else if(strcmp("N", variableName) == 0)
        returnValue = 1024;
    else if(strcmp("n", variableName) == 0)
        returnValue = 1028;
    else if(strcmp("Y", variableName) == 0)
        returnValue = 1032;
    else if(strcmp("L", variableName) == 0)
        returnValue = 1040;
    else if(strcmp("indx", variableName) == 0)
        returnValue = 1048;
    else if(strcmp("k", variableName) == 0)
        returnValue = 1052;
    else if(strcmp("i", variableName) == 0)
        returnValue = 1056;
    else if(strcmp("a1", variableName) == 0)
        returnValue = 1064;
    else if(strcmp("loss", variableName) == 0)
        returnValue = 1144;
    else if(strcmp("X11", variableName) == 0)
        returnValue = 1224;
    else if(strcmp("X1", variableName) == 0)
        returnValue = 1304;
    else if(strcmp("X", variableName) == 0)
        returnValue = 1384;
    else if(strcmp(".LC0", variableName) == 0)
        returnValue = 1464;
    else if(strcmp(".LC2", variableName) == 0)
        returnValue = 1472;
    else 
        returnValue = 0xFFFFFFFF;  // Signal that the variable was not found.
    return returnValue;
}
