VERSION:
3.001

// Include file below is generated by C-Builder      
// and contains the variables declared as -          
// PARAMETERS, INPUTS, OUTPUTS . . .                 
#include "OutputLv2SigDense.h"


STATIC:

// -----------------------------------------------   
// Variables declared here may be used in both the   
// RAM: and CODE: sections below.                    
// -----------------------------------------------   
//    double dt;    

double W[60] = {-0.01194542, 0.02700008, -0.20097231, -0.19964591, 0.04697875, -0.2621471, 
               0.33185596, 0.14779643, 0.36256337, 0.02799838, 0.17271972, 0.13564832, 
               -0.20974577, 0.33184618, -0.05653329, 0.3977786, 0.06664755, 0.30365487, 
               0.37559894, 0.04899491, -0.18130616, -0.24870329, -0.34907727, 0.36320711, 
               0.11352973, 0.26516055, -0.1991046, 0.30390542, 0.14991587, -0.30060835, 
               -0.22997509, -0.15156108, -0.30925243, 0.06241518, -0.10372219, 0.32686743, 
               0.14239957, -0.01676829, 0.13334125, -0.25653699, -0.40567608, 0.38335856, 
               0.12191811, -0.14301099, 0.06033108, -0.42277535, 0.03786547, -0.14868022, 
               0.15301943, 0.3113031, 0.21232252, 0.20718283, 0.03385868, -0.39083904, 
               -0.09629824, 0.41479473, 0.10734768, 0.42113613, -0.18060257, 0.00439339};

double b[6] = {0.0,0.0,0.0,0.0,0.0,0.0};

double Wd[6] = {1.68943792, 0.90880629, 1.63581244, 0.50655374, -1.21481088, 0.55139419};

double bd[6] = {0.0};

int N;
int n;
int Y;


// - E n d   o f   S T A T I C :   S e c t i o n -   

RAM_FUNCTIONS:

// -----------------------------------------------   
// This section should contain any 'c' functions     
// to be called from the RAM section (either         
// RAM_PASS1 or RAM_PASS2). Example:                 
//                                                   
// static double myFunction(double v1, double v2)    
// {                                                 
//     return(v1*v2);                                
// }                                                 
// -----------------------------------------------   

RAM:
n = numInputs + numOutputs;
N = numInputs;
Y = numOutputs;

// -----------------------------------------------   
// Place C code here which computes constants        
// required for the CODE: section below.  The C      
// code here is executed once, prior to the start    
// of the simulation case.                           
// -----------------------------------------------   
//    dt= getTimeStep();                             


// ------------- End of RAM: Section -------------   

CODE_FUNCTIONS:

double preOutput = 0.0;
double preOutput2 = 0.0;
double out1;
double out2;

int i;
int k;
double preOutputa[6] = {0.0};
double out[6] = {0.0};
double Xout[6] = {0.0};
double X[10] = {0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0};
double X1[10] = {0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0};
double dLoss_da2[6];
double loss[6] = {0.0,0.0,0.0,0.0,0.0,0.0};

double lossy1;
double lossy2;

double da[10] = {0.0};
double dasig[10] = {0.0};
double dW;

double sigmoid(double x) {
    return 1.0 / (1.0 + exp(-x));
}

static void LoadX(int N){

X[0] = input1;
if (N>1){
	X[1] = input2;
	if (N>2){
		X[2] = input3;
		if (N>3){
			X[3] = input4;
			if (N>4){
				X[4] = input5;
				if (N>5){
					X[5] = input6;
					if (N>6){
						X[6] = input7;
						if (N>7){
							X[7] = input8;
							if (N>8){
								X[8] = input9;
								if (N>9){
								  X[9]=input10;

								}
							}

						}
					}
				}
			}
		}
	}
	
}


}


static void Feed6Forward(int N){
double preOutputa[6] = {0.0};

for (i = 0; i < N; i++){
	for (k = 0; k < Y; k++){

		preOutputa[k] += W[i+N*k] * X[i];
	}
}

for (k = 0; k < Y; k++){
	Xout[k] = sigmoid(preOutputa[k] + b[k]);
	out[k] = Xout[k] * Wd[k] + bd[k];
	dasig[k] = Xout[k] * (1 - Xout[k]);
}

}



static void Back6prop(double loss[6], int N, double alpha, double lambda){

double da[10] = {0.0}; 
for (i = 0; i < Y; i++){
	b[i] = b[i] - alpha * loss[i] * Wd[i]*dasig[i];

	for (k = 0; k < N; k++){
	da[k] += loss[i]* Wd[i]* dasig[i] * W[k+i*N];
	dW = loss[i]*Wd[i]*dasig[i] * X[k];
	W[k+i*N] = W[k+i*N] - alpha * dW - lambda * 	((W[k+i*N] > 0) - (W[k+i*N] < 0));

	}
Wd[i] = Wd[i] - alpha * loss[i] * Xout[i];
bd[i] = bd[i] - alpha * loss[i]; 
}

}



static void FeedForward(int N){

preOutput = 0.0;
preOutput2 = 0.0;

for (i = 0; i < N; i++){

preOutput += W[i] * X[i];
preOutput2 += W[i+N] * X[i];
}
Xout[0] = sigmoid(preOutput + b[0]);
Xout[1] = sigmoid(preOutput2 + b[1]);

dasig[0] = Xout[0] * (1 - Xout[0]);
dasig[1] = Xout[1] * (1 - Xout[1]);

out1 = Xout[0] * Wd[0] +bd[0];
out2 = Xout[1] * Wd[1] +bd[1];

}



static void Backprop(double loss, double loss2, int N, double alpha, double lambda){
	double da[10] = {0.0}; 
for (i = 0; i < N; i++){

da[i] = loss * Wd[0]* dasig[0] *W[i] + loss2* Wd[1] * dasig[1] *W[i+N];

W[i] = W[i] - alpha * loss* Wd[0]*dasig[0] *X[i]- lambda * ((W[i] > 0) - (W[i] < 0));
W[i+N] = W[i+N] - alpha * loss2 * Wd[1]*dasig[1]  *X[i]- lambda * ((W[i+N] > 0) - (W[i+N] < 0));

}

b[0] = b[0] - alpha * loss * Wd[0] * dasig[0];
b[1] = b[1] - alpha * loss2 * Wd[1] * dasig[1];

bd[0] = bd[0] - alpha * loss;
bd[1] = bd[1] - alpha * loss2;
Wd[0] = Wd[0] - alpha * loss * Xout[0];
Wd[1] = Wd[1] - alpha * loss2* Xout[1];


}


static void saveX(int N){
for (i = 0; i<N; i++){ 
X1[i] = X[i];
}
}

static void LoadL(int Y){
loss[0] = L1;
if (Y>1){
	loss[1] = L2;
	if (Y>2){
		loss[2] = L3;
		if (Y>3){
			loss[3] = L4;
			if (Y>4){
				loss[4] = L5;
				if (Y>5){
					loss[5] = L6;
				}
			}
		}
	}
}
}


CODE:

if (Learning_rate>0.0){
	LoadL(Y);

	if (Y<3){
		Back6prop(loss, N, Learning_rate, lam);

	}

	else{

		Backprop(L1, L2, N, Learning_rate, lam);

	}
	Li1 = da[0];
Li2 = da[1];
Li3 = da[2];
Li4 = da[3];
Li5 = da[4];
Li6 = da[5];
Li7 = da[6];
Li8 = da[7];
Li9 = da[8];
Li10 = da[9];
}




LoadX(N);

if (Y<3){

FeedForward(N);
foutput = out1;
foutput2 = out2;

}

else{

Feed6Forward(N);
foutput = out[0];
foutput2 = out[1];
foutput3 = out[2];
foutput4 = out[3];
foutput5 = out[4];
foutput6 = out[5];

}
// -----------------------------------------------   
// Place C code here which runs on the RTDS. The     
// code below is entered once each simulation        
// step.                                             
// -----------------------------------------------   


// ------------ End of CODE: Section -------------   